### ISSUE TITLE
Targeted Keypad Scene Button Backlight Toggle?

### ISSUE THREAD

**Issue by THX723** [kuestess/homebridge-platform-insteonlocal#101]
Currently it is possible to configure a device as `'scenes'`, which will properly set the backlight of any linked keypad scene buttons. However scenes support is currently an On/Off only affair and incapable of dimming levels.

Instead, would it be possible to extend the code for device configuration to also facilitate direct setting of specific backlight of a given keypad (through INSTEON Extended-length Direct Commands)?

Consider the following normal configuration, where `TV Light` is a dimmer module that is linked to `button B` of `Porch Light Keypad`.

```
                {
                    "name": "TV Light",
                    "deviceID": "3A637C",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
                {
                    "name": "Porch Light Keypad",
                    "deviceID": "525C89",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
```

It might look something like below, where `"targetIDs"` and `"targetButtons"` (for the lack of better names) are arrays for the linked `DeviceID` and `Keypad Button` respectively.

The expected result would then be when `TV Light` is turned on or set anywhere above 0%, `button B` backlight is set on the `Porch Light Keypad`.

```
                {
                    "name": "TV Light",
                    "deviceID": "3A637C",
                    "dimmable": "yes",
                    "deviceType": "lightbulb",
           NEW>>>>> "targetIDs": ["525C89", "<deviceID2>", "<deviceID 3>" ],
           NEW>>>>> "targetButtons": ["B", "<button for deviceID2>", "<button for deviceID3>"]
                },
                {
                    "name": "Porch Light Keypad",
                    "deviceID": "525C89",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
```

Hopefully that all made sense.

Let me know if you need help with the Insteon Extended-length Direct Command that is used to set the keypad buttons.

**Comment by THX723** [comment]
@kuestess I tried to study your code and noted there's already a nifty setKeypadState function using direct command to set the keypad button LEDs. Awesome.

So hopefully to make this work, it is as simple as injecting an additional setKeypadState call after acknowledging state changed in each setBrightnessLevel, setRelayState, ... etc. methods.

For-loop used to step through the array of all targeted keypad devices.

If the extended configuration in config.json (keypadID, keypadType, keypadKey) do not exist for a given device, then the extra setKeypadSate call is skipped.

Some adjustments to the proposed config.json changes:

`"keypadID" : ["deviceID1", "deviceID2", "deviceID3, ..."]` ... array of all targeted keypad device IDs.
`"keypadType" : ["6", "6", "8", ... ]` ... array of 6 or 8 button layout corresponding to keypadID array.
`"keypadKey" : ["A", "D", "F", ... ]` ... array of keypad button (A-H) corresponding to keypadID array.


Sample config.json,
```
                {
                    "name": "TV Light",
                    "deviceID": "3A637C",
                    "dimmable": "yes",
                    "deviceType": "lightbulb",
                    "keypadID": ["525C89",  "4219FD"],
                    "keypadType": ["8", "6"],
                    "keypadKey": ["F", "A"]
                },
                {
                    "name": "Porch Light Keypad",
                    "deviceID": "525C89",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
                {
                    "name": "Dining Light",
                    "deviceID": "4219FD",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
```

**Comment by kuestess** [comment]
@THX723 If I understand the concept, isn't this something that you could also do with Insteon links - ie, link the dimmer as a controller of the keypad button?

**Comment by THX723** [comment]
@kuestess Yes and no. My devices are in fact linked accordingly and behave as you'd expect when using the Insteon for Hub app. However, if you initiated it via HomeKit, the set keypad button state step is not carried out.

**Comment by THX723** [comment]
@kuestess Hooray! I was able to refactor the code and make this a reality. Specified keypad button are now turned On/Off accordingly to the linked device. To keep it simple for now, each device can only associate 1 keypad and button for now. Later we can expand to using arrays to handle multiple keypads/buttons per device.

Let me know how I can contribute the code, so some of you can also test it out and expand on it too.

**Comment by kuestess** [comment]
@THX723 Very cool!  You can submit a PR and I'll review.

**Comment by THX723** [comment]
@kuestess Done!

**Comment by THX723** [comment]
@kuestess Alrighty. Support for multiple target keypads/buttons per device has been added in the latest pull request. Took a lot more hair pulling than expected. Give it workout and let me know what you think.

**Comment by THX723** [comment]
Released in latest code.

**Comment by shereefalkady** [comment]
@kuestess @thx723 can i activate a scene/group from a mini remote?

tried the below and many variations nothing works.... i only get the event not for correct group message
 {
                    "name": "Test Remote C",
                    "deviceID": "3F06AF",
                    "deviceType": "remote",
                    "remotebtn": "D",
                    "groupID": "4",
                    "dimmable": "no",
                    "groupMembers": "43E77B,44EF63"
                },
