### ISSUE TITLE
Fanlinc LED Control

### ISSUE THREAD

**Issue by Mattapoisett** [kuestess/homebridge-platform-insteonlocal#105]
Thank you for providing a great piece of software. I'm using it to connect 4 Fanlincs through Homebridge to HomeKit and so far so good.  I have one small issue.  The Fanlinc controller has 2 indicator lights on the unit which are always on.  Unfortunately they are bright enough to be annoying when all the lights are out.  Apparently there's a way flags can be set in the controller to turn them off. Is there a way to change the setting through Insteon Local? Your operational Flags tab doesn't allow changes. Recently, I tried using an HTTP Command string, which didn't work 192.xxx.xx.xx:25105/3?0262YYYYYY2008=I=3. Also, have tried loading the old Homelinc Software on a PC but wasn't able to connect to my 2245-2222 hub. Any suggestions would be appreciated, because the next step will involve gaffers tape.

**Comment by Mattapoisett** [comment]
Following up.  I've since corrected the HTTP Command String <http://username:password@xxx.xxx.xxx.xxx:yyyyy/3?0262zzzzzz0F2008=I=3> but It still is not working but it seemingly does go through. The Command Flag info I got from the [Fanlinc Developer's Guide](http://cache.insteon.com/developer/2475Fdev-022012-en.pdf) and the string Syntax came from [Insteon Support](https://www.insteon.com/support-knowledgebase/tag/Wearable) Also, I've figured out how to use Your Express Server to control the Fanlinc, it wasn't apparent to me initially. However, I haven't found syntax which will do what I want it to do.

**Comment by kuestess** [comment]
@Mattapoisett Apologies for the delay - buried under work and family obligations.  Will probably get some time later this week to look into it more.

**Comment by Mattapoisett** [comment]
@kuestess it good to hear from you.  I totally understand.  Thanks again.

**Comment by Mattapoisett** [comment]
I have found the solution.  There is actually a setting in the app to control the LED backlights.  However, the first controller wouldn’t respond to the command so I thought the setting was for something else.  The other 2 installed Fanlincs now have their LEDs turned off. Now I need to factory reset the misbehaving one to see if it will respond to the command.  Thanks Again!
