### ISSUE TITLE
Changelog issue with homebridge-config-ui-x

### ISSUE THREAD

**Issue by THX723** [kuestess/homebridge-platform-insteonlocal#111]
Using [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x), which has appropriately detected an update from this plug-in.

<img width="726" alt="Screen Shot 2020-06-17 at 2 30 09 PM" src="https://user-images.githubusercontent.com/25112621/84953333-2d58a580-b0a8-11ea-8125-9868875f0cb7.png">

Yet somehow, the release notes it displayed seemed outdated.

<img width="845" alt="Screen Shot 2020-06-17 at 2 29 33 PM" src="https://user-images.githubusercontent.com/25112621/84953539-8f190f80-b0a8-11ea-9782-45f8610bca0f.png">

I can't figure out where that text might have come from. It's certainly not from CHANGELOG.md in this git. I'm wondering if it might be on the npm side?

**Comment by kuestess** [comment]
@THX723 I don’t know where that comes from, although it appears to be the commit message from GitHub....although from the previous update.  This is likely an issue with `homebridge-config-ui-x`.

**Comment by THX723** [comment]
@kuestess I'll raise an issue with `homebridge-config-gui-x`.

**Comment by THX723** [comment]
@kuestess got response back from oznu. Looks like it is pulling the release notes from the release tag [here](url).

**Comment by kuestess** [comment]
@THX723 Interesting....its getting the version number likely from the package.json or npm but looking specifically at releases for the change notes.  Ideally you would get all of that information from a single place.  I stopped publishing to releases a while back as I didn't think they were used and they take time to put together.  I won't likely get to this soon, but will see if I can figure out how to automate releases.

**Comment by THX723** [comment]
@kuestess totally understand. It's one of those thankless jobs, so don't stress over it.
Oops, just noticed I screwed up the link above; should have pointed to [https://github.com/kuestess/homebridge-platform-insteonlocal/releases](https://github.com/kuestess/homebridge-platform-insteonlocal/releases).

FYI, `config-gui-x` pulls that info and presents to the user prior at update confirmation (go/no-go). Then after the update, it presents the text within CHANGELOG.md.

**Comment by kuestess** [comment]
Closing, fancy new GitHub action in place that automates releases.
