### ISSUE TITLE
HubPro Automatically boot SD card

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#112]
how do i make it so if the power goes out in my home the HubPro will boot automatically to the SC card rather than me holding the S2 button?

**Comment by kuestess** [comment]
@yonigold1 The easiest way to do it is to flash the SD card to the internal mmc of the Hub.  This will overwrite what is there from Insteon so you would no longer be able to use it as an out of the box Hub Pro, but if you're using this plugin that probably doesn't matter to you :-).  After you do this the SD card is no longer needed.  See here:

[https://stackoverflow.com/questions/31725206/unable-to-flash-emmc-from-sd-card-beaglebone-black/40180517#40180517](https://stackoverflow.com/questions/31725206/unable-to-flash-emmc-from-sd-card-beaglebone-black/40180517#40180517)

**Comment by yonigold1** [comment]
Hey so i jsut got around to trying this and it doesnt seem to be working for me the light on the board is just blinking at a steady pace and i cant figure out what to do :(

**Comment by kuestess** [comment]
@yonigold1 When I did it, it took quite a while.  Try booting from your SD card again (hold S2) and let it re-flash.

**Comment by yonigold1** [comment]
i did it 😃🥳

**Comment by Calorion** [comment]
This is not working for me, even if I leave it overnight. I've tried several times. The BeagleBone boards say that maybe it's not getting enough power? https://forum.beagleboard.org/t/flashing-emmc-help/31893/13

Am I doing something wrong here?
