### ISSUE TITLE
Two hubs in config, first one in config won't work

### ISSUE THREAD

**Issue by patchg** [kuestess/homebridge-platform-insteonlocal#114]
This is really an update to issue #52, but now both hubs are 2245's.  (I finally upgraded the old 2242)

I have two hubs in my setup, a 2245 and a 2245. (two buildings on the same wifi network but separate electrical services and 800' apart, house and a barn).

When both hubs are properly configured in the config.json the first hub (house) will communicate in the launch sequence, and the devices will be reachable according to the log.  Then the second hub (barn) will exhibit the same behavior.  Everything is looking good as we finish starting up!

Once the next polling happens (either by setting the refresh value for the hubs or a device command from homebridge) The first hub (house) devices won't respond.  The second hub (barn) is fine.

If I switch the hubs order in the config, its still the first hub that will have the issue... now the barn

It looks like we're holding on to the hub config of the last hub in the start up sequence.

Individually they work.

**Comment by kuestess** [comment]
@patchg The plugin isn't currently set up to handle multiple hubs in a single config.  Something I can look into adding, but for the time being your best bet is probably to spin up a separate instance of homebridge.  Should get you to the same end result.

**Comment by patchg** [comment]
Ok, thanks.  If you do look to add that capability, let me know and I'll be happy to test.
