### ISSUE TITLE
Support for HomeKit scenes with Brightness but no Power State?

### ISSUE THREAD

**Issue by BrechFiwalli** [kuestess/homebridge-platform-insteonlocal#115]
With the Hub Pro, I had scenes that for some lights would set the brightness but I removed the Power State action.  This way if the room was already off it would stay off but if it was on, it would change the brightness (usually dimmer).  

With insteonlocal all SetBrightness calls will set the Power State to On. My understanding is that homekit usually sends both so removing the implicit SetPowerState(on) on SetBrightness would still work as normal for most things except where explicitly not wanting to turn it on.  

Can it be changed to support this like the Hub Pro did?

**Comment by kuestess** [comment]
@BrechFiwalli Unfortunately, the Insteon command set only has scene on/off and scene dim/brighten commands.  There is no ‘scene on at level’ command (at least that is documented).  I have some thoughts on how I might be able to get to what you’re asking for, but I don’t expect it to be an experience that most would find acceptable (I might be surprised :-)).  Would be interesting to sniff the traffic from an original Hub Pro to see if they use an undocumented command to get to what you describe above.
