### ISSUE TITLE
Newbie: Numerous deprecated assets during install; Initial config docs question

### ISSUE THREAD

**Issue by mmorper** [kuestess/homebridge-platform-insteonlocal#116]
I just installed this plugin, however during installation I noticed several assets denoted deprecation. 

<img width="852" alt="CleanShot 2020-09-16 at 09 43 14@2x" src="https://user-images.githubusercontent.com/15195056/93367879-f78ba000-f801-11ea-8b06-b78fba0d6ded.png">

Perhaps related, I am unclear how to proceed with configuration per the docs:

> Direct your browser to the host that you have Insteonlocal **running on and the port configured in your config.json (ie, 127.0.0.1:3000 if running on the local machine)**. Before using any of the pages described below, you will need to complete the following steps:

Is there no configuration UI for this plugin or is configuration all 100% in the config itself?

**Comment by kuestess** [comment]
@mmorper You can safely ignore those deprecation warnings, everything should work just fine.  To get started on the config, you can copy in the example config (updated for your network) and then open the address of your homebridge host and the port in the config (default 3000) to do the remainder of the config.  Let me know if you have questions.
