### ISSUE TITLE
only one device actually shows up in home kit

### ISSUE THREAD

**Issue by MsTreeWoman** [kuestess/homebridge-platform-insteonlocal#118]
What, if anything, am i doing wrong?  (i'm very new to home bridge.  running on a HOOBS system.  no matter what i add, only Front Floodlights actually shows up in home kit.  no errors in the log (all devices are seen and added).
{
    "bridge": {
        "name": "HOOBS",
        "username": "xxxxxxxxxxxxx",
        "pin": "xxxxxxxxx"
    },
    "platform": "InsteonLocal",
    "user": "xxxxxx",
    "password": "xxxxxxxx",
    "host": "192.168.0.29",
    "port": "25105",
    "model": "2245",
    "refresh": "0",
    "use_express": "true",
    "server_port": "3000",
    "keepAlive": "3600",
    "devices": [
        {
            "name": "Master Bathroom Light",
            "deviceID": "3D.47.B0",
            "Dimmable": "yes",
            "DeviceType": "switch"
        },
        {
            "name": "Front Floodlights",
            "deviceID": "3D.47.66",
            "dimmable": "yes",
            "deviceType": "switch"
        },
        {
            "name": "Kitchen Light",
            "deviceID": "40.69.63",
            "dimmable": "yes",
            "DeviceType": "dimmer"
        },
        {
            "name": "Hall Light",
            "deviceID": "40.5A.61",
            "dimmable": "yes",
            "DeviceType": "dimmer"
        }
    ]
}

**Comment by kuestess** [comment]
@MsTreeWoman For "Kitchen Light" and "Hall Light", change "DeviceType" to "deviceType".  Case matters :-).

**Comment by MsTreeWoman** [comment]
Thank you for creating this amazing program.

I made the changes and your program now sees them.  HOME in IOS sees them.  3 questions:

1. The lights still do not turn off or on (no error messages in the main log).  So no action despite the setting appear to be correct.
2. Is there a deeper debug option?  something that shows the activity and responses.
3. the simple use_express UI does not seem to be accessible.  I try to go to 192.168.0.1:3000.  i try to go to hoobs.local:3000.  how do i get there?

here is the code:

{
    "platform": "InsteonLocal",
    "name": "Insteon Local Platform",
    "user": “XXXX0000",
    "password": “PASSWORD",
    "host": "192.168.0.29",
    "port": "25105",
    "model": "2245",
    "refresh": "0",
    "use_express": "true",
    "server_port": "3000",
    "keepAlive": "3600",
    "devices": [
        {
            "name": "Master Bathroom Light",
            "deviceID": "3D.47.B0",
            "dimmable": "yes",
            "deviceType": "lightbulb"
        },
        {
            "name": "Front Floodlights",
            "deviceID": "3D.47.66",
            "dimmable": "yes",
            "deviceType": "lightbulb"
        },
        {
            "name": "Kitchen Light",
            "deviceID": "40.69.63",
            "dimmable": "yes",
            "deviceType": "lightbulb"
        },
        {
            "name": "Hall Light",
            "deviceID": "40.5A.61",
            "dimmable": "yes",
            "deviceType": "lightbulb"
        }
    ]
}

**Comment by MsTreeWoman** [comment]
i've gone through most of the issues throughout your GitHub account, made a few changes.  All devices are 'seen' in terms of the software.  All devices registered as devices with home kit.  but when i turn a light on or off using home kit (or on homebridge), i get an error message (log below)...  This is very similar to what others have seen.  wondering if i should use another hub (i think i have 2 working ones)?

Oct 23 17:39:15 hoobs hoobs[571]: [10/23/2020, 5:39:15 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
Oct 23 17:39:15 hoobs hoobs[571]: [Insteon Local Platform] Initializing InsteonLocal platform...
Oct 23 17:39:15 hoobs hoobs[571]: Initializing Insteon UI
Oct 23 17:39:15 hoobs hoobs[571]: [Insteon Local Platform] Started connection watcher...
Oct 23 17:39:15 hoobs hoobs[571]: [Insteon Local Platform] Found 4 devices in config
Oct 23 18:07:41 hoobs hoobs[808]: [10/23/2020, 6:07:41 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
Oct 23 18:07:41 hoobs hoobs[808]: [Insteon Local Platform] Initializing InsteonLocal platform...
Oct 23 18:07:41 hoobs hoobs[808]: Initializing Insteon UI
Oct 23 18:07:41 hoobs hoobs[808]: [Insteon Local Platform] Started connection watcher...
Oct 23 18:07:41 hoobs hoobs[808]: [Insteon Local Platform] Found 4 devices in config
Oct 23 18:08:27 hoobs hoobs[808]: [Insteon Local Platform] Setting power state of Master Bathroom Light to on
Oct 23 18:08:38 hoobs hoobs[808]: [Insteon Local Platform] Error setting power state of Master Bathroom Light to on
Oct 23 18:08:38 hoobs hoobs[808]: [Insteon Local Platform] Getting status for Master Bathroom Light
Oct 23 18:08:48 hoobs hoobs[808]: [Insteon Local Platform] Error getting power state of Master Bathroom Light

**Comment by kuestess** [comment]
@MsTreeWoman The plugin isn't connecting to your hub - you should see a 'Connected to ...' message in the log.  First, just verifying that you are using the Hub user/password and not the one that you use to initially log into the app.  If so, change to the hub credentials.  Sometimes hubs also like to do a fun thing where they change the password on you :-).  Its easy to fix - go in to the Insteon app and change the Hub password (NOT your Insteon account password).  This will re-sync the password in the app with that in the hub, and you should be able to use those credentials in your config.

**Comment by MsTreeWoman** [comment]
kuestess - Please close this issue.  If you look at my json file, i had "password" instead of "pass".  I made this correction and everything works.  Once again, an amazing piece of work - I've been a computer programmer for over 30 years, and I should know that a keyword is a keyword.
