### ISSUE TITLE
Issues setting up insteonlocal on RaspberryPi 

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#122]
Hi, @kuestess hope you're doing well! I have just purchased a RaspberryPi 4 Model B 4GB because I wanted to expand my homebridge setup to more devices as I previously set up a homebridge instance on my Insteon Hub Pro 2243 and it worked great however it had less than 1GB or memory and I couldn't setup cameras to stream over that as it wont be able to handle it.

Anyway I of course still need my Hub Pro I just want to transfer the setup from my Hub Pro to my new Pi however I have done that but I get this error after **attempting** to setup the insteonlocal plugin:
<img width="1412" alt="Screen Shot 2020-11-22 at 3 49 50 PM" src="https://user-images.githubusercontent.com/34217684/99916814-5d9d1380-2cda-11eb-8266-b2ff1f3eaee6.png">

Now if I recall I had this issue originally on my Hub Pro in issue #94 and I checked what you said there and you said to double-check if I had enabled serial port on my HubPro (BeagleBone Black) and after that it worked but I went to look on my Pi to do those same steps but I first wanted to ask you if that was safe to do and second i don't even see the file /boot/uEnv.txt. 

On my Pi installed Homebridge using the Homebridge Raspberry Pi Image so it was directly installed.

Please help me I'm so stuck 😩.

**Comment by kuestess** [comment]
@yonigold1 For the HubPro, the plugin uses the direct serial port connection as the Insteon modem in the Pro doesn't have a network interface.  In other words, the plugin has to be running directly on the HubPro.  The error that you get above is because it can't open the serial port (which probably doesn't exist on the Pi).  I found this post that might be a quick and dirty way to bridge the serial pot on the Hub Pro over the network to a virtual serial port on the Pi.  [https://stackoverflow.com/questions/29207980/bridge-serial-ports-over-network](https://stackoverflow.com/questions/29207980/bridge-serial-ports-over-network).  Not sure if that will work, but worth a try.  Alternately, might be interesting to adapt one of my other projects 'Insteon-server` to work with the plugin, but that's not likely a quick solution.

**Comment by yonigold1** [comment]
Thanks for the quick response! 

What's the Insteon-Server do and how would that help my situation?

**Comment by kuestess** [comment]
@yonigold1 [insteon-server](https://github.com/kuestess/insteon-server) is a server that could run on the Hub Pro, connect via the serial connection (like the plugin currently does) and the allow for control and relay status updates across the network to a different server - in this instance the Pi.  The issue is that the homebridge plugin doesn't currently have any way of sending control commands to insteon-server or understanding status messages from the insteon-server.  It was originally written for Smartthings/Hubitat.  The home bridge plugin could be adapted to speak to Insteon-server, but its not a small task.

**Comment by yonigold1** [comment]
would it be an easy setup to make the Pi and the Hub Pro talk to each other or will it take a lot of time ?

**Comment by kuestess** [comment]
@yonigold1 I was able to get this to work using `ser2net` and `socat`.  Here's a rough step-by-step:

On the HubPro:
1. Install `ser2net` : `sudo apt-get install ser2net`
2. Edit `/etc/ser2net.conf`so the contents are `3333:raw:0:/dev/ttyS4:19200 8DATABITS NONE 1STOPBIT`
3. Reboot the Hub Pro

On the Pi:
1. Install `socat`: `sudo apt-get install socat`
2. Add your user to the dialout group: `sudo usermod -a -G dialout YOUR_USER_NAME` then reboot the Pi
3. Start a virtual serial port: `socat pty,link=/dev/ttyS4,waitslave tcp:HUB_PRO_IP_ADDRESS:3333 &`
4. Run `homebridge`
5. Profit

Ser2net on the HubPro bridges the serial port on the PLM to port '3333'.  Socat creates a virtual serial port `/dev/ttyS4` on the Pi that is connects to port 3333 on the HubPro.  This worked for me just as if it were running directly on the Hub Pro, although I didn't test response speed extensively (seemed to be the same in limited testing).  Hope this helps!

**Comment by yonigold1** [comment]
Will give this a try and let you know! thanks so much!

**Comment by yonigold1** [comment]
> @yonigold1 I was able to get this to work using `ser2net` and `socat`. Here's a rough step-by-step:
> 
> On the HubPro:
> 
> 1. Install `ser2net` : `sudo apt-get install ser2net`
> 2. Edit `/etc/ser2net.conf`so the contents are `3333:raw:0:/dev/ttyS4:19200 8DATABITS NONE 1STOPBIT`
> 3. Reboot the Hub Pro
> 
> On the Pi:
> 
> 1. Install `socat`: `sudo apt-get install socat`
> 2. Add your user to the dialout group: `sudo usermod -a -G dialout YOUR_USER_NAME` then reboot the Pi
> 3. Start a virtual serial port: `socat pty,link=/dev/ttyS4,waitslave tcp:HUB_PRO_IP_ADDRESS:3333 &`
> 4. Run `homebridge`
> 5. Profit
> 
> Ser2net on the HubPro bridges the serial port on the PLM to port '3333'. Socat creates a virtual serial port `/dev/ttyS4` on the Pi that is connects to port 3333 on the HubPro. This worked for me just as if it were running directly on the Hub Pro, although I didn't test response speed extensively (seemed to be the same in limited testing). Hope this helps!

Question when editing the /etc/ser2net.conf file what am I changing?
<img width="392" alt="Screen Shot 2020-11-30 at 1 53 39 PM" src="https://user-images.githubusercontent.com/34217684/100651461-75484d80-3313-11eb-99af-3907d53e05bc.png">
that's what the file looks like am I just adding the line: 3333:raw:0:/dev/ttyS4:19200 8DATABITS NONE 1STOPBIT to the bottom? or do I delete EVERYTHING in the file and just write 3333:raw:0:/dev/ttyS4:19200 8DATABITS NONE 1STOPBIT?

**Comment by yonigold1** [comment]
I followed all those steps but I'm running into this
<img width="1440" alt="Screen Shot 2020-11-30 at 2 13 22 PM" src="https://user-images.githubusercontent.com/34217684/100653340-3e276b80-3316-11eb-9730-f5591faa06b0.png">

**Comment by yonigold1** [comment]
What should my config look like on my Pi?

**Comment by kuestess** [comment]
@yonigold1 Yes, you're correct - you can delete everything in ser2net.conf and replace with `3333:raw:0:/dev/ttyS4:19200 8DATABITS NONE 1STOPBIT`.  On the Pi, you can just copy over the insteonlocal config from your Hub Pro and use that exactly as it is (this assumes that you use `socat pty,link=/dev/ttyS4,waitslave tcp:HUB_PRO_IP_ADDRESS:3333 &` for scout on the Pi - the port has to be `/dev/ttyS4` in order to use the Hub Pro config unchanged).

**Comment by yonigold1** [comment]
so i followed everything and i still cant seem to get it to work. My Pi outputs this when I enter, (I needed to put `sudo` it said permission denied if I didn't) `sudo socat pty,link=/dev/ttyS4,waitslave tcp:192.168.2.28:3333 &` 
<img width="852" alt="Screen Shot 2020-12-03 at 9 35 52 PM" src="https://user-images.githubusercontent.com/34217684/101114605-d3915c80-35af-11eb-82bb-8d7d78981f46.png">
I have no clue what the output means lol but then after restarting homebridge i see this in my homebridge logs:
<img width="1411" alt="Screen Shot 2020-12-03 at 9 33 10 PM" src="https://user-images.githubusercontent.com/34217684/101114652-eefc6780-35af-11eb-9470-7962a40d2e25.png">

let me know what I'm doing wrong cause I got no clue

**Comment by yonigold1** [comment]
I actually managed to fix it by running this: `sudo chmod 777 /dev/ttyS4`

I do have 2 questions though,
I now have both the HubPro's Homebridge with all the Insteon devices AND the Pi with all the Insteon devices, what can I remove? Do I simply remove the HubPro from my Home app?

My second question is now that I have set this up is that every time I reboot the Pi I'm going to have to run `sudo socat pty,link=/dev/ttyS4,waitslave tcp:192.168.2.28:3333 &` ? or will it not require that? if it requires me to do so is there a way to not have to run that?

**Comment by yonigold1** [comment]
So i have been playing around and it seems that upon every restart of homebridge both commands (`sudo chmod 777 /dev/ttyS4` and `sudo socat pty,link=/dev/ttyS4,waitslave tcp:192.168.2.28:3333 &` ) are undone and i must re-enter them upon restarting homebridge, is there anyway i can program the pi to do input these commands before homebridge starts up?

**Comment by kuestess** [comment]
@yonigold1 Permissions are a pain!  You should be able to avoid those issues by adding your user to the`dialout` group with `sudo usermod -a -G dialout YOUR_USER_NAME` (sub in your username on the Pi).  Otherwise, you can easily do it with a short bash script.

**Comment by yonigold1** [comment]
So i did that and ran `sudo usermod -a -G dialout pi` but it still seems to not work

**Comment by kuestess** [comment]
@yonigold1 Hmm, that's strange - are you running homebridge as the 'pi' user as well?

**Comment by yonigold1** [comment]
yes i beleive i am. i ran the command `groups` and i see a bunch of users but the command `sudo usermod -a -G dialout [USER]`only runs when run it with the user pi other wise it doesn't work and outputs with `usermod: user '[USER]' does not exist` 
<img width="870" alt="Screen Shot 2020-12-04 at 11 26 32 AM" src="https://user-images.githubusercontent.com/34217684/101188329-9070d100-3623-11eb-83c1-7e1422b2c9fc.png">
i installed the homebridge pi image and thought that maybe the user is homebridge but its not.

**Comment by yonigold1** [comment]
any idea on what i can do?

**Comment by kuestess** [comment]
@yonigold1 You should be able to put `socat pty,link=/dev/ttyS4,waitslave tcp:192.168.2.28:3333 &` (without the sudo) in `/etc/rc.local' before `exit 0` and it will run automatically on boot.  I tried this and it gave me the correct permissions on `/dev/ttyS4` so the chmod wasn't necessary.

**Comment by yonigold1** [comment]
i'm not sure why it doesn't want to work but that command `socat pty,link=/dev/ttyS4,waitslave tcp:192.168.2.28:3333 &` doesn't even work with sudo like the chmod seems necessary unfortunately.

i also tried placing it in the rc.local before exit 0 and still won't work so i'm going to put the chmod command in the rc.local for the time being until we can find a real solution :)

**Comment by yonigold1** [comment]
i've also been playing around with rc.local and i can't seem to get any of the commands to run on startup through rc.local :(

**Comment by kuestess** [comment]
@yonigold1 I installed the Homebridge image on a spare Pi, and adding to `rc.local` worked fine.  Make sure `rc.local` is set to executable (should be by default).

**Comment by yonigold1** [comment]
so I did it and ill list what I did so that anyone who wants to attempt this in the future can:

### Tutorial:
⚠️ **Make sure you have followed the steps above until you reach the part I got stuck at as this tutorial will start off from where I was stuck.** ⚠️
1. ssh into your pi and make sure ur in the home directory (if you're not already run this: `cd ~` )
2. create bash file with a simple name of your choice (I will use SCRIPT1 for an example) by running `nano FILENAME.sh` in the file start it off with this `#!/bin/bash` then return 2 lines down and enter `socat pty,link=/dev/ttyS4,waitslave tcp:HUB_PRO_IP_ADDRESS:3333 &` your script should look like this: <img width="878" alt="Screen Shot 2020-12-09 at 12 10 33 PM" src="https://user-images.githubusercontent.com/34217684/101662461-8c73f300-3a17-11eb-874c-16aa599f28ac.png">
3.  Next save the file and exit 
4. Now create another script with a different simple name (I will use SCRIPT2 for the second) and put the `#!/bin/bash` at the top then 2 lines down put `sudo chmod 777 /dev/ttyS4` so now your second script looks like this: <img width="414" alt="Screen Shot 2020-12-09 at 12 14 59 PM" src="https://user-images.githubusercontent.com/34217684/101663018-2a67bd80-3a18-11eb-99fa-5029f1627ccb.png">
5. Now save the file and exit
6. Double check that your scripts are saved by running `ls` and seeing if you see the names of your script
7. We now need to make these scripts executable to do so run these 2 commands `sudo chmod +x SCRIPT1.sh` and `sudo chmod +x SCRIPT2.sh` (replace the SCRIPT1 SCRIPT2 with the names of your scripts) 
8. Now that we have finished creating the scripts we need to run them on boot to do so we need to get to the rc.local file in /etc/ to get there go to the root of your pi by running: `cd /` then go to /etc/ by entering `cd etc` you should now be in the etc folder and if you enter `ls` you should see many different things listed but we only need the rc.local so to edit that run `sudo nano rc.local` (if you have another editor such as vim you can use that instead) 
9. Once you're in the file right above the exit 0 place this`/home/pi/SCRIPT1.sh && sleep 4 && /home/pi/SCRIPT2.sh` (replace the SCRIPT1 SCRIPT2 with the names of your scripts) 
10. save and exit
11. Reboot and test if it works :)
