### ISSUE TITLE
Battery monitoring as an option

### ISSUE THREAD

**Issue by Snoomy** [kuestess/homebridge-platform-insteonlocal#123]
Hi. I’m using Insteon motion sensors powered by 9v batteries. Recently I’ve switched to rechargeable ones. They don’t last much - I have to recharge them every 3 months, but I believe this approach is far more green, than throwing alkaline batteries away every year.

So, the problem is even when it is fully charged homebridge still says “low battery”... as a result it is always shown in my home status. And that’s rather disturbing...

My idea is to implement a parameter, that would stop low battery status monitoring for particular devices, but will keep heartbeat monitoring to find out when a sensor stops operating at all.

What do you think?

**Comment by kuestess** [comment]
@Snoomy Completely agree with the green approach!  You're right though, they don't last long.  Would be fairly straightforward to add a config option to disable battery status reporting.  The plugin does maintain a last status update value, so may take a little work but certainly feasible to fire off a low battery if no status update occurs within a certain duration.  May take me a bit to get to it, but will put on the list for updates.

**Comment by kuestess** [comment]
@Snoomy Sorry for the delay in posting - I incorporated this into the latest release.  You can disable battery monitoring at the device level in your config (see readme).  Ot will still show low battery if it doesn't get a heartbeat for 48 hours, indicating a likely dead battery.

**Comment by ucdscott** [comment]
> The plugin does maintain a last status update value

Where in the InsteonUI can I find the "last status update value?"

**Comment by kuestess** [comment]
@ucdscott Its not currently shown in the UI, but something I can add in an update.

**Comment by ucdscott** [comment]
@kuestess Showing the "last status update value" in the UI would be much appreciated. Thank you!
