### ISSUE TITLE
Long delays and increasing when I add devices

### ISSUE THREAD

**Issue by benhur2407** [kuestess/homebridge-platform-insteonlocal#127]
I've had Insteon devices and hubs for years but i'm new to Homebridge. I installed Homebridge for Docker on my Synology NAS and then I installed your plugin to connect to my Insteon hub (model # 2242). Everything seemed to work as expected at that point, i.e. no errors (see homebridge-1.log).

When I add an Insteon device (dimmer) and I try to control it from within Homebridge, there is a delay between the request and the effect of that request on the device. I ran Homebridge in debug mode to better understand what was happening (see homebridge-2.log). From the log, it seems that the Insteon hub is communicating with Homebridge every 5-6 seconds, explaining the delay. I even get an "Error getting power state of <device>" which increases the delay.

When I add a second Insteon device (another dimmer) and I try again to control it from within Homebridge, the delay increases (see homebridge-3.log). I still get communication errors and the Insteon hub broadcasts status of the first device and after 5-6 seconds the status of the second device.

I tried adding a third Insteon device (still a dimmer) and the same pattern continues (see homebridge-4.log). 

I don't understand why there is a 5-6 second delay between Insteon hub -Homebridge communications,. I don't understand either why the Insteon hub needs to broadcast status of every device when the request was for one specific device. Obviously, the system would be totally unusable if I added my 40+ Insteon devices.

All theses devices work flawlessly with the Insteon app on my iOS devices, without delays. My plan was to use Homebridge to control my Insteon devices from the Home app on my iOS devices as this would allow me to control the Insteon devices with my Apple Watch (Insteon app is not available on Apple Watch).

I attach my config.json file (in text format) and printscreens of the Homebridge UI so you can see I am using the latest versions.

I hope my situation is clear enough for you to diagnose the problem.

Thanks in advance.

[homebridge-1.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705004/homebridge-1.log)
[homebridge-2.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705006/homebridge-2.log)
[homebridge-3.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705007/homebridge-3.log)
[homebridge-4.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705008/homebridge-4.log)
[config.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705010/config.txt)
<img width="1593" alt="Homebridge plugins" src="https://user-images.githubusercontent.com/49077966/102395779-982c6000-3fa9-11eb-9901-03606f968c7a.png">
<img width="1596" alt="Homebridge" src="https://user-images.githubusercontent.com/49077966/102395781-98c4f680-3fa9-11eb-9a0c-4f402b74412b.png">

**Comment by kuestess** [comment]
@benhur2407 The 2242 hub has a couple of quirks that I had to work around in the code - the biggest was managing connections to the hub.  It doesn't seem to tolerate a persistent connection (like the 2245), so the code checks the hub every 20 sec to see if any operations are in progress - if not, it disconnects from the hub and the reconnects when necessary (this shows in your log).  One thing that I overlooked in the code are status events that are triggered on a connection event - those are only supposed to fire on the initial connection, not each reconnect.  All of those status events make the 2242 relatively unresponsive.  I've fixed this in 0.4.16 which is now published.  Give it a try and see if that takes care of the problem.

**Comment by benhur2407** [comment]
Thanks for the quick response. Unfortunately, as you can see from the attached log, nothing has changed after the update to 0.4.16.

I tried to turn off one device (Office). I first got an "Error getting power state of Office" after 1 second (no result on the lights), then 5 seconds later I got a status for the second device (Family Room), then another 5 seconds later I got a status for the third device (Living Room), then another 5 seconds later another status for Family Room, then 6 seconds later another status for Living Room and finally 5 seconds later the Office lights were turned off. I think the problem would may be go away if we could get rid of the error which is happening only one second after the request. I don't understand why we are not successful in getting the power state of the device on the first try. I find strange that the power state is obtained (Office is on at 75%), then the command (Setting level of Office to 0%) is sent and then there is an error in getting the power state yet again. Could there be a conflict happening in the sequence of events? 

[homebridge-5.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5705686/homebridge-5.log)

**Comment by kuestess** [comment]
@benhur2407 Well crud, thought that might get it....  can you run `DEBUG=* homebridge -D` and post the output?

**Comment by benhur2407** [comment]
The log I attached to my previous post was already in debug mode. Do you prefer that I copy/paste it directly in the comment?

**Comment by kuestess** [comment]
@benhur2407 The `DEBUG=*` in front will also include the messages from the `home-controller` module, which has the raw hub response in it.

**Comment by kuestess** [comment]
@benhur2407 I'll take it!  Glad you got it working!
