### ISSUE TITLE
Five second delay between actions from scene

### ISSUE THREAD

**Issue by benhur2407** [kuestess/homebridge-platform-insteonlocal#128]
I'm having another issue similar to issue #127. When I run a scene from my iOS device, there is a five second delay between each action. I attach the log. 

Thanks.

[homebridge.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/5721382/homebridge.txt)

**Comment by rasod** [comment]
This, unfortunately, is a byproduct of how the Insteon Hub works with the Insteon communication protocol. The Hub can only send out one command at a time. So when you change the state of many devices they all get queued up and executed serially - the 5 second delay comes from the underlying home-controller code as it waits for the command to be acknowledged by the device. 

I have changed the delay in the code in the past - but I think (it was a couple of year ago) it ended up making things worse by having commands get “lost”. Have to try again.

Native Insteon scenes (like an All Off button) work differently. The scene “broadcasts” the state to all devices, then devices “subscribed” to that scene perform the state change. You kinda get use to it.

**Comment by benhur2407** [comment]
Thank you for the quick response.

When I create a scene using the Insteon app, all devices involved respond simultaneously, whether there is 2 devices or 2 dozen devices doesn't matter. If there is only 2 devices involved, the 5 second delay is no big deal. But when there is 2 dozen devices involved, it means it will take 2 minutes for the scene to complete; that's a long time. If nothing can be done in HomeKit to improve that, I will keep my Insteon app to run these scenes. The only issue I will have then is that the status of the devices involved in these scenes will be wrong in Homebridge because  the status will be changed by another app.

**Comment by rasod** [comment]
Yes, because when you create a scene in the Insteon app, it goes though the steps of adding each device to the group. That is why they beep one by one. Basically the app is telling each device in the scene “you are apart of this group when I say group “ABC” turn off you turn off”. Where as with Homekit it has to say “A turn off... ok?” “B turn off... ok?” “C turn off... ok?

You can use the InsteonUI to create a scene and that will be exposed as a “switch” in homekit. Take a look at the README for scenes.

Yes the state will get out of sync if you have multiple apps changing the state. You can us the polling feature to get the state every so many minutes depending on the number of devices you have.

**Comment by benhur2407** [comment]
Can you please explain how to use the InsteonUI? My Homebridge is installed on my Synology NAS using Docker. I'm using the Homebridge UI to control my system (not the command line because I don't know how to do that with the Synology NAS).

**Comment by rasod** [comment]
Should be what ever the IP of your homebridge is with port 3000. So something like 192.168.1.20:3000

**Comment by benhur2407** [comment]
Thanks.

**Comment by shereefalkady** [comment]
long time... great advancements gentlemen...
however..... this scene is an issue .... benhur waits 5 seconds.... i wait over a minute ....
with a setup of about 150 devices..... verifying all statuses takes too long .... i dont need it to or want it to ....
is there a way to 
1.ideally when given a new command it prioritizes it then goes back to polling
OR
2.when given a new command just dropping poll and taking new command....

its a must... cant use it with the scenes like this
