### ISSUE TITLE
TypeError when I add groupMembers to a scene

### ISSUE THREAD

**Issue by aketterson** [kuestess/homebridge-platform-insteonlocal#130]
I may be doing something wrong but I get :
   TypeError: device.groupMembers.split is not a function
   at InsteonLocalAccessory.init (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:2428:44)...

My config for this scene is...

                    "name": "PM Scene",
                    "deviceID": "4F.60.7D",
                    "deviceType": "scene",
                    "sixBtn": false,
                    "groupID": "14",
                    "keypadbtn": "D",
                    "dimmable": "no",
                    "groupMembers": [
                        "2345C8",
                        "15261F",
                        "53C7E2",
                        "471EA7",
                        "43690C"
                    ]
                },

**Comment by kuestess** [comment]
@aketterson The plugin expects groupMember to be a string with device IDs rather than an array.  Try this and see if it works for you:
```
"groupMembers":  "2345C8, 15261F, 53C7E2, 471EA7, 43690C"
```

**Comment by aketterson** [comment]
Thank you.   Perhaps I should have been able to figure that out.  Sooty for the trouble.

Regards,

Andrew

**Comment by kuestess** [comment]
@aketterson No worries!  Glad you got it to work.
