### ISSUE TITLE
Insteon HubPro vs Hub 2245-222

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#131]
Hey @kuestess i just acquired an insteon hub model 2245-222 I began thinking if this model would be a better choice for your plugin as using the HubPro has been very inconsistent with statuses being incorrect to not turning on or off when toggling. So i was just wondering what your thoughts were and if it was a good idea to do so.

**Comment by kuestess** [comment]
@yonigold1 Yep, the 2245 is pretty solid.  Pretty responsive and can also connect with other services if you're a multi-platform smarthome.

**Comment by yonigold1** [comment]
Just switched over to it! works great! 
Just a quick question for you on an unrelated topic how does this plugin work? Like is it created using Insteon's API? or is it created in another way?
