### ISSUE TITLE
Fast on and off with less delay

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#132]
Hey @kuestess I have been doing a lot of research on Insteon's API and if there are any ways to speed up the responses when turning on and off the lights and please feel free to ignore this if you have already seen this or was aware of this already. I found some http commands that you can send and they work instantly i was really impressed by how fast they worked. I then got to thinking about how to get this into HomeKit and then i thought about this plugin and thought that maybe you could find a way to implement it into the plugin. 
So to start off i found these [here](https://www.smarthome.com.au/smarthome-blog/insteon-hub-http-commands/) and anyone can generate them if you input the correct things in the correct fields. It generates a link that can toggle devices with a few different commands (for example for dimmers there is ON and OFF and FAST ON and FAST OFF with the on level in %)  they work really fast and i was hoping that you could find a way to implement it if it makes sense to of course. I have registered as a developer for Insteon as perhaps in their more detailed API (that one gets access to after registering as a developer) there might be yet another way to speed up commands.

Let me know :)

**Comment by kuestess** [comment]
@yonigold1 In the end, the plugin uses those exact commands (and more) at the link above.  The `home-controller` package provides the Insteon functionality - it initiates connections to the hub/PLM, provides request queuing, and decodes responses from the hub and packages into a more useful format.  It does add a little overhead, but it should be negligible and not result in any delay in commands.  If you're experiencing delay, then there may be other issues that are causing it.  I have 40+ devices and responses are fairly instantaneous (essentially instant).  

Good luck getting a response form the developer program.  Unfortunately, they seem to no longer respond to those requests.  Most of the developer documentation is available via a google search or at other sites/forums online.  I am fortunate enough to have a developer token, and actually have a version of the plugin that uses it.  I wish they were more open with them, as it makes things much easier....but here we are :-).

**Comment by yonigold1** [comment]
Ah got it had no clue that it uses those commands. The problem I experience is when toggling on there is a bit of a delay and i'm not sure why it occurred when i used the HubPro and now when i use the Hub V2. I have no clue how to figure out what's causing it. 

Insteon is the biggest pain in the ass period. Does the version of your plugin with their API work better? If so are u able to publish it? I'm so desperate for a perfect working Insteon setup I will do anything. Ive literally never been so dedicated and invested to perfecting something so much in my life. 😂

**Comment by kuestess** [comment]
@yonigold1 My initial guess for your slow response is a lot of Insteon traffic on your network since the issue persisted across the 2245 and HubPro.  You can monitor this traffic with the script below - save it as `eventListener.js` and run `node eventListener.js`.  Do this when you expect little/no Insteon traffic - if you see a lot of messages flying by then that's your cause.  Sometimes devices get 'chatty' and need to be reset, or if you have a lot of services (Alexa, Harmony, etc) linked up, then they will create extra traffic.  Feel free to shoot me a PM on Reddit if you'd like (username is the same).

```
var Insteon = require('home-controller').Insteon
var hub = new Insteon()

var config = {
	host: 'xxx.xxx.xxx.xxx',
	port: 25105,
	user: '*******',
	password: '*******'
  }

  hub.httpClient(config, function () {
	console.log('Connected to Insteon Hub.  Server listening....')
	
	hub.on('command', function (data) {
		var info_text = JSON.stringify(data)
		var deviceID = data.standard.id
		var messageType = data.standard.messageType
	  
		console.log('Full data: ' + info_text);
		console.log('Device ID: ' + data.standard.id)
		console.log('messageType: ' + messageType)
		console.log('Command1: ' + data.standard.command1)
		console.log('Command2: ' + data.standard.command2)
	}
  )
})
```
