### ISSUE TITLE
Request:  invert_sensor option for contact sensor

### ISSUE THREAD

**Issue by haywirecoder** [kuestess/homebridge-platform-insteonlocal#134]
Great module and very helpful for my Insteon setup. One request -- can the contact sensor (e.g. door sensor, window sensor..etc) also get the invert_sensor option just like iolinc? One of my sensor is normally open, when an event occur it close the contact. All my automation logic right now are reserve at this moment, hoping the invert_sensor option can be added to this module.

**Comment by kuestess** [comment]
@haywirecoder Should be easy enough to add - will put this on the list for the next update.

**Comment by kuestess** [comment]
@haywirecoder Just implemented this in 0.4.18, up on npm now.

**Comment by haywirecoder** [comment]
Thank you! It works great
