### ISSUE TITLE
Can the plug-in be used with a PLM only (eg no Insteon Hub)?

### ISSUE THREAD

**Issue by 1004PTLN** [kuestess/homebridge-platform-insteonlocal#135]
@kuestess I ended up installing homebridge on a MacBook vs the hub pro. While it was pretty cool getting the  beaglebone working, I'm concerned that I might be introducing other potentially negative factors down the road including the limited spec of the beaglebone and potential for issues if the on-board PLM goes bad.   In any event, my current setup is using a 2413U connected to the MacBook with Indigo domotics controller software.  I have never set up an Insteon account.  Is having an Insteon account a requisite for your plug in or is there a way to run things with just the PLM?  I will be frank that while setting up links in the Indigo software is quite simple, technically where things are actually located between the PLM, the devices and the Indigo databases are a little like black magic to me.  I certainly don't want to do anything that could be catastrophic to the current set up of link tables.  Look forward to your response.

**Comment by yonigold1** [comment]
hey sorry this is off topic but i saw that u use Indigo software may i ask what you thought about it? i've been considering using it.

**Comment by kuestess** [comment]
@1004PTLN No requirement to have an Insteon account, and you can set up the plugin to run directly with a PLM (this is essentially what you're doing on the Hub Pro).  To connect to the PLM, just specify PLM as your model and set host in your config to the device path you want to use (sorry, I really need to update the readme!).  By design, Insteon links are stored in a database on the PLM and devices, so if you switch PLMs then you will lose the links set up in that PLM (the corresponding link is still in the device).

Understand your concern about a PLM failure - your risk is essentially the same whether you go with the Hub Pro or direct to a PLM.  The Hub Pro is the beaglebone connected to a PLM in the same box, pretty much the same as the Macbook/PLM setup.  The beaglebone is underpowered, but it really doesn't need to do much - the nice thing about it is the serial connection directly to the PLM which tends to be faster than the network connection to a separate Hub.  Either way should work just fine!

**Comment by 1004PTLN** [comment]
Thanks @kuestess , a few additional questions.  Hopefully this will get me off the fence!

[To connect to the PLM, just specify PLM as your model and set host in your config to the device path you want to use]

OK, since I don't have an insteon app what would I do with the references in the Configuration section related to info coming from the insteon app such as user, password, port?


[By design, Insteon links are stored in a database on the PLM and devices, so if you switch PLMs then you will lose the links set up in that PLM (the corresponding link is still in the device).]

This is why I was more leaning toward keeping the current PLM that I'm using with Indigo.  I have about 80 devices in my set up now many are linked switches and KPLs so I really don't want to have to rebuild all that.  If I keep the current PLM, it sounds like your plug-in will read them but the down side will be speed?   If I move to the PLM that's in the hub pro, how would you recommend going about rebuilding the links to the corresponding links in the devices?  Is that accomplished automatically through your plug-in?

[Understand your concern about a PLM failure - your risk is essentially the same whether you go with the Hub Pro or direct to a PLM. The Hub Pro is the beaglebone connected to a PLM in the same box, pretty much the same as the MacBook/PLM setup. ]

Yes, but the PLM in the hub pro is soldered in.  Although it looks like the cape could be reused.  If that PLM went bad it would be an awful lot of work to replace it vs the current separately enclosed PLM that is a one for one swap.

[The beaglebone is underpowered, but it really doesn't need to do much]  

Fair point.  I have installed Ring and Nest plug-ins on the beaglebone and it has been pretty snappy with them.  Any concerns that you'd have with 80-100 devices?

**Comment by 1004PTLN** [comment]
> hey sorry this is off topic but i saw that u use Indigo software may i ask what you thought about it? i've been considering using it.

@yonigold1, no problem. Indigo is a very powerful application.  Allows you to take automation to pretty sophisticated levels.  Having said that, I really don't use the power of the system to its full extent so it's a bit of overkill for me, I really migrated to it because they had a Homekit plugin that was pretty bullet proof.  Unfortunately the developer of that plug-in has moved on, so I've looking for a fall back options and have been investigating homebridge and this plug-in of course.  In addition, the developers of the Indigo application have instituted a subscription model on top of the original out of pocket costs.  So for me, while everything is working just fine now, it seemed like a good time to investigate alternatives.  Hope that helps.

**Comment by kuestess** [comment]
@1004PTLN You can leave out the user, pass, and port in your config - not used for a PLM connection.  Insteon must have changed the design of the HubPro over time - mine has the PLM on a separate board, so theoretically it could be re-used if the beaglebone took a crap.  If yours is soldered on, would certainly go with the MacBook/PLM combo - saves you this time of re-creating links.  The plugin doesn't currently migrate PLMs/Hubs, but that's something I want to do long-term.  I have the groundwork set for that in the web UI, but haven't had the time to implement not to mention the headache when I screw up my Hub :-).  Your Mac/PLM combo should be equally as fast as the hubPro, so I wouldn't have reservations about going that route.  I looked into Indigo a while back, but the cost pushed me away.  Subscription model seals the deal for me.

**Comment by 1004PTLN** [comment]
Thanks so much!  I'll be able to play around with this more over the next few weeks.  Will open a new one up if other questions come up.

**Comment by yonigold1** [comment]
> > hey sorry this is off topic but i saw that u use Indigo software may i ask what you thought about it? i've been considering using it.
> 
> 
> 
> @yonigold1, no problem. Indigo is a very powerful application.  Allows you to take automation to pretty sophisticated levels.  Having said that, I really don't use the power of the system to its full extent so it's a bit of overkill for me, I really migrated to it because they had a Homekit plugin that was pretty bullet proof.  Unfortunately the developer of that plug-in has moved on, so I've looking for a fall back options and have been investigating homebridge and this plug-in of course.  In addition, the developers of the Indigo application have instituted a subscription model on top of the original out of pocket costs.  So for me, while everything is working just fine now, it seemed like a good time to investigate alternatives.  Hope that helps.

Hey thanks so much for replying did u have the full version of indigo at the time before they introduced a subscription? and if you paid for the original can u still use it without the need to pay the subscription?

**Comment by 1004PTLN** [comment]
@yonigold1 yes I have had the full version for a few years. You can still use the version you are on once you stop participating in the subscription but of course you'd lose the ability to update the system with any new updates the developers create.
