### ISSUE TITLE
Error loading plugin homebridge-platform-insteonlocal - modules missing 

### ISSUE THREAD

**Issue by matttttttttttttt** [kuestess/homebridge-platform-insteonlocal#138]
Hello kuestess,

Thank you so much for creating and maintaining this Swifty and very useful home bridge plugin.

When updating the insteonlocal plugin or setting up a new home bridge installation, I've run into the problem of not being able to load up the plugin. This happened to me a couple of times in the last few months and I am not quite sure what is the cause for it. What usually worked is to wipe and delete everything Node/NPM related on the raspberry pi and then install it and restore it a couple of times. One time I manually installed all the missing modules by hand. Maybe this is a linking problem.

I tried to install it via npm -g install homebridge-platform-insteonlocal.

Have you seen this kind of behavior? 

configuration: raspbian OS with HomeBridge v1.3.4, Node v15.12.0 and NPM 7.7.6

<img width="961" alt="Screenshot 2021-03-29 at 13 36 27" src="https://user-images.githubusercontent.com/72557120/112896883-ce42ab00-9093-11eb-8f48-930d210fa5ca.png">

**Comment by matttttttttttttt** [comment]
After removing everything and downgrading Node to v14.16.0, I was able to make it work again. This helped me fixing this issue for me.

**Comment by kuestess** [comment]
@matttttttttttttt Glad you were able to get it sorted out.  I've had this issue as well (on other projects) and it seems to be related to the latest version of `npm`.
