### ISSUE TITLE
All devices gone

### ISSUE THREAD

**Issue by sabresoftware2021** [kuestess/homebridge-platform-insteonlocal#141]
Had multiple insteon devices showing up in HomeKit, but noticed today that they have all disappeared. Checked version of the plug-in (0.4.18) and restarted HomeBridge server but still nothing. 

What gives?

**Comment by kuestess** [comment]
@sabresoftware2021 Sorry, gonna need more to go on than that.  Any messages in the console?  Have you verified your config?

**Comment by sabresoftware2021** [comment]
I went back through the logs and found the following:

[13/05/2021, 16:55:55] ====================
[13/05/2021, 16:55:55] ERROR LOADING PLUGIN homebridge-platform-insteonlocal:
[13/05/2021, 16:55:55] Error: Cannot find module 'q'
Require stack:
- /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js
- /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/index.js
- /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/index.js
- /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:7:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[13/05/2021, 16:55:55] ====================

[13/05/2021, 16:55:57] Loading 4 platforms...
[13/05/2021, 16:55:57] [Config] Initializing config platform...
[13/05/2021, 16:55:57] [Config] Running in Service Mode
[13/05/2021, 16:55:57] No plugin was found for the platform "InsteonLocal" in your config.json. Please make sure the corresponding plugin is installed correctly.

At some point during the last week I accepted plug-in updates for several plug-ins and probably went from version 0.4.17 to 0.4.18 of the Insteon plug-in at that time. I only noticed the missing items today when I tried to turn something on and then noticed that all the Insteon devices were missing. I reverted to version 0.4.17 and all my devices showed up again (although I did have to clean up a few things in HomeKit such as HomeKit room assignments and participation in automations). All is working right now, so I'm reluctant to to try 0.4.18 again right now.

My config.json is as follows:
{
    "bridge": {
        "name": "Homebridge 0FB3",
        "username": "0E:AF:2A:A8:0F:B3",
        "port": 51985,
        "pin": "861-91-312"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "InsteonLocal",
            "name": "insteonlocal",
            "host": "192.168.4.20",
            "port": "25105",
            "model": "2245",
            "user": "ihub",
            "pass": "********",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Anns Ceiling Light",
                    "deviceID": "562D51",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Basement Lights",
                    "deviceID": "2F.97.43",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Pool Table",
                    "deviceID": "2F.94.8F",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Garage Lights",
                    "deviceID": "29.DB.B7",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Front Lights",
                    "deviceID": "3D.36.A8",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Side Light",
                    "deviceID": "29.D1.A6",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Multi Room Table Lamp",
                    "deviceID": "47.3F.B2",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                },
                {
                    "name": "Leak Sensor",
                    "deviceID": "3F.A5.82",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                }
            ]
        },
    ],
    "disabledPlugins": []
}

**Comment by kuestess** [comment]
@sabresoftware2021 I've had this issue as well - seems to be a bug in the latest npm.  To fix it, you'll need to manually install the missing dependencies.  From the terminal, type `npm -g install q`.  This will install the missing module (`q` in this case).  You may have to do this with a handful of missing modules, but once they're all installed it should work fine.
