### ISSUE TITLE
Plug-In Relay Support

### ISSUE THREAD

**Issue by aw-0** [kuestess/homebridge-platform-insteonlocal#144]
Hope you've been well! Is there support for Insteon's "Plug-In Relays"? Can't find it in the config section of the readme, and thought I'd double-check by creating an issue.

**Comment by kuestess** [comment]
@aw-0 I'll be honest that I didn't even know those existed - appear similar to the appliance modules available in the US.  It *should* work if you set it up as a switch.  Give that a try and let me know if it doesn't work and I can look into it further.

**Comment by aw-0** [comment]
Will give that a try -- thanks!

I'm pretty sure it's just a switch, but the app said Plug-In Relay so I thought I'd double check :)

**Comment by aw-0** [comment]
That worked, thanks for the response! Not sure why I didn't try switch anyways - I must've thought it referred to a wall switch.
