### ISSUE TITLE
[Question] FanLinc + KeyPad + Scenes examples?

### ISSUE THREAD

**Issue by drbenschmidt** [kuestess/homebridge-platform-insteonlocal#150]
Hello!

I was reading through the documentation and was wondering if there are any examples of configuring the plugin to handle a 6 button KeyPad that is linked to a FanLinc through the hub already. I'm hoping to have any commands coming through Home also update the status of the KeyPad, but wasn't sure what all is necessary to do that.

If there isn't a good place for examples, maybe this would be a good chance to start compiling them into an `examples.md` file or folder?

Thanks!

**Comment by kuestess** [comment]
@drbenschmidt I like the idea of an `examples.md` file.  There is an example `config.json`, but admittedly the examples are sparse and I haven't updated it in a while :-(.  One straightforward way to accomplish what you're asking is to create a scene device for each fan state - that would give you an on/off switch for each fan mode and the controlling keypad state should follow.  What this won't give you is the slider that you get with a typical Home fan control.  If you want the fan slider control, then you can set up as a `fan` device....however that won't update the button status.  Let me know what you're trying to get to and I can give an example config for that.  There is also the 'target keypad' feature that is intended to show status of a device, but it currently only works with lights and isn't intended for fans.
