### ISSUE TITLE
Cannot connect to config page

### ISSUE THREAD

**Issue by Calorion** [kuestess/homebridge-platform-insteonlocal#154]
I've installed the latest version (0.4.20) of the plug-in on a HOOBS box in its own bridge. However, HOOBS reports that the bridge is down, and connecting to `hoobs.local:3000` times out. 

The log says `8/23/2021, 10:39:40 PMPlatform Insteonlocal BridgeInsteonLocalERRORNo devices defined - please add devices to your config.json`
`8/23/2021, 10:39:40 PMPlatform Insteonlocal BridgeWARNINGunhandled rejection: TypeError: "path" is not defined: undefined`

On installation, these errors appeared:![image](https://user-images.githubusercontent.com/3050950/130552726-d713e72f-62a1-40f8-94c0-975bc7cfcb5f.png)

How do I resolve this issue and connect to the config page?

**Comment by kuestess** [comment]
@Calorion You can safely ignore the warnings above - those are older dependencies of `home-controller` that won't impact the plugin operation.  Unfortunately the log that you pasted above doesn't give me enough information to go on.  Can you manually run homebridge in debug mode (`homebridge -D`) and paste the output here.

**Comment by Calorion** [comment]
Is this what you want? Running `homebridge -D ` in the HOOBS Terminal doesn't work, but here is the debug log. 

[log.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/7043681/log.txt)

**Comment by kuestess** [comment]
@Calorion Thanks for the extra logs.  Looking through them, this appears to be an issue with Hoobs as I don't use the `path` module for the plugin.  You might search through issues on their repo to see if others have had that problem.  Alternately, you could try to set up a standalone install of homebridge and see if that works.

**Comment by kuestess** [comment]
@Calorion To clarify, you can configure the plugin without using the ui by manually adding devices to your config.json, so the UI is not an absolute requirement.

**Comment by kuestess** [comment]
@Calorion Saw a similar error on another issue - can you post your config.json.

**Comment by kuestess** [comment]
@Calorion Based upon your other issue, it appears that you're running the plugin on a Hub Pro and HOOBS on another host.  In order to connect to the Insteon UI page, you have to use the IP address of the Hub Pro.  Connecting to a remote instance of the plugin running on a Hub Pro isn't supported (without additional software).
