### ISSUE TITLE
Settings page won't open

### ISSUE THREAD

**Issue by funkyvisions** [kuestess/homebridge-platform-insteonlocal#155]
When I try to open the settings page the logs say:
[Homebridge UI] [homebridge-platform-insteonlocal] Custom UI: Plugin does not provide a custom UI
I am running the latest homebridge and insteonlocal versions
Ideas on how to correct this?

**Comment by kuestess** [comment]
@funkyvisions Seeing this on my end too - looking into it.

**Comment by Calorion** [comment]
I'm not sure if this is the same issue, but when I install on Homebridge UI on both my Hub Pro and my Mac, this is the config screen I get, with the gear spinning, forever. ![image](https://user-images.githubusercontent.com/3050950/132621714-441d3a91-a8d6-4612-9646-755bf828ed7e.jpeg)

**Comment by kuestess** [comment]
@funkyvisions @Calorion Just pushed an update that should take care of this.
