### ISSUE TITLE
Not getting Status of outlets

### ISSUE THREAD

**Issue by tsawyer** [kuestess/homebridge-platform-insteonlocal#157]
Upon rebooting Homebridge the status on my two outlets is ON though they are OFF. I set a refresh value of 30 and the log shows a refresh every 30 seconds. However, the Homebridge Ui nor Homekit status changes to OFF. Pressing either the Homebridge button or the Homekit button will turn the outlet ON or OFF and update the status (in both Homekit and Homebridge)  correctly.

There are the first two and only devices in Homebridge thus far.

**Comment by kuestess** [comment]
@tsawyer Can you post the config for your outlet?

**Comment by tsawyer** [comment]
> @tsawyer Can you post the config for your outlet?

Sure, I added a wall switch since my last post. It's working as expected.

```
    "devices": [
        {
            "name": "Test Outlet",
            "deviceID": "54FD5C",
            "dimmable": "no",
            "deviceType": "outlet"
        },
        {
            "name": "Test Coffee Pot",
            "deviceID": "374A09",
            "dimmable": "no",
            "deviceType": "outlet"
        },
        {
            "name": "Test Wall Switch",
            "deviceID": "381920",
            "dimmable": "yes",
            "deviceType": "dimmer"
        }
    ]
"devices": [
        {
            "name": "Test Outlet",
            "deviceID": "54FD5C",
            "dimmable": "no",
            "deviceType": "outlet"
        },
        {
            "name": "Test Coffee Pot",
            "deviceID": "374A09",
            "dimmable": "no",
            "deviceType": "outlet"
        },
        {
            "name": "Test Wall Switch",
            "deviceID": "381920",
            "dimmable": "yes",
            "deviceType": "dimmer"
        }
    ]
```

**Comment by kuestess** [comment]
@tsawyer You also need to add the `position:` key to your config, specifying either top or bottom (see readme).

**Comment by tsawyer** [comment]
@kuestess The readme says the default position it top. So I added `position: bottom` and it's working now. Thanks!

**Comment by tsawyer** [comment]
@kuestess After a bit more usage it appears `position:` is not the answer. It's only changing the displayed status on boot up. I don't think the status is actually read at boot up. Can you confirm this?

**Comment by kuestess** [comment]
@tsawyer The plugin does check status once on start.  It may take a few minutes depending upon how many devices you have and the amount of traffic on the Insteon network.  In your config, you'll need to put top/bottom in quotes if you haven't already (just going from above post).

**Comment by tsawyer** [comment]
It is quoted. Theses outlets do not have separately switchable top and bottom outlets. Could that be the problem?

**Comment by tsawyer** [comment]
@kuestess I made them switches. It worked.
