### ISSUE TITLE
Port 3000 goes to unexpected destination on Hub Pro

### ISSUE THREAD

**Issue by Calorion** [kuestess/homebridge-platform-insteonlocal#158]
So the last update works, and I finally got Insteonlocal fully installed on my Hub Pro. But when I go to `<Hub Pro IP>:3000`, it goes to something else entirely: A Beagleboard page telling me I need to upgrade. Should I just pick a different port, or what? And should I indeed update the Beagleboard software?

**Comment by kuestess** [comment]
@Calorion This is typical on a Beagleboard as there is default installed software running on port 3000.  Just specify another port in your config.

**Comment by Calorion** [comment]
Could this be added to the documentation?
