### ISSUE TITLE
Homebridge crashes after configuring Insteonlocal

### ISSUE THREAD

**Issue by Calorion** [kuestess/homebridge-platform-insteonlocal#159]
After updating to 0.4.21, the configuration page appeared. I set the model and port number, saved and restarted Homebridge. Now Homebridge is crashing. See the attached log. This is happening on both my Hub Pro and my Mac.

https://www.dropbox.com/s/it6k6rd7b2b3gu4/homebridge.log.txt?dl=0

**Comment by kuestess** [comment]
@Calorion This appears to be the log from your HubPro.  The repeated crash is because your user doesn’t have permissions for the HubPro serial port `/dev/ttyS4`.  You need to fix those permissions and it should work.

**Comment by Calorion** [comment]
How would I do that?

**Comment by kuestess** [comment]
See here: [https://askubuntu.com/questions/58119/changing-permissions-on-serial-port](https://askubuntu.com/questions/58119/changing-permissions-on-serial-port)

**Comment by Calorion** [comment]
That fixed one error, but it doesn't seem to be why Homebridge is crashing. https://www.dropbox.com/s/ekixegk8tur0zg7/homebridge2.log.txt?dl=0

**Comment by kuestess** [comment]
@Calorion Looking at the log you posted, it still shows the permissions error for `/dev/ttyS4`.  Please also post your config.json.

**Comment by Calorion** [comment]
The most recent entries in the log seem to not show the permissions error. 

[Here's the config.json](https://www.dropbox.com/s/hib3pze0j51xrka/config.json?dl=0).

**Comment by kuestess** [comment]
@Calorion You have an extra line in your config.  Remove the last line with `"platform": "InsteonLocal"`

**Comment by Calorion** [comment]
Insteonlocal must have put it in then. I haven't touched the config.json and I have no other plugins installed.

**Comment by Calorion** [comment]
And trying to remove that line results in the error, "All platform blocks must contain the "platform" attribute" when I try to save.

**Comment by kuestess** [comment]
@Calorion You do have other plugins installed - the Config ui is a plugin and is writing your config.  Outside of the Insteonui, Insteonlocal doesn’t write to the config.  I  overlooked part of your config, and the platform line above is correct, however it looks like you’ve only partially configured a single device.  Delete everything inside of the `”devices”: [ ]` array and restart homebridge.

**Comment by Calorion** [comment]
> You do have other plugins installed - the Config ui is a plugin and is writing your config. 

Well, yes, but that was installed along with Homebridge; I didn’t install it separately. I assume that any Homebridge plugin is compatible with Config UI. So I think there’s likely some sort of bug or incompatibility in Insteonlocal.
