### ISSUE TITLE
Importing devices when installed on Hub Pro

### ISSUE THREAD

**Issue by Calorion** [kuestess/homebridge-platform-insteonlocal#161]
I was excited to see that it was possible to install Homebridge and Insteonlocal on a Hub Pro. I presumed that that would make it easier to connect to and manage my Insteon devices. 

Well, I've finally got Insteonlocal up and running on my Hub Pro, but when I log into Insteonlocal and select "Get Devices/Links," nothing appears. 

How do I import my devices when running Insteonlocal on my Hub Pro?

**Comment by kuestess** [comment]
@Calorion You have to get Hub info first on the ‘Hub’ tab - see readme.

**Comment by Calorion** [comment]
Yes, I did that first.  But I still get "No links in Insteon config - please click Get Links to get links and devices from Hub"

**Comment by kuestess** [comment]
@Calorion Can you post the output from the console when you click the 'Get Devices/Links' button?

**Comment by Calorion** [comment]
https://www.dropbox.com/s/wd8a44e0ub4ny5e/homebridge.log.txt?dl=0

My fear is that I unlinked it while rebooting the Hub Pro over and over trying to get Homebridge installed.

**Comment by kuestess** [comment]
@Calorion The end of the log looks normal.  Have you tried re-linking a device to the Hub using the 'Link' tab?

**Comment by Calorion** [comment]
How do you do this via the InsteonUI?

**Comment by kuestess** [comment]
@Calorion You can add each device on the config tab at the bottom.

**Comment by Calorion** [comment]
You can add devices to HomeKit that way?

**Comment by kuestess** [comment]
Yes, see the readme.

**Comment by Calorion** [comment]
I  don't have any device settings at the bottom of my Configuration tab in InsteonUI. Just the Hub Configuration at the top.
