### ISSUE TITLE
Upgraded to Hoobs 4 and now Insteon Hub Not Responding to Commands 

### ISSUE THREAD

**Issue by mikemarconi** [kuestess/homebridge-platform-insteonlocal#162]
After upgrading to HOOBS 4 I had to re-add my Insteon devices again.  Now Hoobs and HomeKit both see them.  However,  commands are not being executed by the Insteon HUB.  This is the error message I get in the logs:

0/2/2021, 3:03:31 AMPlatform Insteonlocal BridgeInsteon Local PlatformSetting level of Hallway Lights to 100%

10/2/2021, 3:03:34 AMPlatform Insteonlocal BridgeWarningunhandled rejection: Error: connect EHOSTUNREACH 192.168.4.35:25105

10/2/2021, 3:03:37 AMPlatform Insteonlocal BridgeWarningunhandled rejection: Error: connect EHOSTUNREACH 192.168.4.35:25105

Any Ideas?

Mike

**Comment by kuestess** [comment]
@mikemarconi Looks like homebridge can't reach your hub.  Double check to make sure that the IP address of the Hub is the same, if so you may need to unplug/replug your Hub.  They tend to stop accepting connections sometimes.

**Comment by mikemarconi** [comment]
@kuestess  Thanks.  It turns out the ip address for the hub had changed and I now have it working.  Thanks for all of the help.
