### ISSUE TITLE
targetKeypadBtn doesn't work for ON/Off buttons on a 6 button keypad

### ISSUE THREAD

**Issue by lancehudson** [kuestess/homebridge-platform-insteonlocal#164]
I am trying to link up my fanlinq light and the on/off button on my 6 button keypad. 

Current config:

```
  {
      "name": "Office Fan Light",
      "deviceID": "123456",
      "dimmable": "true",
      "deviceType": "lightbulb",
      "controllers": "987654",
      "targetKeypadID": "987654",
      "targetKeypadBtn": ["A"],
      "targetKeypadSixBtn": [true]
  }
```

But that lights up the Scene button.

I looked at the source code, looks like on the 6 button, only the 4 scene buttons are avaliable.

https://github.com/kuestess/homebridge-platform-insteonlocal/blob/6df6a5c41a75a90c62cd043ea134e9284b348cdc/index.js#L1771

I tried using it as an 8 button so I can hit the other id's but so far it hasn't worked and I ran out of time to poke it.

Do you know which numeric id is the on/off button?

Also, I suggest adding ON to the array.

Thanks for all the work on this!

**Comment by lancehudson** [comment]
No, As far as I know, ON is not A

[Example pic](https://cdn.shopify.com/s/files/1/0375/3816/8965/products/vai-pdp-msi2322-382-800x800-1a-2018-9-4_800x.jpg?v=1591109399)

**Comment by THX723** [comment]
Have you already done a manual Insteon link between the scene button and the other switch?

targetKeypad is for updating the button LED status, not the actual device state.
