### ISSUE TITLE
Newbie to Hoobs

### ISSUE THREAD

**Issue by dali341** [kuestess/homebridge-platform-insteonlocal#167]
Hi there, I am new to all this and i can't seem to figure out how to get past the initial config page. i have a 2245 hub and have entered the info on the back of the hub but it doesnt seem to accept the host ip.

**Comment by dali341** [comment]
Insteon Bridge starting
2021-11-13, 7:41:49 AMInsteon BridgeLoaded plugin 'homebridge-platform-insteonlocal'
2021-11-13, 7:41:49 AMInsteon BridgeLoading 1 platforms...
2021-11-13, 7:41:49 AMInsteon BridgeInsteonLocalStarted connection watcher...
2021-11-13, 7:41:49 AMInsteon BridgeInsteonLocalFound 1 devices in config
2021-11-13, 7:41:50 AMInsteon BridgeBridge is running on port 51846.
2021-11-13, 7:41:50 AMInsteon BridgeWARNINGunhandled rejection: Error: Error: No such file or directory, cannot open 192.168.0.186

**Comment by kuestess** [comment]
@dali341 Please post your config.json.

**Comment by dali341** [comment]
{
    "accessories": [],
    "platforms": [
        {
            "platform": "InsteonLocal",
            "name": "InsteonLocal",
            "pass": "tRtPBkiT",
            "port": "25105",
            "refresh": false,
            "server_port": "3000",
            "keepAlive": false,
            "user": "Whituryd",
            "devices": [
                {
                    "name": "Lower Hallway",
                    "deviceID": "51.98.07",
                    "dimmable": "false",
                    "deviceType": "switch"
                }
            ],
            "host": "192.168.0.186"

**Comment by kuestess** [comment]
Add `"model": "2245"` to your config and that should take care of it.

**Comment by dali341** [comment]
ugh forgive my ignorance but where do i place it? I did this and when o save it nothing happens and it disappears lol.

{
    "platform": "InsteonLocal",
    "name": "InsteonLocal",
    "pass": "tRtPBkiT",
    "port": "25105",
    "refresh": false,
    "server_port": "3000",
    "keepAlive": false,
    "user": "Whituryd",
    "devices": [
        {
            "name": "Lower Hallway",
            "deviceID": "51.98.07",
            "dimmable": "false",
            "deviceType": "switch"
        }
    ],
    "host": "192.168.0.186"
    "model": "2245"

**Comment by dali341** [comment]
ok i put a comma after and it stuck but i got a new error

"platform": "InsteonLocal",
    "name": "InsteonLocal",
    "pass": "tRtPBkiT",
    "model": "2245",
    "port": "25105",
    "refresh": false,
    "server_port": "3000",
    "keepAlive": false,
    "user": "Whituryd",
    "devices": [
        {
            "name": "Lower Hallway",
            "deviceID": "51.98.07",
            "dimmable": "false",
            "deviceType": "switch"
        }
    ],
    "host": "192.168.0.186"
}

unhandled rejection: Error: Status code expected 200, got 401

**Comment by kuestess** [comment]
@dali341 You're getting closer - 401 is an authorization error.  Fun thing that the hub does sometimes is reset the hub password so it doesn't match what's on the bottom.  Easiest way to fix is open the Insteon app, got to Settings->House and change the 'Hub Username' and 'Hub Password'.  I would change both, even if you make it the same as the app doesn't always show the correct user/pass.  Rewriting both will make sure that its correct.

**Comment by dali341** [comment]
Ok i got it up and running, looks like i have to enter every device manually as it did not populate devices. Also not sure how to work dimmable devices? It just does On/Off and my keypad is the same it does not show a 6 button keypad?

**Comment by dali341** [comment]
where do i do this?

If you have already discovered devices from the Hub, you should see a list of devices in the left-hand column. If not, click 'Get Devices' and the device list should populate after discovery is complete.

Once devices are discovered, click on a device in the list. In the right-hand pane, you can give the device a friendly name (be sure to click 'Save'). Devices that were in your config should already be named (you can change the name here without overwriting your config). Under the 'Action' menu, you can get links information and links from the device by clicking 'Get Dev Info/Links'. Depending upon the number of links in the device, this may take some time and is best to do when there is no other Insteon traffic. If you want to do this for all devices at once, click 'Get All Dev Links' in the top right. Again, this may take time.

**Comment by kuestess** [comment]
@dali341 Yes, you will have to manually add devices to your config in order for them to appear in HomeKit.  What you reference above doesn't add them to your config, but is used for device management.  For the keypad, there's no equivalent available in HomeKit, so you can only represent it as multiple switches.  If you want to do device management (as above), then open `<ip of homebridge host>:3000/` in the browser.
