### ISSUE TITLE
Support for door/window sensors - device info hangs

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#171]
So in the drop down to add devices the door/window sensors are not support. To clarify I am talking about the UI for the 127.0.0.1:3000 interface on the main page where you click add. I will try to add via the plugin configuration panel where I can see that option. 

Clicking get device info hangs the system so I cannot provide that output. The webpage will just show the "Updating device" window and the log shows the "Getting device info for..."

You can click the X to close the window, but you have to restart to make querying any other device work again.

Device Details in Insteon App show:

x10x11x45 for hidden door sensor
x10x02x43 for window open/close sensor

Door sensor in Insteon.json

```
{
                "flags": "A2",
                "controller": false,
                "isInUse": true,
                "hasBeenUsed": true,
                "isLast": false,
                "group": 1,
                "id": "329Fxx",
                "data": [
                    "00",
                    "00",
                    "00"
                ],
                "onLevel": 0,
                "rampRate": 2000,
                "number": 1
            },

 {
            "name": "",
            "deviceID": "329Fxx"
        },
```

The entry for the Window open/close does not show up in the file at all.

So I just let the get links run..and it seems to timeout at some point a move to the next thing.

Getting all device links
Getting device info for 5509xx
(node:504) TimeoutOverflowWarning: 2684354560 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:504) TimeoutOverflowWarning: 5368709120 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:504) TimeoutOverflowWarning: 10737418240 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
Error getting device info
Getting operating flags for 5509xx
Getting all device links
Getting device info for 5509xx

**Comment by kuestess** [comment]
@sahafeez Unfortunately, this is an Insteon limitation.  Door and window sensors are battery operated devices, so they don't listen for Insteon commands unless they are awake (to preserve battery).  You can manually wake each device (with the set button) and then get device info.  It should work if you time it right.  I can add door/window sensors to the ui on the next update, but honestly the Homebridge ui works better.

**Comment by sahafeez** [comment]
Thanks for the information. I am taking some time to read and understand the code in this project. Thanks for putting this together. I hope to have a minor pull request to you soon just cleaning up some typos I found.
