### ISSUE TITLE
Difference between configured items in plugin and "Get Devices"

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#173]
I have 68 configured devices in the plugin configuration. This matches my Insteon app. The get devices only returns 59 devices. Some are battery powered, however there are a number that are plugs / lights. I am trying to understand the difference between the 2.

**Comment by kuestess** [comment]
@sahafeez Unfortunately, there’s no direct way to ask the hub for all the devices it knows about.  The devices shown in the ui are generated by asking the hub for all of its links and filtering that list for unique device id’s.  I’ve never cross compared this to a list of my devices, but a quick look seems like everything is there.

**Comment by sahafeez** [comment]
So after I dusted off my sed/awk skills I produced a diff between the config.json and the insteon.json files.

The get devices is missing the following:

2 lights switches
3 door sensors
2 motions sensors
2 leak sensors

I would say okay, battery devices, except for the fact that there are sensor that are the same type that do show in the get devices and there are 2 missing light switches. The 2 light items are showing up in HomeKit with the correct status. 

Strange.

**Comment by kuestess** [comment]
@sahafeez If you're up for some nerdy troubleshooting, save the below as a .js file and then run `node <filename>.js`. Should spit out all of the links that your Hub knows about.  Look through there and see if your missing devices are listed.  If so, may have a problem with the code to look into.

```
var Insteon = require('home-controller').Insteon;
var util = require('util')
var hub = new Insteon();

var config = {
  host: '<hub IP>',
  port: 25105,
  user: '<hub username>',
  password: '<hub password>'
};

hub.httpClient(config, function () {
  console.log('Connected to Hub')
  hub.links(function(err,links){
	console.log('Links: ' + util.inspect(links,false,null))
	
	})
})
```

**Comment by sahafeez** [comment]
@kuestess Thanks for looking at this. I am always up to troubleshoot.

So I dropped the script into /usr/lib/node_modules/homebridge-platfrom-insteonlocal and ran it.

It returns as list of items, but sat the end it seems to cut off:

```
  {
    flags: 'E2',
    controller: true,
    isInUse: true,
    hasBeenUsed: true,
    isLast: false,
    group: 0,
    id: '411FFA',
    data: [ '01', '20', '45' ],
    onLevel: 1,
    rampRate: 480000
  },
  ... 40 more items

```

..and just sits there. 

1. is it suppose to print the 40 more items?
2. is it suppose to exit?

**Comment by kuestess** [comment]
@sahafeez Well crap, that's not helpful.  Try this script instead.

```
var Insteon = require('home-controller').Insteon;
var util = require('util')
var hub = new Insteon();

var config = {
  host: '10.0.0.12',
  port: 25105,
  user: 'kuestess',
  password: 'ccs12345'
};

hub.httpClient(config, function () {
  console.log('Connected to Hub')
  hub.links(function(err,links){
	console.log('Links: ' + JSON.stringify(links))
  })
})
```

**Comment by sahafeez** [comment]
Okay, so the script pulls 69 unique ids. The number I have configured in the config.json is 77 as is the number reported to me in the Insteon application. I will ID the differences and list what devices they are.

**Comment by sahafeez** [comment]
The missing devices are:

3 hidden door sensors
1 open close sensor
1 range extender
1 leak sensor
1 motion sensor (old big one)
1 light switch dimmer 

So for the sensor - there are other motion, hidden door and leak sensors that DO show up.

The strange one is the 1 light switch dimmer. It is configured as a device in the plugin settings, and I have verified the ID in the Insteon app and I am able to control the device from the Insteon app. This devices has associated motion sensor, which does show up in the list.
