### ISSUE TITLE
Outlet - Top / Bottom position value

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#174]
Documentation states:
Outlet support: On/off outlets are supported with independent control over each outlet (each is defined as an individual device). Additional parameters that should be used when defining an outlet are:

position: Specify the position of the outlet - valid values are 'top' or 'bottom' [default = top]

Editing the config.json for an outlet, cloning one entry into 2 and adding the position values to each results in this outcome. Am I reading the docs incorrectly?

                {
                    "name": "Office TV",
                    "deviceID": "42xxxx",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "top"
                },
                {
                    "name": "Office TV",
                    "deviceID": "42xxxx",
                    "dimmable": "no",
                    "deviceType": "outlet",
                    "position": "bottom"
                },

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: e4b2ad5f-ab4e-411a-b5b3-dd114f7caead
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:583:15)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:552:25
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at InsteonLocalPlatform.accessories (/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:811:2)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:534:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:528:12)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:139:36)

**Comment by kuestess** [comment]
@sahafeez The UUID is generated from the device name.  Give one of the above a different name and it should work.

**Comment by sahafeez** [comment]
Thanks. Really going to screw up my naming scheme. Oh well.

**Comment by sahafeez** [comment]
Did this and it works fine. Thank you.
