### ISSUE TITLE
Insteon Plugin causing Homebridge to reboot

### ISSUE THREAD

**Issue by Mattapoisett** [kuestess/homebridge-platform-insteonlocal#175]
I have been running the Insteon Plug-in for a while now without issue. However, now I'm getting the error below when Homebridge launches which causes it to crash and reboot.  If I disable the Insteon plugin, the issue goes away.  I'm running Homebridge in a Docker Container on a Synology NAS.  Is there anything which stands out which would allow me to troubleshoot further? 

Thanks!

11/30/2021, 12:25:32 AM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
stdout
08:25:32
    at new NodeError (node:internal/errors:371:5)
stdout
08:25:32
    at Hash.update (node:internal/crypto/hash:105:11)
stdout
08:25:32
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
stdout
08:25:32
    at InsteonLocalAccessory.init (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:2506:21)
stdout
08:25:32
    at new InsteonLocalAccessory (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:2463:12)
stdout
08:25:32
    at /homebridge/node_modules/homebridge-platform-insteonlocal/index.js:807:19
stdout
08:25:32
    at Array.forEach (<anonymous>)
stdout
08:25:32
    at InsteonLocalPlatform.accessories (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:806:15)
stdout
08:25:32
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:24
stdout
08:25:32
    at new Promise (<anonymous>)

**Comment by reisfni** [comment]
+1 (Running Homebridge Raspberry Pi Image 1.3.8 on a RPI 4).  I found that if I deleted the “Devices” section in the settings window, saved and rebooted Homebridge it solved the issue.  Can’t seem to connect to the express server via a browser (404), but that might be user error.

**Comment by Mattapoisett** [comment]
Were you then able to re-build the devices section to return everything to normal?

> +1 (Running Homebridge Raspberry Pi Image 1.3.8 on a RPI 4). I found that if I deleted the “Devices” section in the settings window, saved and rebooted Homebridge it solved the issue. Can’t seem to connect to the express server via a browser (404), but that might be user error.

**Comment by kuestess** [comment]
@Mattapoisett @reisfni Do you have the `name:` property defined for each of the devices in your config?  Looks like its the UUIDgen function puking on a missing property.

**Comment by Mattapoisett** [comment]
I did think it was set since it was working since I initially set it up. However I'll go through line by line and make sure everything is correct when I redo the configuration

**Comment by Mattapoisett** [comment]
Solved!  Thanks @kuestess!  Somehow these two entries added themselves to my config.json.  I might have fat fingered them there at some point. But now that I’ve gotten rid of them everything works fine.
                {
                    "dimmable": "true",
                    "deviceType": "dimmer"
                },
                {
                    "dimmable": "true",
                    "deviceType": "dimmer"
                }

**Comment by kuestess** [comment]
@Mattapoisett Perfect - glad you got it figured out!
