### ISSUE TITLE
Status in Home never stays synced, changes are delayed or never happen.

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#176]
So I have been using this for awhile and I am running into issue where status of things are just never are correct in Home and only restarting the server causes them to be updated. Also if I try to use Home to change something, like power something on and off, it does not work - it says it does - and I see the update in the Homebridge console. Then randomly a few minutes later the light will turn off.

I have tried various configurations of the "refresh" and the "keep alive" to no success. I have noticed that if refresh is on, after awhile I will see "Getting status for...xx" "Error getting status for..xx" in the logs. Then the next pass it will update.

I have looked at the network, the load on the server, etc. All are good. Any help on where to look would be greatly appreciated.

**Comment by kuestess** [comment]
@sahafeez This sounds a lot like an issue with Insteon network traffic.  First place I'd start is running homebridge in debug mode `homebridge -D`, let the plugin startup and go through its initial status stuff, and then watch the console for Insteon traffic.  Once everything settles down, you shouldn't see constant Insteon traffic - if you do, then you may have one that has lost its mind and is spewing out messages, or something similar.  I've tried to minimize the Insteon traffic with the plugin, but obviously some is needed to make it work.  If you're using scenes, use Insteon scenes and not Home scenes with multiple Insteon devices - Insteon scenes are way more efficient from the traffic perspective.  Just a few things to help start to narrow down the issue.

**Comment by sahafeez** [comment]
So I started fresh, created a new bridge and added 2 devices that seem to work. In the log however I do see:

[12/18/2021, 12:42:55 PM] [InsteonLocal] Got event for Sean Light Door (429xx)
[12/18/2021, 12:42:57 PM] [InsteonLocal] Received command for 4200xx
[12/18/2021, 12:42:57 PM] [InsteonLocal] Received command for 4113xx
[12/18/2021, 12:42:58 PM] [InsteonLocal] Received command for 412Bxx
[12/18/2021, 12:42:59 PM] [InsteonLocal] Received command for 4107xx
[12/18/2021, 12:43:00 PM] [InsteonLocal] Received command for 4188xx
[12/18/2021, 12:43:01 PM] [InsteonLocal] Received command for 418Axx
[12/18/2021, 12:43:03 PM] [InsteonLocal] Received command for 418Axx
[12/18/2021, 12:43:04 PM] [InsteonLocal] Received command for 418Cxx
[12/18/2021, 12:43:05 PM] [InsteonLocal] Received command for 418Cxx
[12/18/2021, 12:43:10 PM] [InsteonLocal] Received command for 418Dxx
[12/18/2021, 12:43:10 PM] [InsteonLocal] Received command for 4189xx

And it seems to keep going for a bit, stopping then happening again a few minutes later. Lost it's mind? Is there a known fix?

**Comment by kuestess** [comment]
@sahafeez The plugin listens to all Insteon traffic, only taking action on the devices it knows about.  In debug mode, it will show you all of the traffic it sees.  If you see the above sequence repeated, then you've got a few devices that are 'chatty' for whatever reason.  One common thing is other integrations connected to your Insteon account (Alexa, Harmony, etc) so maybe turn those off temporarily to see if it stops.  If you've migrated hubs then you might look at the device database in the ui for those devices to see if they are trying to communicate with an old Hub/PLM.  If it continues to repeat, you may want to think about factory resetting the affected devices.  This is a pain in the butt, so maybe a last resort, but you can always use the UI to re-link them.

**Comment by sahafeez** [comment]
So no Alexa, no Harmony, never migrated hubs.

I am not seeing any chatty traffic anymore, however it is still not working.

For example:

Hey Siri, turn on Patio lights:
[12/18/2021, 9:42:23 PM] [InsteonLocal] Discard on, sent too close to dim
Not on, ask again.
[12/18/2021, 9:42:41 PM] [InsteonLocal] Setting level of Patio Lights to 100%
[12/18/2021, 9:42:51 PM] [InsteonLocal] Patio Lights is on at 100%
Not on. Click on interface in home which shows ON - which turns them off (they are not on)
[12/18/2021, 9:43:21 PM] [InsteonLocal] Setting level of Patio Lights to 0%
[12/18/2021, 9:43:31 PM] [InsteonLocal] Discard on, already at commanded state
[12/18/2021, 9:43:31 PM] [InsteonLocal] Patio Lights is off at 0%
[12/18/2021, 9:43:39 PM] [InsteonLocal] Discard on, sent too close to dim
Click again now that home shows off -
[12/18/2021, 9:43:39 PM] [InsteonLocal] Setting level of Patio Lights to 100%

They are still not on.

The interesting thing is most of the status for things is correct in Home.

**Comment by kuestess** [comment]
@sahafeez Thanks for the detail above - this points to a different issue than Insteon traffic.  I think it has something to do with the debounce logic.  Does this only happen when you use Siri to control lights?  I've had this happen on occasion, but randomly and only when I use Siri.  Until now, no one else has reported an issue so I figured it was unique to my setup.  I haven't had a chance to look into it further, but will try to troubleshoot.

**Comment by sahafeez** [comment]
@kuestess I will do some testing and get back to you. In all cases above, I asked Siri first then went into the app at which point that did not work, however it is possible we are looking at some crazy blocking function where the UI and Siri are at olds. Who knows. 

Also please note the last line of my comment - this all worked nice and find after I wiped, added a few things (2) back and tested. Then I added the other 70 back and it broke again. So there might be a scale issue?

**Comment by kuestess** [comment]
@sahafeez Thanks - been doing some informal testing as well and always seems linked to using Siri.  Not sure what changed, but will continue to investigate.  The plugin relies on the assumption that any command worked, so anytime a Siri command doesn't go through, the state and Home app get out of sync creating the issues you are experiencing.  I used to confirm that the command worked, but that created a lot of extra Insteon traffic and lag...not the best user experience.  Could be a scale thing - I've got 40+ devices but haven't tried with a smaller subset of them.

**Comment by sahafeez** [comment]
@kuestess so I am seeing it as linked to the number of devices as I am seeing the same behavior when using the home app. I have just removed all the motion, door and leak sensors going from 70 to 59 devices. I am going to do some more testing with that setup and I will let you know.

**Comment by kuestess** [comment]
@sahafeez Did some troubleshooting and found an error in the debounce logic that would prevent a light from turning on.  Published v0.4.22 - try that out and see if it fixes your issues.

**Comment by sahafeez** [comment]
So I have uninstalled, and reinstalled the full setup. I have added only a few devices, 6. All show up in Home, neither Siri or direct control works after a few hours. When I create them and test it works. A few hours later the status in Home updates if I change things however the devices never turn on or off. If I reboot the Homebridge system it works for a bit then...

[1/3/2022, 9:40:43 PM] [InsteonLocal] Setting level of Patio Lights to 100%
[1/3/2022, 9:41:24 PM] [InsteonLocal] Setting level of Patio Lights to 0%
[1/3/2022, 9:42:02 PM] [InsteonLocal] Setting level of Patio Lights to 100%

**Comment by sahafeez** [comment]
This morning, the status in Home did not reflect the real status. There are msg like this in the log:

[1/4/2022, 7:44:32 AM] [InsteonLocal] Error getting power state of Rope Wine
[1/4/2022, 7:44:42 AM] [InsteonLocal] Error getting power state of Rope Front

As I know rebooting the Homebridge would fix this, I decided to try something else. I rebooted the Insteon Hub. A few minutes later the status was correctly reflected in Home. I tried changing the state of the light. It changed in Home and around 10 seconds later the light went on. 

At a bit of a loss here. It seems that breaking the connect, either by restarting Homebridge or the Hub will bring things back in line.

**Comment by kuestess** [comment]
@sahafeez The plugin actually does this for you.  You can use the `keepAlive` parameter in your config to set the interval in seconds.  Unless you've changed it, it defaults to 3600s (an hour).  This is typically frequent enough to keep the hub interested in talking to the plugin, but you might try to decrease the duration and see if that helps.  Unfortunately, what you're describing sounds like a hub with a capacitor that is about to fail (a known issue with Insteon hubs).  I've had it happen a few times, and this is the course things seem to take.  Not saying that's definitely the issue here, but sounds familiar :-).

**Comment by sahafeez** [comment]
@kuestess I do not believe this to be the issue. 

Here is what just happened.

1. At the time there is any issue in Home, both the Insteon applications can be opened and have the correct status and are able to control devices. 
2. This morning in Home devices are stuck at "updating..."
 a. The Homebridge log shows that the timer is working:
[1/6/2022, 8:46:25 AM] [insteonlocal] Closing connection to Hub...
[1/6/2022, 8:46:30 AM] [insteonlocal] Reconnecting to Hub...
3. At this point where home is not updating this morning I go to the InstonUI:3000 I click get hub info and get this output:
4. [1/6/2022, 9:19:24 AM] [unifi-poe-control] Refreshing devices...
Building Hub scene data...
Getting Hub info
undefined

/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137
            task();
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[1/6/2022, 9:19:58 AM] [insteonlocal] Child bridge process ended
[1/6/2022, 9:19:58 AM] [insteonlocal] Process Ended. Code: 1, Signal: null
[1/6/2022, 9:20:05 AM] [insteonlocal] Restarting Process...
[1/6/2022, 9:20:06 AM] [insteonlocal] Launched child bridge with PID 3862
homebridge API version: 2.7
[1/6/2022, 9:20:06 AM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[1/6/2022, 9:20:06 AM] [insteonlocal] Loaded homebridge-platform-insteonlocal v0.4.22 child bridge successful

At this point I restarted the server. Everything comes back up but devices are stuck at updating in Home on IOS, however their status is correct in the Homebridge Accessories UI and they can be controlled. 

I have no idea at this point if the issue is the plugin or Homebridge itself.

**Comment by kuestess** [comment]
@sahafeez The error in 3 and 4 above is because the plugin is not connected to the hub, so the hub info comes back undefined (should probably do better error handling there).  Do you see 'Connected to Insteon Model 2245 Hub...' in the console after the 'Reconnecting to hub...' message?  Connection watcher is working, but wonder if it actually reconnects to the hub.

**Comment by sahafeez** [comment]
@kuestess Yes, I do see that message.

**Comment by sahafeez** [comment]
So the system has been up and running for a few days with a limited number of Insteon items in it.

I just tried to change a light via the Accessories section of the Homebridge UI. It did not work.

```
[1/9/2022, 12:01:36 PM] [insteonlocal] Reconnecting to Hub...
[1/9/2022, 12:01:49 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:02:49 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:03:49 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:04:49 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:05:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:06:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:07:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:08:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:09:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:10:50 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:11:32 PM] [homebridge-lacrosseview] Discovering devices
[1/9/2022, 12:11:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:12:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:13:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:14:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:15:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:16:51 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:17:52 PM] [unifi-poe-control] Refreshing devices...
[1/9/2022, 12:18:15 PM] [insteonlocal] Setting level of Rope Wine to 100% <-----
```
The status of the items within the Insteon application is correct, network monitoring shows that the hub never misses a heartbeat check (checking every 2 minutes). Turning the Rope Wine on and off in the Insteon application works 100% of the time AND happens within 2 seconds of making the change.

There has to be something else going on here. Is there any deeper debugging that I can enable?

In this case above, I went into the Insteon application, and set the lights above on and off with no issue. I then opened the Insteonlocal:3000 server and clicked get hub info.

```
[1/9/2022, 12:24:53 PM] [unifi-poe-control] Refreshing devices...
Building Hub scene data...
[
  { group: 2, controllers: [ [Object] ], responders: [] },
  {
    group: 7,
    controllers: [ [Object] ],
    responders: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  {
    group: 71,
    controllers: [ [Object] ],
    responders: [ [Object], [Object] ]
  },
  { group: 75, controllers: [ [Object] ], responders: [ [Object] ] },
  {
    group: 76,
    controllers: [ [Object] ],
    responders: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  {
    group: 77,
    controllers: [ [Object] ],
    responders: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  {
    group: 78,
    controllers: [ [Object] ],
    responders: [ [Object], [Object] ]
  },
  {
    group: 79,
    controllers: [ [Object] ],
    responders: [ [Object], [Object] ]
  },
  { group: 255, controllers: [ [Object] ], responders: [] }
]
Getting Hub info
undefined

/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137
            task();
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[1/9/2022, 12:25:22 PM] [insteonlocal] Child bridge process ended
[1/9/2022, 12:25:22 PM] [insteonlocal] Process Ended. Code: 1, Signal: null
[1/9/2022, 12:25:29 PM] [insteonlocal] Restarting Process...
[1/9/2022, 12:25:29 PM] [insteonlocal] Launched child bridge with PID 4464
homebridge API version: 2.7
[1/9/2022, 12:25:30 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[1/9/2022, 12:25:30 PM] [insteonlocal] Loaded homebridge-platform-insteonlocal v0.4.22 child bridge successfully
[1/9/2022, 12:25:30 PM] Loaded 0 cached accessories from cachedAccessories.0E4D519D4BB0.
Initializing Insteon UI 
Reading config from /var/lib/homebridge/config.json
Found 5 platform(s) in config
Reading devices from insteon.json
[1/9/2022, 12:25:30 PM] [insteonlocal] Started connection watcher...
[1/9/2022, 12:25:30 PM] [insteonlocal] Found 7 devices in config
```

**Comment by kuestess** [comment]
@sahafeez This continues to seem like a connection problem with your hub.  The error you see above is consistent with that.   Opening the Insteon app creates a new connection, explaining why that works.  Sounds like the connectionWatcher is doing its job, and in fact reconnects to the hub.  A couple things to try - start by decreasing the `keepAlive` duration in your config to see if that helps.  You can also get additional debug information by starting homebridge with `DEBUG=* homebridge -D`.  That'll spit out a nearly overwhelming :-) amount of information, but may help detect an error.

**Comment by sahafeez** [comment]
So I am struggling with the ordering here. The log shows that the connection watcher is working, yet pushing a change in Homebridge does not work. Pushing it in the app (opens new connect does)? But that that point the UI on 3000 also fails? Is that the same connection as the main plugin? What keeps this connection awake? Is there TCP keep alive or other method?

**Comment by sahafeez** [comment]
So I have disabled all other plugins and I am running in debug mode. One thing I have noticed is that there seems to be a ton of traffic for no reason I can see. I have a Insteon Range Extender in the network. I just removed it and the "chattiness" stopped. Interesting. I am going to restart the server and see if the chattiness is a time thing or related to the extender.

**Comment by sahafeez** [comment]
@kuestess if the system is running correctly would you expect netstat or lost to show an open connection to the hub?

**Comment by sahafeez** [comment]
@kuestess So it is possible that I have sorted this out and it IS NOT a failing hub. I am running this setup in a VM on a KVM deployment. I started a tcpdump and captured the packets between the software and the smart hub. Turns out there were a ton of bad / incorrect checksums in the traffic. The NIC driver is `virtio`. I checked all the other VMs on the system and noticed the same issues, however it never effect anything else as there is not thing running that is connection sensitive. I ending up disabling tx offload in the vm `ethtool -K int tx off` and the errors went away. Now let us see if this fixes my issues.

**Comment by sahafeez** [comment]
@kuestess My first install was running on Proxmox and it mostly worked. I just moved all my VMs to a TrueNAS Scale setup. Not sure this is 100% the issue, but I am going to keep at it and see. While I am not seeing the bad packets anymore I am seeing the hub sending TCP RST after a bit.

**Comment by sahafeez** [comment]
@kuestess I am not as clever as I thought. The checksum errors have to do with how tcpdump pulls the packet from the kernel before it gets to the HW so the issue is not real on the wire. So I am at a loss now. I guess I can see if I can get a new hub. What I have noticed is that with a small number of items the system seems to stay stable. When I have the full number of devices, which is 64 real devices but 84 configured (outlets set to top/bottom) the system will not stay stable.

**Comment by kuestess** [comment]
@sahafeez Well crud, thought you were onto something there.  Sorry, gonna have to take your super nerd badge :-).  Before you jump to a new hub, if you've still got a hub pro headed your way, maybe try that out first.  It uses a serial connection rather than the http connection, so should be more robust.  The plugin asks the hub to do something it wasn't designed for (semi-persistent http connection) and perhaps with a larger number of devices its little brain can't handle it.  I've got 42 devices in my config running on a PLM with no issue (actually quite responsive).

**Comment by sahafeez** [comment]
@kuestess so I have been reading through the code and notes on the home-controller package. it looks like any sort of stable connection to the the http is never really going to work because of majorly poor design choices on the part of Insteon. This really does explain why they made the change in the "NEW" application not to update everything when opened, which makes it useless. I am going to see if I can get PLM and be done with it as I got sniped on the HubPro.

**Comment by kuestess** [comment]
@sahafeez Yep, they eliminated the dedicated PLM port that the 2242 had, leaving only an http interface, not to mention its quite underpowered.  PLM for me has been super stable and responsive.

**Comment by sahafeez** [comment]
@kuestess still trying to get a PLM - they are hitting $500 on Ebay. Ugh. Going to close this.
