### ISSUE TITLE
X10 switches and model 2245 Insteon

### ISSUE THREAD

**Issue by vhm14u2c** [kuestess/homebridge-platform-insteonlocal#177]
I see this no longer works again, and see no mention of it anywhere on how to use it anymore on the read me sections.

Has support been removed?

**Comment by kuestess** [comment]
@vhm14u2c X10 support hasn't been removed.  Honestly, I'm not sure if I ever added it to the readme (need to overhaul documentation).  Post more detail on your issue and happy to help troubleshoot.

**Comment by vhm14u2c** [comment]
This was a snippet of some docs that were in place where x10 devices did work sometimes in the past.  If it would not work the first time, the 2nd or 3rd try would usually work.

Snippets of The code below is still in place which was working in the past, but doesn't do anything anymore-

{
      "platform": "InsteonLocal",
      "name": "Insteon Local Platform",
      "user": "Xxxremoved",
      "pass": “yyyremoved",
      "host": "192.168.1.125",
      "port": "25105",
      "model": "2245",
      "refresh":"0",
      "server_port": "3000",
      "keepAlive": "3600",
      "devices": [
        { 
	  "name": "Living Room Light",
 	  "house" : "M",
	  “unit”: “6”,
  	  "dimmable" : "no",
 	  "deviceType" : "x10" 
        }]
        [...]
    },
[...]

{
"name": "My X10 wallswitch",
"house": "M",
"unit": "2",
"deviceType": "x10"
}

**Comment by kuestess** [comment]
@vhm14u2c Thanks for the above - can you help me understand the issue?  If you have some console output from when the issue occurs, that would also be helpful.  Your config looks correct.
