### ISSUE TITLE
BridgeERROR(node:13124) MaxListenersExceededWarning

### ISSUE THREAD

**Issue by JimCSaratoga** [kuestess/homebridge-platform-insteonlocal#178]
I have been adding additional Insteon devices to the config file and came across this node error related to the total number of  listeners.  Is this a parameter that I can modify to address the memory leak issue?  Thanks for the help in advance!!!

ref:
12/20/2021, 12:21:24 PMPlatform Insteonlocal BridgeLoading 1 platforms...
12/20/2021, 12:21:24 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
12/20/2021, 12:21:24 PMPlatform Insteonlocal BridgeInsteonLocalFound 16 devices in config
12/20/2021, 12:21:25 PMPlatform Insteonlocal Bridge**ERROR(node:13124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Insteon]. Use emitter.setMaxListeners() to increase limit
12/20/2021, 12:21:25 PMPlatform Insteonlocal BridgeERROR(Use `node --trace-warnings ...` to show where the warning was created)**
12/20/2021, 12:21:25 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
12/20/2021, 12:21:25 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub...

**Comment by JimCSaratoga** [comment]
There was an older thread on this with HOOBS (which I am using) and an older version of Node (the thread was closed / stale without a resolution) 
https://github.com/hoobs-org/HOOBS/issues/752

**Comment by kuestess** [comment]
@JimCSaratoga The  plugin has a number of listeners that are setup initially, beyond the (standard?) limit set by node.  They fire once and then they're done.  You can safely ignore this warning.

**Comment by JimCSaratoga** [comment]
Many thanks for the clarification! I personally appreciate how beneficial your work is to help the Insteon community continue on.

**Comment by kuestess** [comment]
@JimCSaratoga Happy to do it - glad its working well for you!
