### ISSUE TITLE
Keypad as a button

### ISSUE THREAD

**Issue by haywirecoder** [kuestess/homebridge-platform-insteonlocal#179]
Hi, 

I am trying to setup keypad button as on/off button for Homekit device (e.g. Hue bulb). Is their way to expose the keypad as buttons, so I can trigger on and off bulb?

**Comment by kuestess** [comment]
@haywirecoder Yep, you can doe exactly that.  Just configure as a keypad - see example below:

```
{               
    "name": "E button",
    "deviceID": "XXXXXX",
    "deviceType": "keypad",
    "keypadbtn": "E"
 }
```

**Comment by haywirecoder** [comment]
Awesome, thank you!
