### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [kuestess/homebridge-platform-insteonlocal#18]
Just setting up a new Homebridge Hub and I've hit this brick wall with your plugin:

serialport@5.0.0 install /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@10.8.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build'
gyp ERR! System Linux 4.14.32+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Linux 4.14.32+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build/Release' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@5.0.0 (node_modules/homebridge-platform-insteonlocal/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by kuestess** [comment]
@Kung-Foo-Kamel That's an optional dependency for home-controller that you should only need if using a serial PLM.  Does homebridge run despite the error?  If not, add `--unsafe-perm` to the end of your npm install command.

**Comment by Kung-Foo-Kamel** [comment]
Hi bud, i haven't run homebridge yet, I'm just installing all the plugins first and was stopped by this one, --unsafe-perm seems to have worked.

Cheers.
