### ISSUE TITLE
Nokia Smart Lighting

### ISSUE THREAD

**Issue by donavanbecker** [kuestess/homebridge-platform-insteonlocal#183]
do you know if it would be possible to use this with the [Nokia Smart Lights](https://nokia.smartlabsinc.com)? since they are also Insteon? or [SmartLab](https://www.smartlabsinc.com) Products?

I can get you any info, if you need it to support them.

**Comment by kuestess** [comment]
@donavanbecker Now that you mention this, I remember hearing about it a few years ago (Nokia partnership).  Not a ton of technical info on their site, but it appears that they are using the Insteon protocol and an eerily-similar looking hub :-).  Assuming that's the case, I don't see any reason that the plugin wouldn't work with the Nokia devices as well.

**Comment by donavanbecker** [comment]
@kuestess any way I could send you a little info? I tried but wasn't able to get it to work? I have used Http Catcher to get some info.

are you on the homebridge discord server?

**Comment by kuestess** [comment]
@donavanbecker Just joined the discord.
