### ISSUE TITLE
Using insteonlocal with Hoobs Box, Express server error

### ISSUE THREAD

**Issue by vanpatrickbevill** [kuestess/homebridge-platform-insteonlocal#184]
I recently purchased a Hoobs Box (lovely little thing!) and am trying to use the Platform Insteonlocal Bridge. The bridge is installed and running, with no devices defined yet.

The first problem I had is that I could not get to InsteonUI on the IP address of the Hoobs on port 3000. I checked my json file to make sure everything was set correctly, and noticed that even though I had selected model 2245 in the Insteonlocal settings dialog, this setting "model" was completely missing from the json and I had to add it manually.

Once I added the "model", my file looks like this:

{
    "platform": "InsteonLocal",
    "name": "InsteonLocal",
    "user": "preset user on bottom of 2245",
    "pass": "preset password for 2245",
    "host": "192.168.1.123",
    "port": "25105",
    "model": "2245",
    "refresh": false,
    "server_port": "3000",
    "keepAlive": false
}

After the bridge starts, it successfully connects to my Insteon 2245, the Insteon event listener and Express server start. The problem I have now is that when I browse the Hoobs IP address on port 3000 the Express server throws lots of errors. My logs are below.

Thanks in advance for any assistance!

Patrick Bevill

---------------begin Hoobs logs--------------------

1/16/2022, 4:18:12 PMPlatform Insteonlocal Bridge starting
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeLoading 1 platforms…
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalERRORNo devices defined - please add devices to your config.json
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher…
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalFound 0 devices in config
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeBridge is running on port 51825.
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub…
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started…
1/16/2022, 4:18:27 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server…
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORTypeError: Cannot read properties of undefined (reading 'forEach')
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat buildDeviceTable (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat InsteonUI.renderMainPage (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat InsteonUI.handleRequest (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat expressInit (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/init.js:40:5)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat query (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/query.js:45:5)
1/16/2022, 4:20:47 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORTypeError: Cannot read properties of undefined (reading 'forEach')
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat buildDeviceTable (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat InsteonUI.renderMainPage (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat InsteonUI.handleRequest (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat expressInit (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/init.js:40:5)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat query (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/query.js:45:5)
1/16/2022, 4:20:53 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORTypeError: Cannot read properties of undefined (reading 'forEach')
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat buildDeviceTable (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat InsteonUI.renderMainPage (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat InsteonUI.handleRequest (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat expressInit (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/init.js:40:5)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat trim_prefix (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat /var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat Function.process_params (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat next (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat query (/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/query.js:45:5)
1/16/2022, 4:21:02 PMPlatform Insteonlocal BridgeERRORat Layer.handle as handle_request

-------------end Hoobs logs-------------------

**Comment by kuestess** [comment]
@vanpatrickbevill Looks like you don't have any devices defined on your config yet (and I don't properly handle that case).  Add at least one device via the homebridge/hoobs ui and then try.

**Comment by vanpatrickbevill** [comment]
Thanks! That did the trick. I was hoping it would work such that I could get to the InsteonUI first and then poll the devices to complete the configuration.

About the hoobs interface not registering the "model" selection- is that a hoobs issue or a homebridge issue? Sorry, I'm just not that familiar with who is doing what on products like hoobs.

Thanks again!

**Comment by vanpatrickbevill** [comment]
@kuestess So, I was able to get to Insteon UI by manually adding a device, I can get hub info and get devices and links, but there are still some issues. After I get devices and links, I see them on the devices tab, however they are missing the names I have assigned to them in the Insteon app (all are blank.) Also, when I go back to the configuration tab, none of the discovered devices appear there. There is only the one I added manually. On the devices tab, I have 9 devices including one I do not recognize with deviceID 888888, which has no flags, links, or scenes (could be my manual one, but it doesn't have any of the attributes I gave it.) Finally, the only device that appears in hoobs is the one I manually defined. I think I must be missing  something really basic, because I'm a noob, but I hope you can help. What other information would be useful?

**Comment by kuestess** [comment]
@vanpatrickbevill What you describe is exactly how the ui is supposed to work - its intended to be a ui to manage your devices and device configuration, not specifically for managing your homebridge config.  Yes, there is a config tab and you can use it to add devices, but it doesn't talk to the other tabs so the devices that are discovered aren't automatically added to your config.  For device names, that information is stored in the Insteon app and not on the Hub so there's no way to get those names.  If you've added devices to the config, then it will pick up those names from the config.  I would recommend using the Homebridge ui to add devices to your config as its more flexible.  I may be able to add a feature to add discovered devices to the config, but that will be down the road.

**Comment by vanpatrickbevill** [comment]
Thanks, that's good context! I'll try you recommendation.

**Comment by kuestess** [comment]
@vanpatrickbevill No idea where that would have come from.  You can probably just change the device id to a real one.
