### ISSUE TITLE
I can't control an accessory in the HOOBS dashboard or in the HomeKit app.

### ISSUE THREAD

**Issue by wsantia2** [kuestess/homebridge-platform-insteonlocal#187]
@kuestess kuestess

**Description**
I can't control an accessory in the HOOBS dashboard or in the HomeKit app.

**Expected behavoir**
Have local control of an Insteon device (dimmers)

**Plugin name**
homebridge-platform-insteonlocal

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
4.1.22

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
No. macOS Monterey 12.1 (21C52)

**Post your config**

* Remove any passwords from the config file. This is public.

```
    "accessories": [],
    "platforms": [
        {
            "platform": "InsteonLocal",
            "name": "InsteonLocal",
            "user": "xxxxxxx",
            "pass": "xxxxxxx",
            "model": "2245",
            "host": "192.168.x.xx",
            "port": "25105",
            "refresh": "false",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Second",
                    "deviceID": "1D.CD.1A",
                    "dimmable": "true"
                }
            ]
        }
    ]
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
2/11/2022, 4:09:51 PMPlatform Insteonlocal BridgeConfiguration change
2/11/2022, 4:09:51 PMplatforminsteonlocalbridge stopping
2/11/2022, 4:09:57 PMPlatform Insteonlocal Bridge starting
2/11/2022, 4:10:13 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
2/11/2022, 4:10:13 PMPlatform Insteonlocal BridgeLoading 1 platforms...
2/11/2022, 4:10:13 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
2/11/2022, 4:10:13 PMPlatform Insteonlocal BridgeInsteonLocalFound 1 devices in config
2/11/2022, 4:10:14 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
2/11/2022, 4:10:14 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub...
2/11/2022, 4:10:14 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started...
2/11/2022, 4:10:14 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...
```

**Additional context**
I can see accessory in HOOBS, but when pressing the Icon nothing happens. In HomeKit I get an icon but no action can be triggered. The Insteon ID device was verified and is working normal via the wall dimmer. All accessories, HOOBS and Mac are connected to the same network.

**Comment by wsantia2** [comment]
Additional images
![HOOBS detail 1](https://user-images.githubusercontent.com/39568943/153665015-ab044929-b703-423e-989d-b68dc831563e.jpg)
![homekit details 2](https://user-images.githubusercontent.com/39568943/153665024-013e3413-3f42-40ca-8f00-c18804bc3cc1.jpg)
![homekit details](https://user-images.githubusercontent.com/39568943/153665027-0b419162-48b8-40e0-a012-38b43becfbe3.jpg)
![Homeki accessory](https://user-images.githubusercontent.com/39568943/153665028-3dbf479b-48c8-49a3-8a77-2fa69a2494cf.jpg)
![HOOB accsessory](https://user-images.githubusercontent.com/39568943/153665030-2c9549ee-f1bf-4513-be07-fd6d2418c746.jpg)

**Comment by wsantia2** [comment]
After sending creating the Issue, I changed the type from dimmer to Switch and it works. The device is a Dimmer switch but is now workin as a switch. Hope this can help the troubleshooting. The unit is a Insteon Remote Control Dimmer Switch SKU: 2477D

**Comment by kuestess** [comment]
@wsantia2 Your config posted above is missing the `deviceType` key.  Add it to your config like below and it should work.

```
{
     "name": "Second",
     "deviceID": "1D.CD.1A",
     "dimmable": "true",
     "deviceType": "dimmer"
}
```
