### ISSUE TITLE
Polling support for Insteon USB adapter (2448A7)

### ISSUE THREAD

**Issue by brian4286** [kuestess/homebridge-platform-insteonlocal#189]
I have been experiencing major delays with the Insteon Hub v2. I can see the commands quickly execute in HB but have a noticeable delay executed. I understand the PLM 2413U & 2412S should be more reliable/faster but they are on backorder from what I have been told will be later this year. So I picked up a Insteon USB adapter (2448A7) and with my new Insteon gear it seems to work fine most of the time and provides nearly instant response when setup as PLM device.

The only issue I am experiencing is the USB adapter is not responding to HB with device status and the devices are getting out of sync. I don't know if device status is normally a function of the other PLM's (2413U/2412S) or not. Should insteonlocal be able to poll a USB adapter (2448A7) or is possibly something not setup correctly or am I missing something?

**Comment by magicvash** [comment]
Can you post your config file with the 2448A7 working?  I'm having trouble getting the PLM to work properly myself.

**Comment by brian4286** [comment]
I worked right out of the box for me as a PLM:

> {
>     "name": "InsteonLocal",
>     "user": "true",
>     "pass": "true",
>     "host": "/dev/ttyUSB0",
>     "port": "25105",
>     "model": "PLM",
>     "refresh": "0",

**Comment by magicvash** [comment]
Interesting. Are you running this on Linux or macOS?

**Comment by brian4286** [comment]
Linux box but on macOS I would try `ioreg -p IOUSB`

**Comment by kuestess** [comment]
@magicvash Periodic polling should work fine with the 2488 - just change the value for `refresh` in your config to whatever interval you want the plugin to poll for status.

**Comment by brian4286** [comment]
@kuestess I have adjusted it but it does not appear that it is able to pull the status from the 2448A7:

> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Kitchen sink primary
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Driveway Flood
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Garage Outside Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Landscape Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Front Door Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Livingroom Inside Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Downstairs Hallway Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Powder Room Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Office
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Office Desk
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Front Door Inside Light
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Kitchen Main
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Livingroom outside
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Hot water recirculator
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Stairs
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Powder Room Open/Close
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Master Bedroom
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Office Main
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Master Bathroom Shower
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Master Bathroom Main
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Garage Main
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Deck Main
> [21/02/2022, 19:31:56] [InsteonLocal] Getting status for Dog Run
> [21/02/2022, 19:31:56] [InsteonLocal] Getting state for Powder Room Fan
> [21/02/2022, 19:31:56] [InsteonLocal] Connected to Insteon PLM...
> [21/02/2022, 19:31:56] [InsteonLocal] Insteon event listener started...
> [21/02/2022, 19:31:56] [InsteonLocal] Started Insteon Express server...
> [21/02/2022, 19:31:56] [InsteonLocal] Error getting power state of Driveway Flood
> [21/02/2022, 19:31:56] [InsteonLocal] Error getting power state of Garage Outside Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Error getting power state of Landscape Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Error getting power state of Livingroom Inside Lights
> [21/02/2022, 19:31:56] [InsteonLocal] Error getting power state of Downstairs Hallway Lights
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Powder Room Lights
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Office
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Office Desk
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Kitchen Main
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Livingroom outside
> [21/02/2022, 19:31:57] [InsteonLocal] Error getting power state of Hot water recirculator
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Powder Room Open/Close
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Master Bedroom
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Office Main
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Master Bathroom Shower
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Master Bathroom Main
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Garage Main
> [21/02/2022, 19:32:03] [InsteonLocal] Error getting power state of Deck Main
> [21/02/2022, 19:32:04] [InsteonLocal] Error getting power state of Dog Run

**Comment by sahafeez** [comment]
@kuestess I was hoping to get away from this stuff but then Insteon had to go and shut down before I was able to sell the house :) 

So I have moved everything over from the HUB to the 2448A7 (what a pain, used old houselinc to verify everything, reset most and rebuild the senes and linking). Everything seems to work, however sometimes it just does not, IE, status does not update or light does not go off. 

I have set the refresh to 120 seconds and I am seeing the same issue listed above with the "Error getting..." messages. What can I do to help debug this?

**Comment by kuestess** [comment]
@sahafeez Welcome back (to hell?) sir!  You really like to torture yourself :-).  Do the errors above happen right away or after the plugin has been running for a while?  Does it go away with a restart?

**Comment by brian4286** [comment]
I experimented with this more. I could’t get a PLM but I had a old v1 hub which I was able to activate prior to Insteon going into liquidation.

It has the same issue, status is not kept by any PLM based device that I tried. This is really apparent when you turn on a switch manually but HA never picks up the device is on. Thus HomeKit automation can fail.

**Comment by sahafeez** [comment]
@kuestess on startup, some will work, some will not. It seems VERY RANDOM as it changes each time. Then with refresh set, I will see the errors for some but not others. Wash, rinse repeat. 

A side question, Get All Links say "okay, I am done" but it does not ask every device, and I have been going through one by one and hitting get links, at which point it says "no changes, what to do anyway?" Hit yes, and then it finds 8 links. I can open another issue for it, but I just wanted to bring it up. On the refresh I am seeing the same thing as the OP.
