### ISSUE TITLE
Cannot use express server

### ISSUE THREAD

**Issue by magicvash** [kuestess/homebridge-platform-insteonlocal#190]
I have 2 issues:

Trying to set this up in my home bridge server since I'm trying to migrate over from Indigo.  Here's my config:

{
            "name": "InsteonLocal",
            "user": "Hubusername",
            "pass": "Hubpassword",
            "host": "192.168.123.166",
            "port": "25105",
            "model": "2245",
            "refresh": "3",
            "server_port": "3000",
            "keepAlive": "false",
            "platform": "InsteonLocal"
        }

I'm trying to use InsteonUI to simplify adding devices since I have 42 switches + 5 fanlincs

127.0.0.1:3000 just says cannot connect to server 127.0.0.1.  I'm clearly doing something incorrect

Separate issue:

So I decided, well lets use my PLM instead.  this is the config I have.  I even added a device in the home bridge GUI.  I see the device in the home app, but it doesn't respond to turning on/off lights.

{
            "name": "InsteonLocal",
            "user": "Hubusername",
            "pass": "Hubpassword",
            "host": "/dev/tty.usbserial-A700ahHk",
            "port": "25105",
            "model": "2245",
            "refresh": "3",
            "server_port": "3000",
            "keepAlive": "false",
            "devices": [
                {
                    "name": "Library Lights",
                    "deviceID": "58.BB.AC",
                    "dimmable": "true",
                    "deviceType": "dimmer"
                }
            ],
            "platform": "InsteonLocal"
        }

BUT if I instead use the Insteon Hub to login and replace "host" with the IP address of the host, and keep the rest the same - everything works correctly.  I'd much prefer to use the PLM because I have all the devices already loaded in that modem.  Specifically, I have 5 fanlincs that if I have to manually add to the hub, which would require some degree of dismantling fans and I would *REALLY* like to avoid doing that.

I'm very new at this - I'm tempted to just go back to Indigo since it worked without issue, but I'm determined to migrate away if I can.  Hope that someone can help me sort this out!

**Comment by magicvash** [comment]
Update:

Now when I use this configuration:
`

        {
            "name": "InsteonLocal",
            "user": "*******",
            "pass": "*******",
            "host": "/dev/tty.usbserial-A700ahHk",
            "port": "25105",
            "model": "PLM",
            "refresh": "false",
            "server_port": "3000",
            "keepAlive": "false",
            "devices": [
                {
                    "name": "Library Lights",
                    "deviceID": "58.BB.AC",
                    "dimmable": "true",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Hangar Bay Lights",
                    "deviceID": "58.B6.EA",
                    "dimmable": "true",
                    "deviceType": "dimmer"
                }
            ],
            "platform": "InsteonLocal"
        }
`
I get this error:

Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:415:7)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:304:8)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)

`

**Comment by kuestess** [comment]
@magicvash You'll definitely have a better experience with the PLM in terms of response speed.  Unfortunately the `serialport` dependency has been a pain on some platforms.  Fortunately, its fairly easy to fix - just install `serialport` globally with: `npm i -g serialport`.

**Comment by magicvash** [comment]
Thanks for the assist! I tried installing serial port but I still get the same error

[2/21/2022, 4:41:58 PM] TypeError: this.SerialPort is not a constructor
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:153:17)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:415:7)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:304:8)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)'

I'm in the process of migrating from my Mac mini server to a raspberry pi - I'll have to see if the PLM option works on that instead.

The express server doesn't work for me though. Am I doing something wrong?

**Comment by magicvash** [comment]
I just installed an Ubuntu virtual machine and got everything set up.  It all works perfectly.  I think the problem was macOS not doing something correctly and it was causing the problems.  Thanks for your assistance!
