### ISSUE TITLE
Multi-Keypad Controller Issue

### ISSUE THREAD

**Issue by JimCSaratoga** [kuestess/homebridge-platform-insteonlocal#191]
Kuestess thanks again for building this wonderful plug-in; it's saved my investment in over 100 Insteon devices.

Having an issue I can't resolve and welcome your advice on this.  

My configuration is the following:
3 Insteon Dimmer Switches; 2 Scene buttons on different Keypads; all controllers/responders for a group of can lights in a hallway
They are all defined in an Insteon group 59 as controllers/responders

I've tried the following configuration so that I could keep the nature of how they worked with the Insteon consistent:
```
{
            "name": "Second Floor Hallway Lights",
            "deviceID": "22ZA45",   { this is the 2477D switch that is physically connected to the lights }
            "deviceType": "scene",
            "dimmable": true,
            "groupID": "59",
            "groupMembers": "2BZ3CD,2BZ510",  { the other two 2477Ds that are in the hallway }
            "targetKeypadID": [
                "447Z39",    { the first 8 button keypad }
                "2B9Z8F"    { the second 8 button keypad }
            ],
            "targetKeypadBtn": [
                "F",
                "D"
            ],
            "targetKeypadSixBtn": [
                false,
                false
            ]
        }
```

The problem I'm having is that I can turn on the lights with the Home app but if I turn them off with one of the keypad buttons I'm not receiving an update on the Home app.   The log doesn't show the received event from the keypad (either of them) and so the Home app never knows that the lights were turned off by a keypad button.  I've also tried adding a controller and using that same deviceID but am toggling the Home app status incorrectly

FYI 
I've been able to make this work in my garage but it only has one keypad in the controller group and it is the one used for the DeviceID:

```
{
            "name": "Garage Lights",
            "deviceID": "2B9Z8F", { the keypad dimmer }
            "deviceType": "scene",
            "dimmable": "no",
            "groupID": "19",
            "keypadbtn": "H",
            "groupMembers": "30ZF87,2879Z0,2A60ZE,2A6Z71,28Z1D0", { the 2477S switches in the scene }
            "targetKeypadSixBtn": false,
            "controllers": [
                "37AEFZ" { the 2477S that is actually physically connected to the lights }
            ]
        }
```

Any and all advice is greatly welcomed.  Thanks !!!

**Comment by JimCSaratoga** [comment]
I've also just tried to make it a simple group and rely upon the hub's scene to take care of updates and still no luck - if I turn on the scene from HomeKit and turn it off from either of the keypads the update to the plugin never arrives.  Is there any way to specify a scene button in the controller group?

```
{
            "name": "Second Floor Hallway Lights",
            "groupID": "59",
            "deviceType": "scene",
            "dimmable": true
        },
```

**Comment by kuestess** [comment]
@JimCSaratoga Seems odd that you get the group broadcast (scene) for the 'on' command, but not 'off'.  Can you run homebridge in debug mode `homebridge -D` and post the output when you push the on/of button on your keypads?

**Comment by JimCSaratoga** [comment]
will do - I'm running this on Hoobs and get a slew of errors trying to turn on debug mode.  I'm going to move this to another hombridge (clean on a Mac mini) server and see what happens and report back

**Comment by JimCSaratoga** [comment]
Sending you a DM with the log

**Comment by kuestess** [comment]
@JimCSaratoga Sorry for taking a bit to get back to you, and thanks for sharing the log.  I didn't find any references to your two keypads (447Z39 and 2B9Z8F).  Do you have those defined in your config, and can you share the log with button presses for those keypads?

**Comment by JimCSaratoga** [comment]
@kuestess no worries at all.... I only had them defined in the structure as above as group members.
Since the buttons aren't the primary buttons how should I define them?

**Comment by kuestess** [comment]
@JimCSaratoga You could define them as a keypad.  I think this is probably why you're not getting a status update from the keypads - the plugin purposely doesn't do anything with devices that aren't in the config as there's no status to update.

**Comment by JimCSaratoga** [comment]
getting an error after updating to the latest version of the plugin:

`[3/26/2022, 11:28:16 PM] Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/application.js:618:24)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:387:9
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/httpClient.js:164:9
    at _fulfilled (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:854:54)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:624:44`

**Comment by JimCSaratoga** [comment]
All set @kuestess it was the lack of definition of the keypads and a scene that was left over on my hub that was toggling one of the buttons ( I still haven't been able to figure out why with debug turned on ).  But it's working now when I use apple home scenes with momentary set as true.  
Thanks for the help.  One more case to close.
