### ISSUE TITLE
Siri does not recognize insteon device names

### ISSUE THREAD

**Issue by essvee0** [kuestess/homebridge-platform-insteonlocal#192]
For quite a few weeks now, I have been dealing with an issue where Siri does not seem to understand names of devices added via this homebridge insteon module. When asked to turn on or off one of these devices, Siri on a HomePod typically says "sending to your iPhone" and sends web search results. This seems to be in general what happens when a name isn't recognized as a HomeKit device. When the same thing is tried directly on an iPhone, I sometimes get web results, and sometimes get a "something went wrong, please try again" error. An odd thing is that on rare occasions (maybe 10% of the time), Siri does recognize the name and turns on/off the device. When this happens, it all seems to work okay for at least a few minutes. This problem only occurs with insteon homebridge devices, and not with any native HomeKit supporting devices. I have tried deleting the insteon bridge and re-adding it. That seemed to cause everything to work for few minutes at least, but then it was right back to the same problem. What kind of debug information can I send to help this problem be understood more? Thank you!

**Comment by essvee0** [comment]
Thanks for the reply. No, my only homebridge plugin is for insteon. Last night I tried changing the name and it didn't help anything. This morning I went to try it again, but today it is working with the old name! That related issue you linked does seem to describe a very similar problem, so I think that puts the problem somewhere in the Homekit/homebridge territory, and not in your particular plugin! So sorry for the trouble. I'll keep experimenting next time it stops working.

**Comment by kuestess** [comment]
@essvee0 No problem - happy to help.  One other thought, maybe try creating another home in the Home app and add your bridge to that.  That might isolate some issue with your current home config.

**Comment by essvee0** [comment]
I am afraid to speak too soon, but so far it seems that HomePod software update 15.4.1 fixes this!

https://www.macrumors.com/2022/03/31/apple-releases-homepod-15-4-1-software/

**Comment by kuestess** [comment]
@essvee0 I saw that and thought of this issue as well - hope that was the issue.

**Comment by essvee0** [comment]
It seems that was really the problem! 5 days later and it hasn't happened once. I'll close now. Thanks again for the help!
