### ISSUE TITLE
Device not working

### ISSUE THREAD

**Issue by jandreaucodes** [kuestess/homebridge-platform-insteonlocal#193]
Disclaimer: I'm just getting this set up for the first time and believe I've done everything correctly.

I'm replacing Indigo Domo with Homebridge and the Insteon plugin. I configured it with a spare PLM (side note: can I use the one tied to Indigo if I disconnect it? Will it read all of the devices, groups, scenes, schedules by default?)

The Express server is running without issue and I was able to add my test dimmer switch via the GUI.

Here's my sample config with a single device:
`{
            "name": "Insteon",
            "user": "true",
            "pass": "true",
            "host": "/dev/tty.usbserial-AL02YD4P",
            "port": "25105",
            "model": "PLM",
            "refresh": "true",
            "server_port": "3000",
            "keepAlive": "true",
            "devices": [
                {
                    "name": "Mikes Office",
                    "deviceID": "3C.69.A1",
                    "deviceType": "dimmer",
                    "dimmable": "yes"
                }
            ],
            "platform": "InsteonLocal"
        },`

Here's the logs:
`[3/23/2022, 4:17:24 PM] [Insteon] Setting level of Mikes Office to 100%
[3/23/2022, 4:17:43 PM] [Insteon] Setting level of Mikes Office to 0%`

Although the logs indicate it's turning the light on and off, nothing's actually happening there. What am I missing?

**Comment by jandreaucodes** [comment]
Adding: when I go to Devices and click "Get Devices", I get "No devices in Insteon config - please click Get Devices to get links and devices from Hub".

Maybe I'm doing this all wrong. Does my hub (in this case, the PLM) need to have all the data for the Devices on it before I set this up? I _thought_ that's what I was defining in the GUI, but maybe I'm wrong here.

Any help is appreciated.

**Comment by kuestess** [comment]
@jandreaucodes Sorry for the delay in responding - looks like you got things running with the main PLM.  You are correct that you need to add these devices to your config.json, either manually (using the sample config.json from the repo) or using the Insteon or homebridge UI.  Once you have them defined in your config, you should be able to control via the Home app.

If you want to use the spare PLM, then you will need to link all of your devices to the spare PLM - you can do that on the 'Links' tab in the Insteon UI.

**Comment by jandreaucodes** [comment]
Got it.

Any thoughts why, when I use my original PLM, logs show it changing a device but the device isn’t actually changing?

**Comment by kuestess** [comment]
@jandreaucodes Likely because the device wasn't linked to the hub.  The plugin assumes it is (doesn't do any checks) and send the command.  If the device isn't linked to the hub then it will ignore the command.
