### ISSUE TITLE
Manually pressing Keypad buttons not working

### ISSUE THREAD

**Issue by will02591** [kuestess/homebridge-platform-insteonlocal#194]
Firstly, thank you for keep updating this great plugin.

I bought an 8 Button keypad and a hub(2245) for controlling other HomeKit devices (e.g. Philips Hue, Tado) via Homebridge. I successfully added the keypad into homebridge but I found that the status of Button B to H will not be updated in homebridge when I manually pressed those buttons. Also no logs showed for it (debug mode too). However, this problem does not exist for Button A. There will be some logs and the status will update when I manually press button A

What I want to do is 8 buttons control different devices/scenes via HomeKit. Only 1 button can perform it now. 

I config the Button in the following format:
```
                {
                    "name": "Button A",
                    "deviceID": "AABBCC",
                    "dimmable": "false",
                    "deviceType": "keypad",
                    "keypadbtn": "A"
                },
                {
                    "name": "Button B",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "B"
                },
                {
                    "name": "Button C",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "C"
                },
                {
                    "name": "Button D",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "D"
                },
                {
                    "name": "Button E",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "E"
                },
                {
                    "name": "Button F",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "F"
                },
                {
                    "name": "Button G",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "G"
                },
                {
                    "name": "Button H",
                    "deviceID": "AABBCC",
                    "deviceType": "keypad",
                    "keypadbtn": "H"
                }
```
What can I do for Button B to H? 

Thanks.

**Comment by will02591** [comment]
Something I missed to mention. For buttons B to H, the LED State would synchronize to Homebridge if I turn it on/off on Homebridge/HomeKit. 

Hope this information can help.

**Comment by kuestess** [comment]
@will02591 Sorry for the delay in responding.  I just tested this on my setup (similar config) and it seems to be working.  Can you run homebridge in debug mode `homebridge -D` and post the output of button presses on the keypad?
