### ISSUE TITLE
Dual On/Off Outlet Support (2663-222)

### ISSUE THREAD

**Issue by aw-0** [kuestess/homebridge-platform-insteonlocal#196]
Thanks to Insteon shutting off their servers, this plugin has been becoming *very* helpful. I have a [Dual On/Off Outlet (2663-222)](https://www.smarthome.com/products/insteon-2663-222-on-off-outlet-white) that I'd like to hookup to InsteonLocal, however there doesn't seem to be support for both outlets. I tried setting it up under the default "outlet" device type, but that only seems to trigger the bottom outlet. Appreciate all the work you put into this plugin.

**Comment by kuestess** [comment]
@aw-0 I would argue that it was helpful even before Insteon pooped the bed ;-).  You can set the position of the outlet by adding the `position` key and setting that to either `top` or `bottom`.  Hope that helps - let m know if you have other issues!

**Comment by aw-0** [comment]
Oh for sure! Thanks for your help, that ended up being the fix :)
