### ISSUE TITLE
Max Listener Exceed Warning

### ISSUE THREAD

**Issue by iBaird44** [kuestess/homebridge-platform-insteonlocal#199]
Does this need addressing? Everything seems to be working (slight delays sometimes but that's mostly the norm) I do see that the child bridge has to restart periodically due to an error.

(node:61781) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Insteon]. Use emitter.setMaxListeners() to increase limit

**Comment by JimCSaratoga** [comment]
per the link below it can safely be ignored

https://www.reddit.com/r/homebridge/comments/kkrcjb/max_listeners_exceeded_warning_dont_know_what_to/

@kuestess to verify that I am correct

**Comment by kuestess** [comment]
@JimCSaratoga You are correct - also see here (#170)
