### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by logname** [kuestess/homebridge-platform-insteonlocal#2]
I'm able to get a light (Insteon Micro Dimmer) to publish in the Home app, but the moment I tap it to adjust its state, I receive the following error and homebridge exits.

Error setting level for Overhead Light

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:362
			callback(error, null);
   ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:445:7
    at Request._callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:362:4)
    at self.callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)

**Comment by kuestess** [comment]
@logname Do you have any other devices configured and working with the plugin?  The fact that you got an error in response back from the Hub might mean that you have a problem with your configuration.  Not out of the question that I may have too many callbacks :-) but if we can check your config that might get you going while I can look into the callbacks more.  I just tested with one of my micro dimmers and it seems to be working.

**Comment by logname** [comment]
Same error if I configure a plugin module:

"platforms": [
   {
      "platform": "InsteonLocal",
      "name": "Insteon Local Platform",
      "user": "<obscured>",
      "pass": "<obscured>",
      "host": "192.168.1.24",
      "port": "25105",
      "model": "2245",
      "refresh":"300",
      "server_port": "3000",
      "devices": [
            { "name": "Table Lamp",
              "deviceID" : "2467DC",
              "dimmable" : "yes",
              "deviceType" : "lightbulb" }
                ]
    }
  ]
}

**Comment by logname** [comment]
But a different error if I configure a 2477S ON/OFF Wall switch. Am I missing a prerequisite?

Error setting power for Kitchen Light

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:303
			if (response.statusCode == 200) {
               ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:303:16)
    at self.callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by kuestess** [comment]
So it looks like you're having a problem connecting to the Hub.  When you start up homebridge,  do you get the 'Connected to Insteon Hub.  Server listening on port....' and 'Insteon event listener started' messages?  One thing to try is to start homebridge and then try to turn on/off the device using the Express server.  You can try:

 `http://[IP of host running homebridge]:[server_port]/light/[id]/on` 

in the browser and see if the device turns on.  I ran into an issue where my Hub password got corrupted - it appeared ok in the Insteon app, but wouldn't let me connect to the Hub.  Changing it in the Insteon app fixed that.  I don't see any problem that would point to dependencies/pre-requisites.

**Comment by logname** [comment]
Got it working. Changed password, but same issue. Tried changing server port and the error stopped, but still didn't get "Connected to Insteon Hub.  Server listening on port xxxx". Changed password back and it still didn't connect. Changed server port back to 3000 and it worked. Thanks so much for your help and the plugin. It's badass!

**Comment by logname** [comment]
Issue resolved

**Comment by kuestess** [comment]
Glad you got it working!  I think that the latest Hub firmware update has created alot of issues with connections.  I had everything working fine and then it stopped after the latest update.  Had to go through those same gymnastics with password/port/etc to get it to connect.  Enjoy!
