### ISSUE TITLE
Express Server updates

### ISSUE THREAD

**Issue by logname** [kuestess/homebridge-platform-insteonlocal#20]
Hi Scott,

I'm helping test a Hubitat driver one of the community memebers is creating for me and the rest of the Hubitat community so we can use Express Server to control Insteon lights via HTTP GET. He has ON/OFF working for lights and polling so Hubitat will match the Insteon light's state after sending the command. He also has level working, but we have noted that there isn't a defined way to set the ramp rate.

My pre-defined ramp rate is being honored when the light is turned on and off, but not when specific dim levels are sent. As I know you are aware, HomeKit also does not honor a ramp rate then changing levels via slider, only when turning on and off as well. I have also notice that the  plugin in not changing the HomeKit status when lights are turned on or off by sending commands via the Express Server. To me that a minor detail, but it does create and issue for usability via HomeKit together
with Hubitat via HTTP, since when an HTTP GET request it sent to Express Server to turn the light on, for example, HomeKit doesn't reflect that change and shows the light as OFF.

I tried setting the refresh rate to 1 (not a great idea I know), but HomeKit still doesn't update from a change made via Express server.

**Comment by kuestess** [comment]
@logname Just published 0.3.9 that should add status updating in Homebridge when you use the express server.  Let me know if you have any issues!

**Comment by logname** [comment]
Working for outlets, switches and lightbulbs, but for some reason not dimmers or plugin dimmer modules. It the light turns off via Express Server, but the status in HomeKit goes from 100% to a random dimmed amount such as 89%, 73% or something like that. It's as if the status update is terminating before the ramp is completed.

**Comment by kuestess** [comment]
@logname Published a new version that adds a 1 second delay to the status check for on commands from the Express server.  It seemed to work fine with my plugin dimmer modules - give it a try and see if that works for you.

**Comment by logname** [comment]
Issue resolved
