### ISSUE TITLE
Status code expected 200

### ISSUE THREAD

**Issue by mmz2584** [kuestess/homebridge-platform-insteonlocal#204]
Trying to setup the Insteon and and got this code right out of the gate. Rejection error status code expected 200. Any ideas what it is?

**Comment by kuestess** [comment]
@mmz2584 Sorry - will need more info than that :-).  Can you post your config and the error that you're getting?

**Comment by kuestess** [comment]
@mmz2584 You can just copy and paste it here.  Make sure to anonymize your login credentials.

**Comment by mmz2584** [comment]
here is what im getting.

4/20/2022, 5:22:36 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
4/20/2022, 5:22:36 PMPlatform Insteonlocal BridgeLoading 1 platforms...
4/20/2022, 5:22:36 PMPlatform Insteonlocal BridgeInsteonLocalERRORNo devices defined - please add devices to your config.json
4/20/2022, 5:22:36 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
4/20/2022, 5:22:36 PMPlatform Insteonlocal BridgeInsteonLocalFound 0 devices in config
4/20/2022, 5:22:37 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
4/20/2022, 5:22:37 PMPlatform Insteonlocal BridgeWARNINGunhandled rejection: Error: Status code expected 200, got 401

**Comment by mmz2584** [comment]
Name
InsteonLocal
Username
**********
Password
**********
Host
192.168.1.72
Port
25105
Model
2245
Refresh
0
Server Port
3000
Keep Alive
3600

**Comment by mmz2584** [comment]
"platform": "InsteonLocal",
    "name": "InsteonLocal",
    "port": "25105",
    "refresh": "0",
    "server_port": "3000",
    "keepAlive": "3600",
    "user": "mnj.bgutfr@hu.com",
    "pass": "Kfube8963",
    "host": "192.168.1.72",
    "devices": [
        {
            "name": "Bar Ceiling Light",
            "deviceID": "50.08.CE",
            "dimmable": "yes"

**Comment by kuestess** [comment]
@mmz2584 That doesn't look like your entire config, but if it is you're missing the `model` key.  You can just add `"model": "2245",` to the line below the host.

**Comment by mmz2584** [comment]
So I got it to work but now I added a few devices and they are not working in home app or on the hoobs dashboard.

**Comment by mmz2584** [comment]
"platform": "InsteonLocal",
    "name": "InsteonLocal",
    "port": "25105",
    "model": "2245",
    "refresh": "0",
    "server_port": "3000",
    "keepAlive": "3600",
    "user": "hgghhh",
    "pass": "kkhgf",
    "host": "192.168.86.34",
    "devices": [
        {
            "name": "Mia's Lamp",
            "deviceID": "26C506",
            "dimmable": "yes"
        },
        {
            "name": "Living Room Lamp",
            "deviceID": "26C6B8",
            "dimmable": "yes"
        },
        {
            "name": "China Cabinet Light",
            "deviceID": "26F542",
            "dimmable": "yes"

**Comment by mmz2584** [comment]
4/20/2022, 7:58:34 PMNest Cam BridgeNest-camConfiguring accessory Playroom
4/20/2022, 7:58:35 PMNest Cam BridgeBridge is running on port 51846.
4/20/2022, 7:58:38 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
4/20/2022, 7:58:39 PMPlatform Insteonlocal BridgeLoading 1 platforms...
4/20/2022, 7:58:39 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
4/20/2022, 7:58:39 PMPlatform Insteonlocal BridgeInsteonLocalFound 3 devices in config
4/20/2022, 7:58:40 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
4/20/2022, 7:58:40 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub...
4/20/2022, 7:58:40 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started...
4/20/2022, 7:58:40 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...
4/20/2022, 7:58:40 PMNest BridgeNestiniting thermostat (P) "Living Room Thermostat": deviceId: 18B430000074FA8B structureId: a8a44c30-bc0b-11e5-9b27-22000a618baf
4/20/2022, 7:58:40 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: a8a44c30-bc0b-11e5-9b27-22000a618baf structureId: a8a44c30-bc0b-11e5-9b27-22000a618baf
4/20/2022, 7:58:40 PMNest BridgeNestiniting temp_sensor (P) "Media Room": deviceId: 18B430C2EAF812DD structureId: a8a44c30-bc0b-11e5-9b27-22000a618baf
4/20/2022, 7:58:40 PMNest BridgeNestiniting temp_sensor (P) "Briellas Room": deviceId: 18B430C82E0EE0AF structureId: a8a44c30-bc0b-11e5-9b27-22000a618baf
4/20/2022, 7:58:40 PMNest BridgeNestiniting protect "Basement": deviceId: 18B43000002FF8F2 structureId: a8a44c30-bc0b-11e5-9b27-22000a618baf

**Comment by mmz2584** [comment]
when i add them as switches they work but when i add them as dimmers they do not work

**Comment by mmz2584** [comment]
sorry to keep posting but figure share info with you to maybe help. so i just switched the devices back to "dimmer" from "switch" and now they work. Do you think i will have to do this for all of my dimmer switches?

**Comment by kuestess** [comment]
@mmz2584 Lamplincs should work as dimmers, so you shouldn't have to switch them btw switch and dimmer.  Should just work as a dimmer.

**Comment by mmz2584** [comment]
I was able to add devices, now all of a sudden i can not add devices. i enter the info in and save and the devices do not show up in accessories. Kitchen cabinet light works and appears but the kitchen can lights do not.

  "name": "Kitchen Cabinet Light",
            "deviceID": "3582B6",
            "dimmable": "yes",
            "deviceType": "dimmer",
            "controllers": "2BD754"
        },
        {
            "name": "Kitchen Can Lights",
            "deviceID": "2BC6E6",
            "dimmable": "yes",
            "deviceType": "dimmer",
            "groupID": "29",
            "groupMembers": "2BC6E6, 2BCFFF"
        },
        {
            "name": "Kitchen Can Lights",
            "deviceID": "2BCFFF",
            "dimmable": "yes",
            "deviceType": "dimmer",
            "groupID": "29",
            "groupMembers": "2BC6E6, 2BCFFF"
        }

**Comment by mmz2584** [comment]
4/21/2022, 7:54:06 PMPlatform Insteonlocal BridgeConfiguration change
4/21/2022, 7:54:07 PMplatforminsteonlocalbridge stopping
4/21/2022, 7:54:12 PMPlatform Insteonlocal Bridge starting
4/21/2022, 7:54:23 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
4/21/2022, 7:54:24 PMPlatform Insteonlocal BridgeLoading 1 platforms...
4/21/2022, 7:54:24 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
4/21/2022, 7:54:24 PMPlatform Insteonlocal BridgeInsteonLocalFound 10 devices in config
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub...
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Mia's Lamp
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Living Room Lamp
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for China Cabinet Light
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Bar Ceiling Light
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Briella's Lamp
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Family Room Lamps
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Kitchen Cabinet Light
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Kitchen Cabinet Light
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started...
4/21/2022, 7:54:25 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...
4/21/2022, 7:55:19 PMPlatform Insteonlocal BridgeConfiguration change
4/21/2022, 7:55:19 PMplatforminsteonlocalbridge stopping
4/21/2022, 7:55:25 PMPlatform Insteonlocal Bridge starting
4/21/2022, 7:55:36 PMPlatform Insteonlocal BridgeLoaded plugin 'homebridge-platform-insteonlocal'
4/21/2022, 7:55:36 PMPlatform Insteonlocal BridgeLoading 1 platforms...
4/21/2022, 7:55:36 PMPlatform Insteonlocal BridgeInsteonLocalStarted connection watcher...
4/21/2022, 7:55:36 PMPlatform Insteonlocal BridgeInsteonLocalFound 10 devices in config
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeBridge is running on port 51826.
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalConnected to Insteon Model 2245 Hub...
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Mia's Lamp
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Living Room Lamp
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for China Cabinet Light
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Bar Ceiling Light
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Briella's Lamp
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Family Room Lamps
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Kitchen Cabinet Light
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Kitchen Cabinet Light
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started...
4/21/2022, 7:55:37 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...

**Comment by kuestess** [comment]
@mmz2584 You have "Kitchen Can Lights" in your config twice.  Each device has to have a unique name - jus change one of them and that should fix it.

**Comment by mmz2584** [comment]
I tried 5 different devices with unique names and it’s not adding them as well

**Comment by kuestess** [comment]
@mmz2584 I think the issue is that you have the wrong set of user/pass in your config.  You'll need to use the user/pass from the bottom of your hub rather than the email/pass that you used for your (former) Insteon account.  If you changed the user/pass via the app before everything shut down then you'll need to use that.
