### ISSUE TITLE
Can't control Insteon switch - HomeKit unsupported

### ISSUE THREAD

**Issue by twswfit** [kuestess/homebridge-platform-insteonlocal#207]
I just installed a new HOOBS unit, configured the bridge, pulled device from the hub (and confirmed it visually at the switch), added the device to the plug-in, linked the HOOBS to my Home app and it pulled the device info into the app however the Home app it says it's not supported:

![IMG_0193](https://user-images.githubusercontent.com/104223798/164771767-b4be3a11-7a01-4ba7-8617-56aec28dfed9.jpg)

Can you advise on a solution?  Thanks!

**Comment by kuestess** [comment]
@twswfit That's a pretty standard warning with homebridge accessories but shouldn't;t affect functionality.

**Comment by twswfit** [comment]
Alas it is.  Is there any kind of diagnostics that I can do that would reveal why it's not working?   Seems like if I can get all that info into the Home app via HOOBS/Insteon-local that It should be across the line by then....

**Comment by kuestess** [comment]
@twswfit Can you run homebridge in debug mode `homebridge -D` or click the 'bug' icon at the top of the log page in HOOBS and post?

**Comment by kuestess** [comment]
@twswfit It looks like homebridge is restarting repeatedly - can you post your config?
