### ISSUE TITLE
Understanding Insteon Links group number

### ISSUE THREAD

**Issue by myriaxis** [kuestess/homebridge-platform-insteonlocal#209]
Hi,
Thank you very much for your plugin. A real lifesaver.

I'm new to Homebridge. I transferred a few days ago after the Insteon servers shutdown.
I'm trying to understand the links group numbers.
Having many scenes programmed in the hub that I can no longer modify, So I started to clean the Insteon Hub links and scenes.
A quick way would have been to factory reset the hub, but I don't want to loose the user/password configuration.
Also, some Insteon devices are hard to reach.
I think I successfully deleted most of the links and scenes between the hub and devices.
Some group numbers seems directly related to specific scenes.
But what about group numbers 0 and 1.
What are they related to?
I have two similar devices (on/off top/bottom outlet) without scene, one with groups 0 and 1 numbers and the other with only group 1.
Please provide some insight.
Francois

**Comment by JimCSaratoga** [comment]
@kuestess will give the best answer here but having looked at my config it looks like group 0 and 1 are used to link the hub to the devices and then the devices back to the hub.   Why the ramp rates are 0.1 (even for switches that aren't dimmers) is confusing. Hope that helps in the mean time.

**Comment by kuestess** [comment]
@JimCSaratoga is correct - those are group numbers used to link the device to the hub, so don't delete unless you want to unlink the device from the hub.

**Comment by myriaxis** [comment]
Thanks @kuestess and @JimCSaratoga.
It makes sense. However, the two devices were part of the same room and the same set of scenes (now deleted).
Why one would have group number 0 and 1, and the other just group 1?
If, as you say and that makes sense, group 0 and 1 are for the links between the hub and the devices, then shouldn't both devices be part of group 0 and 1?

Few more questions:
If I understand correctly, playing with Hub, Devices and Link tabs, we essentially read/modify the Hub content.
Playing with Config tab, we add/delete/modify which Insteon devices are available in the HomeKit app.
There is no automatic transfer of information between what we do in the Config tab and what we do in the Hub/Devices/Link tabs and vice versa. Correct?
So far, I found easier to modify the config.json manually via text editor rather than using the Config tab.
It seems to work, because I can see, in the Config tab list, the devices I added manually via the config.json file.
However, I noticed that the device type list is different (shorter) on the Config tab compared to the allowed device types listed in the readme.
I assume that the Config tab is just a close enough report of what's in the config.json file and only the content of the config.json file is really affecting the system behaviour. Am I correct?

Thanks again for your patience with my slow learning curve.

**Comment by kuestess** [comment]
@myriaxis Starting with your question on the config tab, I would recommend using the Homebridge or HOOBS ui to add/modify devices - its a lot more robust.  The config tab in the ui does work, although as you point out it is limited.  I may consider disabling it in future updates in favor of the Homebridge/HOOBS ui.  I agree that manually adding to the config.json is easier, but that's my personal preference :-).  Any names that you have defined in your config.json will be transferred over to the devices tab (based upon device id), but that's the only interaction.

For groups - there are two sets of 'groups' that you need to think about, the hub and the device.  Basic linking of a device to a hub makes the Hub a responder to group 1 of the device which allows the hub to track changes in device status.  The other half of basic linking is making the device a responder to group 0 of the hub.  So, you should have a group 0/1 link for each device.  Most stuff may work ok if only group 1 is linked, but proper linking to the hub includes both groups.  The ui can do this for you on the link tab.

**Comment by myriaxis** [comment]
Thank you again @kuestess to take the time to answer me.
I tried to unlink a device (a motion sensor) using the "unlink from hub" command on the link tab.
I used the devide id without dots, but it didn't work.
I finally reset the device to factory defaults and manually deleted all links associated to the device.
The device no longer show up in the hub list.
Then I tried to add the device using the "link to hub" command on the link tab.
I used the devide id without dots, but it didn't work.
I get the following messages:
-Linking 416CFD to hub
-Error linking 416CFD to hub
I get the same error if I use 41.6C.FD.
I'm sure that I have the latest versions of Homebridge and InsteonUI since I just installed a fresh copy of Ubuntu 22.04.
While I'm trying to unlink/link the device, the device is configured in config.json. Should I remove it?
While I'm trying to unlink/link, should I tap or hold the set button on the device?

**Comment by myriaxis** [comment]
I tried a hub reset, but I have the same result.
Could there be a problem because I have the latest versions of Ubuntu, Homebridge, NodeJS, etc?

**Comment by kuestess** [comment]
@myriaxis Battery powered devices are a special case.  They are RF only and leave their radio off most of the time except for a periodic 'heartbeat' or if there's an event (motion in this case).  To link using the ui, you'll need to hold down the set button on the device until the LED starts blinking and then use the link button in the ui.

**Comment by myriaxis** [comment]
I just tried what you suggested.
I pressed the set button until the LED starts blinking (once every 2 seconds approx).
I used the InsteonUI Link function abd got the same error linking message.
To diagnose the problem, is there a more detailed log to look at?
By any chance, do you have a copy of the HouseLinc s/w? I could give it a try.

**Comment by myriaxis** [comment]
I don't know what I'm doing wrong, but I'm not able to control my Insteon devices via InsteonUI.
Since battery operated devices are complicated, I decided to try a wall switch dimmer (model 2477D). From the InsteonUI, I see that the device is linked to the hub (model 2245-222) in group 0 and 1. There is no scene. The device is also configured in the config.json.
I tried to unlink the dimmer from the hub using the "Unlink from Hub" function from the link tab. The InsteonUI refreshes saying the unlink performed succesfully.
I go to the Configuration Tab and the device is still shown (I guess this is OK since the device is listed in the config.json). I go to the Hub tab and I see that the device links are still shown. I go to the Devices tab and the device is no longer shown.
Has the device been unlinked or not?
So, I go to the Hub tab and refresh the devices/links with "Get Devices/links" and the device links (group 0 and 1) are still shown.
I go to the Devices tab and refresh the Devices List and the device is now shown on the list, but there is no data in the device info.
So I refresh the device info/links and "voila" the device info and links (group 0 and 1) are now shown.
What am I missing (or do not understand)?
My understanding of the Insteon network is that links between the hub and a device are stored in the hub and in the device. So if I use the "Unlink from Hub" function, I assume that InsteonUI would issue all the commands required to remove the links (and scene if any) in the hub and in the device. After an unlink, the device would only show in the Configuration tab since I kept it configured in config.json. If I use the "Link to Hub" function,  I assume that InsteonUI would issue all the commands required to add the links (groups 0 and 1) in the hub and in the device.
I'm probably wrong, so please help me understand :-)

**Comment by kuestess** [comment]
@myriaxis When you unlink a device, it isn't automatically removed from your config - you'll need to do that.  The unlink code removes it from the list on the devices page, but does not refresh the Hub links (you need to do that too on the Hub tab).  On unlinking/linking, you are correct - the code will add/remove from both the hub and device.

**Comment by myriaxis** [comment]
@kuestess Thanks for the clarifications. To successfully unlink a device from the hub, should I first remove it from the config.json?

**Comment by kuestess** [comment]
Order doesn’t matter.
