### ISSUE TITLE
Using config, or express server to add new items overwrites modification like "position": "top"

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#211]
If you add a new device by plugin config or express server it will nuke the items not expressed in that UI.

**Comment by sahafeez** [comment]
@kuestess just saw you added this. I have a few plugs to add. Let me test it and get back to you with the results! Thanks!

**Comment by sahafeez** [comment]
seems to work.

**Comment by smcahee** [comment]
having this same issue.  when i use the 'plugin config, save changes and restart homebridge', the "position": "bottom" entry for dual outlets disappears.  it seems the author of this post found a solution however it isn't clear to me what it is.

**Comment by kuestess** [comment]
@smcahee Recommend that you use the config gui in Homebridge to add devices.  If you're using that and still seeing this issue let me know.
