### ISSUE TITLE
Error setting Keypad Status / Network outage

### ISSUE THREAD

**Issue by JimCSaratoga** [kuestess/homebridge-platform-insteonlocal#212]
@kuestess one of my HomeKit automations failed to complete with the following error log:

`4/24/2022, 7:18:08 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Driveway Lanterns 2
4/24/2022, 7:18:08 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Driveway Lanterns 1
4/24/2022, 7:18:08 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Landscape Lights Module
4/24/2022, 7:18:08 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Landscape Lights
4/24/2022, 7:18:08 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Garage Lanterns 1
4/24/2022, 7:18:09 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Garage Lanterns 2
4/24/2022, 7:18:09 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Garage Entry Keypad - Driveway Lanterns' was slow to respond!
4/24/2022, 7:18:09 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Garage Entry Keypad - Garage Lanterns' was slow to respond!
4/24/2022, 7:18:15 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Garage Entry Keypad - Driveway Lanterns' didn't respond at all!. Please check that you properly call the callback!
4/24/2022, 7:18:15 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Garage Entry Keypad - Garage Lanterns' didn't respond at all!. Please check that you properly call the callback!
4/24/2022, 7:18:15 PMPlatform Insteonlocal BridgeInsteonLocalSetting state of Master Bedroom Keypad - Night Lights to true
4/24/2022, 7:18:16 PMPlatform Insteonlocal BridgeInsteonLocalSetting level of Stairwell Sconce 2 to 26%
4/24/2022, 7:18:16 PMPlatform Insteonlocal BridgeInsteonLocalSetting level of Stairwell Sconce 1 to 26%
4/24/2022, 7:18:16 PMPlatform Insteonlocal BridgeInsteonLocalGot on event for Landscape Lights
4/24/2022, 7:18:16 PMPlatform Insteonlocal BridgeInsteonLocalGetting status of scene device Landscape Lights Module
4/24/2022, 7:18:18 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Landscape Lights Module
4/24/2022, 7:18:18 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Master Bedroom Keypad - Night Lights' was slow to respond!
4/24/2022, 7:18:24 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge AD9C@On] The write handler for the characteristic 'On' on the accessory 'Master Bedroom Keypad - Night Lights' didn't respond at all!. Please check that you properly call the callback!
4/24/2022, 7:18:25 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Master Bedroom Keypad - ON
4/24/2022, 7:18:25 P`

I rebooted the hoobs that the plugin is running on and I was able to manually turn on those automations.  When I did that I did get the following error log where I'm still having issues setting keypad status.. I did have a network outage and would welcome your thoughts if that might have impacted the Insteon Hub in some way that could cause this issue with Keypad button writes

`4/24/2022, 7:42:54 PMPlatform Insteonlocal BridgeInsteonLocalGetting status for Stairwell Sconce 2
4/24/2022, 7:42:54 PMPlatform Insteonlocal BridgeInsteonLocalInsteon event listener started...
4/24/2022, 7:42:54 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...
4/24/2022, 7:43:11 PMPlatform Insteonlocal BridgeInsteonLocalSetting state of Master Bedroom Keypad - Night Lights to true
4/24/2022, 7:43:11 PMPlatform Insteonlocal BridgeInsteonLocalSetting power state of Family Room Outlets to on
4/24/2022, 7:43:12 PMPlatform Insteonlocal BridgeInsteonLocalSetting level of Stairwell Sconce 2 to 26%
4/24/2022, 7:43:12 PMPlatform Insteonlocal BridgeInsteonLocalSetting level of Stairwell Sconce 1 to 26%
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [2] button [G] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [B] button [undefined] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [9] button [undefined] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [A] button [undefined] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [8] button [undefined] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocal also setting target keypad [F] button [undefined] to true
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [2]
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [B]
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [9]
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [A]
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [8]
4/24/2022, 7:43:13 PMPlatform Insteonlocal BridgeInsteonLocalError getting button states for target keypad [F]
`

**Comment by kuestess** [comment]
@JimCSaratoga I don't recognize the errors in the first post above - they don't look like 'typical' error messages from homebridge or the plugin (ie, the 'slow to respond' or 'didn't respond at all' error messages).  The error messages in the second post are because there is a brightness characteristic being added to a switch (which doesn't dim), but the code doesn't add brightness to a switch.   Perhaps the first one is related to your network issues (still curious where those messages are from), but not sure where the extra brightness characteristic comes from.

**Comment by JimCSaratoga** [comment]
@kuestess 

sorry about those "brightness" characteristics - caught that one too late to reply back. 

on the too slow to respond I typically get those on keypad updates... I'm over 50 devices now so am wondering if it's a Hoobs processing thing or maybe the Insteon hub not responding quickly enough.

**Comment by JimCSaratoga** [comment]
@kuestess 

happy to have this one closed
