### ISSUE TITLE
Water Leak Sensor, Motion Sensor

### ISSUE THREAD

**Issue by TCLGuy1** [kuestess/homebridge-platform-insteonlocal#214]
HI, I can't seem to get Dev info on Insteon Motion Sensors (the newer kind) and Water Leak Sensors. Any thoughts on how to get these scanned in? Thanks!

**Comment by JimCSaratoga** [comment]
Not sure when you say "scanned" in but if you manually add them to the Configuration it would look like this:

`{
                    "name": "Garage Motion Sensor",
                    "deviceID": "321DAC",
                    "deviceType": "motionsensor",
                    "dimmable": "no"
                },
                {
                    "name": "First Floor Bathroom Leak Sensor",
                    "deviceID": "3B9D0E",
                    "dimmable": "no",
                    "deviceType": "leaksensor"
                },`

**Comment by TCLGuy1** [comment]
Thanks! What I meant by scanned in is to get device info in Insteon UI. 
I would like to delete some links from them.

**Comment by kuestess** [comment]
@TCLGuy1 Since those a re all battery powered devices, they keep the radio off most of the time to preserve battery.  You should be able to wake them up by tapping the set button and then clicking 'Get device info'.
