### ISSUE TITLE
Express http://localhost:3000/devices/ does not seem to pull in named items from the configure devices?

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#221]
@kuestess is the express server suppose to pull in the names of the configured devices in the config.json file? I thought it did, but it is not doing it in my current setup. Maybe my brain is just remembering wrong?

**Comment by kuestess** [comment]
@sahafeez Yep, you're remembering correctly.  Anything defined in your config with a matching device id should automagically be named in the ui.

**Comment by sahafeez** [comment]
So I had named the items in express BEFORE adding them in the config.json. That is the starting point. I removed an item that was in insteon.json, (left it in config.json) restart, did get devices and the device showed up without the name as configured in config.json. I guess I could NUKE the insteon.json, restart and get devices again. What do you think?

**Comment by sahafeez** [comment]
@kuestess I removed the insteon.json file and restarted the server. In express there are no devices. I clicked on "get devices". It pulled in all 85, but there are no names. Something cached somewhere else?

**Comment by sahafeez** [comment]
@kuestess is there away to set a retry setting for get links. I just clicked to get all links on this and half the devices report an error on devices with known links.

Error getting database delta
Getting device links for 4114D1
linkArray: []
No links returned from 4114D1
Error getting links for 4114D1
Getting device info for 418CC3
Getting operating flags for 418CC3
Flags (ED): ["00","01","0f","d7","00","20","1c","fe","3f","00","00","00","19","ef"]
Flags (SD): "00"
Getting database delta for 418CC3
Error getting database delta
Getting device links for 418CC3
linkArray: []
No links returned from 418CC3

For example 4114D1 has links. If I pick that exact item and click get links on it it it will say "No changes to device database. Update links anyway?" click yes then all of the sudden it has links!

So then I have to go through and do each of the 85 individually.
