### ISSUE TITLE
Issues with devices no longer in the home

### ISSUE THREAD

**Issue by mbcooper9734** [kuestess/homebridge-platform-insteonlocal#228]
I have a couple of clients where we've had devices fail and they were replaced but the old device seems to be still linked to the hub.  Anything in the API about force unlinking a device.  They are causing scenes to fail in the system.  Also, is there some hidden way to delete a group from the hub that I'm not seeing.  I'm committed to helping you with this as I'm a very adept javascript programmer and It's in my best interest to have an interface to do this.

**Comment by kuestess** [comment]
@mbcooper9734 The easiest way is probably to use the ui.  Since it sounds like the devices are no longer functional, the easiest way is to go to the hub tab, find the right group, and delete the dead device.  Appreciate any PRs/contributions as I’m a crappy coder at best :-)
