### ISSUE TITLE
Garage door emits "closed" event when restarting homebridge

### ISSUE THREAD

**Issue by rcombs** [kuestess/homebridge-platform-insteonlocal#24]
I'm not sure how easy this would be to work around, but currently whenever I restart homebridge, I get a notification as if my garage door had just been closed, regardless of the previous state. I think the way HAP-Nodejs intends you to handle this is by binding the `get` event on the characteristic, rather than by emitting an update on startup.

**Comment by kuestess** [comment]
@rcombs You are correct that HAP-NodeJS provides a `get` event, however binding that to characteristics (at least for the Insteon plugin) doesn't provide a good user experience and creates a lot of Insteon traffic.  I did exactly that in some early versions (maybe not even released) and with a reasonable number of devices the Home app spends a lot of time displaying 'Updating' every time you open it.  For that reason, I removed the getters and chose to use initial status along with the event listener/polling for status.  

I get the close notices for my garage doors as well, and I'm not sure that there's a way to avoid that.  The status update that I trigger on startup is the same as the getter would be.  Homekit initializes the door status characteristic as 0 (open) on startup so it will appear that the door was closed once status is updated.  To my knowledge, there's not a way to filter that.

**Comment by rcombs** [comment]
Could you cache the state in persistent data, and only set it during startup if it's changed?

**Comment by scottyg54** [comment]
@jeffwhalen, I have my Garage Door IOLink setup so that the status's are in sync. Since my magnet and sensor are adjacent when the door is closed, I have "Sensor Sends" set to "Off when closed" in order to achieve this. This is in the Insteon app under the IOLink device settings.
