### ISSUE TITLE
Random Error - Switch / Dimmer characteristic

### ISSUE THREAD

**Issue by JimCSaratoga** [kuestess/homebridge-platform-insteonlocal#241]
Having an issue with an automation that hasn't occurred in the past.  The error is when I'm trying to turn on "Family Room Outlets".  The only change to my configuration is an update to the latest version of the plugin.  Here's the log:

`
5/9/2022, 8:01:39 PMPlatform Insteonlocal BridgeInsteonLocalStarted Insteon Express server...
5/9/2022, 8:05:09 PMPlatform Insteonlocal BridgeInsteonLocalSetting power state of Landscape Lights Module to on
5/9/2022, 8:05:09 PMPlatform Insteonlocal BridgeInsteonLocalSetting power state of Landscape Lights to on
5/9/2022, 8:13:11 PMPlatform Insteonlocal BridgeInsteonLocalGot on event for Family Room Outlets
5/9/2022, 8:13:11 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge 1CD6@Family Room Outlets@Family Room Outlets@Brightness] Characteristic not in required or optional characteristic section for service Switch. Adding anyway.
5/9/2022, 8:13:22 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Garage Lights 2
5/9/2022, 8:13:23 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Garage Lights 1
5/9/2022, 8:13:30 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Garage Lights 3
5/9/2022, 8:13:32 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Garage Lights 4
5/9/2022, 8:13:32 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for Master Bedroom Keypad - Outlets
`
The Characteristic not in required or optional characteristic is a new error and the switch does not turn on.

Here's the config for the switch (nothing out of the ordinary and it did work with the same automation in the past):
`
  {
                    "name": "Family Room Outlets",
                    "deviceID": "330B8F",
                    "deviceType": "switch",
                    "dimmable": "no"
                },
`

**Comment by kuestess** [comment]
@JimCSaratoga The characteristic error means that the code is apparently trying to add 'Brightness' to a switch, which doesn't make sense (thought I took care of those, but need to look again), but it shouldn't impact functionality.  None of the recent updates have touched that code.  Does the switch work outside outside of automations?

**Comment by JimCSaratoga** [comment]
Thanks @kuestess - yes and I am able to articulate it using Accessories also

**Comment by JimCSaratoga** [comment]
confirmed - operator error - sorry @kuestess
