### ISSUE TITLE
Garage Door Status remains 'Open' after restarting HB

### ISSUE THREAD

**Issue by THX723** [kuestess/homebridge-platform-insteonlocal#258]
Lately I've noticed my Garage Door status remained 'Open' after restarting HB. Normally the restart is proceeded with a series of device poll, but I no longer see Garage Door (IOLinc) included, which means the actual Garage Door state never gets updated. Has there been a change to this part of the code?

**Comment by kuestess** [comment]
@THX723 No change to that part of the code - has your config.json changed such that the IOlinc definition is no longer valid?

**Comment by THX723** [comment]
@kuestess Stand corrected. Not sure what that was, but it appears to be working properly with this last reboot. Thanks.
