### ISSUE TITLE
express server status issue

### ISSUE THREAD

**Issue by microbmen** [kuestess/homebridge-platform-insteonlocal#285]
Not sure when this stopped working but seem like /status stopped working a bit ago.  Is anyone else having this issue? 

I used to be able to get status by polling (e.g)

http://192.168.1.2:3000/light/2c774a/status

just spins, no response.

**Comment by microbmen** [comment]
running - homebridge-platform-insteonlocal v0.5.5

**Comment by microbmen** [comment]
update: polling is working when the service does its configured polling interval.  Its just the REST API that isn't working...

**Comment by kuestess** [comment]
@microbmen Working for me - make sure you have `"use_express": true` in your config.

**Comment by microbmen** [comment]
Yup. That fixed it.   Thank you.  
Was that something in the readme documentation that I missed?
