### ISSUE TITLE
KeepAlive doesn’t seem to be working

### ISSUE THREAD

**Issue by ericboles** [kuestess/homebridge-platform-insteonlocal#286]
I’ve been running into an issue where my hub fails to maintain connection for more than a day or so…Restarting the hub and/or Homebridge brings everything back online for a while, and then the same issue in another day or so.

I’ve tried lowering the keepAlive value in hopes that would help.  Unfortunately, when looking at the homebridge logs, I show no evidence that keepAlive is resetting the connection.  In the past, I’ve noticed entries like below, but they do not show up at all my the log (standard or in debug mode):
```
Closing connection to Hub...
Reconnecting to Hub...
```

I’ve tried a variety of things to fix it including deactivating all other homebridge plugins, running Insteon as a child bridge within homebridge, and changing network settings on the Insteon hub.  Nothing has done the trick to bring keepAlive back.

Here’s a sample of my config file…again everything works fine while the connection is alive to the hub, but then fails eventually.  Maybe I have something set incorrectly in the config?

```
 "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "username",
            "pass": "password",
            "host": "10.0.1.42",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "1200",
            "devices": []
```

Thanks for the help and any insight.

**Comment by kuestess** [comment]
@ericboles That function seems to have inadvertently disappeared in the code transition to a dynamic platform :-(.  Let me add back in and push a fix soon.

**Comment by kuestess** [comment]
@ericboles Just published 0.5.7 which should fix this - let me know if you have issues.

**Comment by ericboles** [comment]
Thanks.  Looks like the keepAlive is working as expected now.

**Comment by isitmark27** [comment]
The latest version seems to stop after awhile. Wonder if keep alive is still active. Rolled back to previous and works fine.
