### ISSUE TITLE
Changing the status of a light

### ISSUE THREAD

**Issue by eytanschulman** [kuestess/homebridge-platform-insteonlocal#3]
Hello!

I am having an issue in which when I tap on the light to turn it on, this error gets thrown, and homebridge crashes.

```
Error setting level for Dining Room
/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /home/pi/Documents/homebridge-platform-insteonlocal/index.js:445:7
    at Request._callback (/home/pi/Documents/homebridge-platform-insteonlocal/index.js:362:4)
    at self.callback (/home/pi/Documents/homebridge-platform-insteonlocal/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.onRequestError (/home/pi/Documents/homebridge-platform-insteonlocal/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:160:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
```
Here is my config.json file:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "B8:27:EB:60:40:24",
    "port": 54491,
    "pin": "XXXXX"
  },
  "description": "YSJ Home",
"platforms": [
                                {
                                  "platform": "InsteonLocal",
                                  "name": "Insteon Local Platform",
                                  "user": "XXXXXX",
                                  "pass": "XXXXXX",
                                  "host": "192.168.1.9",
                                  "port": "25105",
                                  "model": "2245",
                                  "refresh":"300",
                                  "server_port": "3000",
                                  "devices": [
                                                                { "name": "Dining Room",
                                                                  "deviceID" : "XXXXXX",
                                                                  "dimmable" : "yes",
                                                                  "deviceType" : "lightbulb" }
                                        ]
                                }
                                ],

        "accessories": [

   ]
}
```

(Anything with XXXX was a value, replaced with XXXXX)

**Comment by kuestess** [comment]
@eytanschulman Sorry, I've got some issues with error handling that I need to fix as it shouldn't completely crash homebridge.  For your error above, I think its a connection issue to your Hub.  Try running homebridge and open 'http://<raspberrypi ip address>:3000/links' and see if you get a response.  If not, go into the Insteon app and try changing the Hub password.  I've found that the latest firmware update mangles the password without any indication in the Insteon app.  Changing it in the app usually fixes it.

**Comment by eytanschulman** [comment]
@kuestess Thanks, I am now away from the Homebridge that I am working to configure with your plugin, but have SSH access and am working on it remotely (with people at the place with the bridge.) I had the password changed, and with the new password I am getting connection refused on curl to localhost:3000/links , as well as "Connection refused" inside a CLI browser.

Separately, how would I go about updating homebridge-platform-insteonlocal, considering I installed via cloning? Would I have to delete the directory and reclone?

**Comment by kuestess** [comment]
@eytanschulman You should be able to update to the latest release by cd-ing into the cloned directory and typing `git pull`.  Sounds like you are still having connection issues.  In my previous reply, I assumed that you were using port 3000 (the default Express server port) - double check that in your config.json and also make sure that you don't have any other services running on that same port.  You may also want to make sure that your firewall isn't blocking connections on that port as well.

**Comment by eytanschulman** [comment]
@kuestess Thanks for the quick reply.

I just tried changing the port to something else, 3246, to no avail. When I try to curl http://localhost:3246/links , I get connection refused.

If it is any help, here are the first things that get printed when I launch Homebridge.

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-2-24 16:02:26] Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.2
[2018-2-24 16:02:26] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[2018-2-24 16:02:26] ---
[2018-2-24 16:02:26] Loaded config.json with 0 accessories and 1 platforms.
[2018-2-24 16:02:26] ---
[2018-2-24 16:02:26] Loading 1 platforms...
[2018-2-24 16:02:26] [Insteon Local Platform] Initializing InsteonLocal platform...
Found 1 devices in config
[2018-2-24 16:02:27] [Insteon Local Platform] Initializing platform accessory 'Dining Room'...
[2018-2-24 16:02:27] Loading 0 accessories...
```

**Comment by kuestess** [comment]
@eytanschulman Seems like its still not connecting to your Hub.  Do you ever get the 'Connected to Insteon Hub.  Server listening on port...' listed in the terminal when you launch homebridge?  You shouldn't be getting connection refused if you curl the link above.  Can you post your config.json?

**Comment by eytanschulman** [comment]
Connected to Insteon Hub or Server listening on port does not get listed. Are there any logs somewhere hidden I could see? Here's my config json. Will verify with my friend again as to if the host and port are still the same..

```
  "bridge": {
    "name": "Homebridge",
    "username": "B8:27:EB:60:40:24",
    "port": 54491,
    "pin": "XXXXXX"
  },
  "description": "YSJ Home",
"platforms": [
                                {
                                  "platform": "InsteonLocal",
                                  "name": "Insteon Local Platform",
                                  "user": "XXXXXX",
                                  "pass": "XXXXXX",
                                  "host": "192.168.1.9",
                                  "port": "25105",
                                  "model": "2245",
                                  "refresh":"300",
                                  "server_port": "3246",
                                  "devices": [
                                                                { "name": "Dining Room",
                                                                  "deviceID" : "44.EF.37",
                                                                  "dimmable" : "yes",
                                                                  "deviceType" : "lightbulb" }
                                        ]
                                }
                                ],

        "accessories": [

   ]
}
```

**Comment by kuestess** [comment]
@eytanschulman In your devices, remove the . in the deviceID (so there are no separators).  I don't *think* that would cause connection issues....but it will eventually keep the plugin from working.  Everything else looks fine - make sure to open the Insteon Hub app on your phone and go to Settings->House and verify that the local IP and port match.  I think you've changed the Hub password, but you might try changing the Hub username as well (not your Insteon user/pass - the user/pass for your Hub in the Insteon app).

**Comment by eytanschulman** [comment]
Just checked, IP and Port match. Is it the hub user/pass what is supposed to be in the config under user/pass?

**Comment by eytanschulman** [comment]
Got it set up and working with the proper user/pass, sorry for the troubles :-). A small suggestion: Change "username from Insteon app" and "password from Insteon app" to "username for the Insteon hub" and "password from Insteon hub"

Cheers!

**Comment by kuestess** [comment]
@eytanschulman Glad you got it to work.  Updated the readme to clarify which user/pass.
