### ISSUE TITLE
Target Keypad LED Function Broken?

### ISSUE THREAD

**Issue by THX723** [kuestess/homebridge-platform-insteonlocal#300]
Target Keypad LED is acting wonky with the latest v0.5.10 release.

My configuration has 2 or more targeted keypads defined. Only the 1st Keypad LED is being triggered, not the subsequent ones. Curiously the log is correctly showing all targeted keypads being triggered however.

When I rolled back to v0.5.8, everything is working as it should. I did not test v.0.5.9 btw.

**Comment by kuestess** [comment]
@THX723 I did have to touch some of that code in the latest update which might have introduced some unintended side effects.  The new i3 keypad is 4 buttons to go along with the existing 6 and 8 button configurations, so had to add some logic to look at the number of buttons specified in the config and choose a button map based upon that.  Let me take a look and see if I can figure out what's going on.

**Comment by THX723** [comment]
@kuestess Yup, I figured as much. Thanks.

**Comment by kuestess** [comment]
@THX723 It was a stupid copy/paste error.  0.5.11 should fix it.

**Comment by THX723** [comment]
> @THX723 It was a stupid copy/paste error. 0.5.11 should fix it.

Ha! Thanks for the fix.

**Comment by THX723** [comment]
Quick validation test passed with flying color. Thanks again @kuestess.
