### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by jayewyo** [kuestess/homebridge-platform-insteonlocal#319]
I am running this on hoobs and have not hand any issues for years until now. The log is showing a 401 error when trying to connect to my Insteon hub. I’ve checked the config, rebooted Insteon, hoobs and my WiFi router and it still will not connect to Insteon. Any ideas on what the issue could be?

**Comment by jayewyo** [comment]
Hoobs bridgeWARNINGunhandled rejection: Error: Status code expected 200, got 401

**Comment by kuestess** [comment]
@jayewyo Haven’t seen that one before.  Status code 401 means unauthorized - try changing the password to your hub in the Insteon app.  I have seen instances in the past where the password gets corrupted and even changing to the previous password fixes it.

**Comment by jayewyo** [comment]
Changing the password fixed it. Thanks for your help! Very weird it got corrupted after all this time.
