### ISSUE TITLE
Add method to invert garage door status

### ISSUE THREAD

**Issue by rcombs** [kuestess/homebridge-platform-insteonlocal#38]
I have my I/O Linc connected to the close-limit sensor on my garage door, so its states are "on" (fully closed) and "off" (at all open). It'd be nice to be able to tell homebridge that.

Not sure if there's something I could improve here just by re-linking; all-link is weird.

**Comment by kuestess** [comment]
@rcombs Just released 0.3.12 which allows you to invert the sensor in your config - details in the readme.  Let me know if you have any issues.

**Comment by rcombs** [comment]
Working great, thanks!

**Comment by rcombs** [comment]
Sorry, I said this was fine, but actually _controlling_ the garage door still needs to be inverted (right now only status is, so I have to double-press to control).

**Comment by kuestess** [comment]
@rcombs Does this happen only after manually controlling the door or even if it is only controlled from the Home app?

**Comment by kuestess** [comment]
@rcombs See if 0.3.13 fixes this for you.
