### ISSUE TITLE
not found npm

### ISSUE THREAD

**Issue by bljarisch** [kuestess/homebridge-platform-insteonlocal#4]
Getting this when trying to install

npm ERR! 404 Not Found: homebridge-platform-insteonlocal@latest

**Comment by kuestess** [comment]
I haven't (yet) published to npm.  In the meantime, to install you can either download or clone the repository, cd into the cloned directory and then type 'npm -g install'.  Working on getting this published to npm to make it easier.

**Comment by bljarisch** [comment]
Sorry I wrote that before I saw the other thread.  I cannot figure out how to do this.  I am running Homebridge in docker on a Synology NAS.  Any help would be appreciated.

**Comment by kuestess** [comment]
Should now be published to npm.  Try `npm -g install homebridge-platform-insteonlocal`.  Should work now.

**Comment by bljarisch** [comment]
That worked.  Thanks!

**Comment by bljarisch** [comment]
Crashes here:

[2018-4-21 17:43:53] [Insteon Local Platform] Insteon event listener started

/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:198
            if(use_express){
            ^
ReferenceError: use_express is not defined
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:198:13)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1185:10)

This is what I put in my config:

	{
		"platform": "InsteonLocal",
		"name": "Insteon Local Platform",
		"user": "un",
		"pass": "password",
		"host": "10.0.1.53",
		"port": "25105",
		"model": "2242",
		"refresh":"300",
		"use_express": "false",
		"server_port": "3000",
			"devices": [
					{ "name": "Garage Door 1",
					  "deviceID" : "420566",
					  "dimmable" : "no",
					  "deviceType" : "iolinc" }

**Comment by kuestess** [comment]
So I'm not sure how that one didn't come up in my testing :-), but I've just uploaded a fix that should address that error.

**Comment by bljarisch** [comment]
Awesome everything is working now!  Thank you so much for your help and your hard work on this!

**Comment by bljarisch** [comment]
The only issue I have now is scenes are not dimmable.

**Comment by kuestess** [comment]
Scene dimming isn't currently supported, per the readme.

**Comment by bljarisch** [comment]
Ah sorry, didn’t see that part.  Thanks.

**Comment by kuestess** [comment]
Closing as plugin now available in npm.
