### ISSUE TITLE
Not about Insteon local...

### ISSUE THREAD

**Issue by shereefalkady** [kuestess/homebridge-platform-insteonlocal#40]
@kuestess I have this device nexxgarage - very simple one button open/close garage opener ...
I need a homebridge for it — willing to pay for development - let me know if there is anything you can do

**Comment by kuestess** [comment]
@shereefalkady Let me see what I can find out about it.  If it has any other sort of integration it should be reasonably straightforward to build a plugin for.  You should have an IOLinc!

**Comment by shereefalkady** [comment]
The io links don’t work in my country - they work on only 60hz

**Comment by shereefalkady** [comment]
@kuestess any updates ... the Nexx garage already works with Alexa google and ifttt

**Comment by kuestess** [comment]
@shereefalkady Sorry for not getting back to you.  I did look into it and unfortunately I couldn't find much in the way of making this work with homebridge......yet.  Their Alexa / Google home implementations are closed, so I can't learn much from them.  It looks like they do intend to support Smartthings (maybe) this year which will be very helpful for integrating with homebridge.  An alternate route might be to use their web portal, assuming it exists.  I tried to find a place to create an account, but didn't find one - do they have a web portal, or just an app interface?

**Comment by shereefalkady** [comment]
@kuestess sadly just the app interface - they look like they are working on a homekit model - but i have been waiting forever... any way i can get homebridge and ifttt linked through any switch?

**Comment by kuestess** [comment]
@shereefalkady You could try [homebridge-ifttt](https://github.com/ilcato/homebridge-ifttt).  Looks like you add the maker channel in IFTTT and then  you could connect it to the Nexx Garage open/close actions.  Not sure what the response time will be though.  If you're familiar with Wireshark, you might be able to sniff out the calls that the app makes to their web service.

**Comment by allenlicn** [comment]
someone reversed engineered [Nexx Garage SDK](https://www.npmjs.com/package/nexx-garage-sdk). will that help with Nexx homebridge plugin development?

**Comment by rasod** [comment]
Looks promising albeit a little old, which model do you have?

**Comment by allenlicn** [comment]
i know. i only start to get into homebridge and begin to search a way to bring nexx to Home app. i have had an old Nexx garage opener for a while. it is the white NXG-100 model (not the newer black kind) with firmware 3.3.19. for some reason the device info shows the model as NGX-100 instead of NXG-100.
