### ISSUE TITLE
IOLink Not updating in homekit

### ISSUE THREAD

**Issue by moahman** [kuestess/homebridge-platform-insteonlocal#41]
Hello, I have two IOLinks in my garage, one named Big Garage and the other Small Garage. Big Garage operates just fine but small garage always says either Open or Closed never the right one. When it says its open and I open the garage it says open but when I close it, it still says open. If I open my Insteon app it shows the correct message either open or closed. Also this affects both garages (when small garage works), when I open a garage it will always say opening or closing until about an hour goes by then it shows the correct position.

**Comment by kuestess** [comment]
@moahman Can you post the config for your garage doors and the output from homebridge in debug mode (`homebridge -D`) when you have the issue?

**Comment by moahman** [comment]
Here is the config and in debug mode there is nothing that is off. I do see that it says Small Garage sensor is on. When i close the garage it does nothing, still says its open.
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:22",
		"pin": "123-45-678"
	},

	"platforms": [
				{
				  "platform": "InsteonLocal",
				  "name": "Insteon Local Platform",
				  "user": "",
				  "pass": "",
				  "host": "192.168.2.117",
				  "port": "25105",
				  "model": "2245",
				  "refresh":"300",
				  "server_port": "3000",
				  "keepAlive": "3600",
				  "devices": [
								{ 
									"name": "Big Garage",
								  	"deviceID" : "3D.E5.",
								  	"deviceType" : "iolinc",
									"gdo_delay": "30"
								},
								{
									"name": "Small Garage",
									"deviceID": "3D.E2.",
									"deviceType": "iolinc",
									"gdo_delay": "30"
								}		
            				]						
				},
				{
					"platform": "Nest",
					"clientId": "",
					"clientSecret": "",
					"code": "EK9PYDWD",
					"token":"",
					"disable":[
						"Thermostat.Fan","Thermostat.Home","Thermostat.Eco"
						]
				},
				{
					"platform": "Camera-ffmpeg",
						"cameras": [
						{
							"name": "Garage",
							"videoConfig": {
							"source": "-re -i rtsp://192.168.2.40:554/11",
							"maxStreams": 2,
							"maxBitrate": 3000,
							"maxWidth": 1920,
							"maxHeight": 1080,
							"maxFPS": 30
							}
						},
						{
							"name": "Drive Way",
							"videoConfig": {
							"source": "-re -i rtsp://192.168.2.42:554/11",
							"maxStreams": 2,
							"maxBitrate": 3000,
							"maxWidth": 1920,
							"maxHeight": 1080,
							"maxFPS": 30
							}
						}
					]
				}
				],
	
	"accessories": [

   ]

}

`

**Comment by moahman** [comment]
When I click to close the garage when its already closed it says Small Garage is already at commanded state

**Comment by kuestess** [comment]
@moahman Thanks - can you also provide the console output from debug mode? `homebridge -D`  It will be helpful in troubleshooting.  I assume that in your config you have all six characters for the device ID and only deleted the last two above for security.

**Comment by moahman** [comment]
@kuestess is there anyway to upload it without all the device ID's showing in the log or am I just going to have to deal with it?

**Comment by kuestess** [comment]
@moahman No built-in method to do that, but you could do a text search and replace with an editor.  Have you updated lately to see if that fixes your issue?

**Comment by moahman** [comment]
@kuestess Just did the update and so far it has been working as expected. Thank you for that!
