### ISSUE TITLE
Event Listener is not updating for blinds

### ISSUE THREAD

**Issue by gitraar** [kuestess/homebridge-platform-insteonlocal#43]
The Event Listener was not updating for my Insteon blinds (which I had set as blinds in the config in order for them to appear with the suitable icon and names in Home app) until I changed the eventListener function `InsteonLocalPlatform.prototype.eventListener = function ()`.

Where it had:
```
    case 'lightbulb':
    case 'dimmer':
    case 'switch':
```

I inserted a case for blinds, resulting in:
```
    case 'lightbulb':
    case 'blinds':
    case 'dimmer':
    case 'switch':
```

This makes the updates appear in the log file. However, they are still not reflected in the Home app. Since I have no experience in node, I don't know if other changes are needed somewhere else in the code.

**Comment by gitraar** [comment]
Got it to work (at least as far as I can tell), by adding the following code in the eventListener function:

```
          case 'blinds':
          if (command1 == "19" || command1 == "03" || command1 == "04" || command1 == "00" || (command1 == "06" && messageType == "1")) { //19 = status
            var level_int = parseInt(command2, 16) * (100 / 255)
            var level = Math.ceil(level_int)

            self.log('Got updated status for ' + foundDevice.name)

            foundDevice.service.getCharacteristic(Characteristic.TargetPosition).updateValue(level)
            foundDevice.level = level
            foundDevice.service.getCharacteristic(Characteristic.CurrentPosition).updateValue(level)
            foundDevice.service.getCharacteristic(Characteristic.PositionState).updateValue(level)
            foundDevice.lastUpdate = moment()
          }

          if (command1 == 18) { //18 = stop changing
            self.log('Got stop dimming event for ' + foundDevice.name);
            foundDevice.getStatus.call(foundDevice)
          }

          break
```

**Comment by kuestess** [comment]
@gitraar Sorry about that - an oversight when I added blinds to the plugin.  Just published a new version that adds it.  Implemented a little differently than above - the getPosition() function will take care of the lines above.
