### ISSUE TITLE
Insteon hub pro - error setting baud rate

### ISSUE THREAD

**Issue by dangerusty** [kuestess/homebridge-platform-insteonlocal#45]
```
debian@beaglebone:~$ journalctl -u homebridge -b | grep serialport
Dec 06 04:16:46 beaglebone homebridge[509]: 2018-12-06T04:16:46.659Z serialport:binding:auto-detect loading LinuxBinding
Dec 06 04:16:50 beaglebone homebridge[509]: 2018-12-06T04:16:50.117Z serialport:main opening path: /dev/ttyS4
Dec 06 04:16:50 beaglebone homebridge[509]: 2018-12-06T04:16:50.126Z serialport:bindings open
Dec 06 04:16:51 beaglebone homebridge[509]: 2018-12-06T04:16:51.673Z serialport:main _read queueing _read for after open
Dec 06 04:16:52 beaglebone homebridge[509]: 2018-12-06T04:16:52.102Z serialport:main Binding #open had an error Error: Error: Input/output error setting custom baud rate of 19200
```

**Comment by dangerusty** [comment]
First time setup on the hub pro. Followed instructions and get this every time. Insteon devices don’t respond.

**Comment by dangerusty** [comment]
Doesn't look like my serial port 4 is accessible:

`debian@beaglebone:/boot$ sudo cat /proc/tty/driver/serial
serinfo:1.0 driver revision:
0: uart:8250 mmio:0x44E09000 irq:30 tx:221 rx:0 RTS|CTS|DTR|DSR
1: uart:unknown port:00000000 irq:0
2: uart:unknown port:00000000 irq:0
3: uart:unknown port:00000000 irq:0
4: uart:unknown port:00000000 irq:0
5: uart:unknown port:00000000 irq:0
debian@beaglebone:/boot$ dmesg | grep tty
[    0.000000] Kernel command line: console=ttyO0,115200n8 bone_capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIone_capemgr.enable_partno=BB-UART1,BB-UART2,BB-UART4,BB-UART5 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait fixrtcherent_pool=1M net.ifnames=0 quiet
[    0.001011] WARNING: Your 'console=ttyO0' has been replaced by 'ttyS0'
[    1.049336] 44e09000.serial: ttyS0 at MMIO 0x44e09000 (irq = 30, base_baud = 3000000) is a 8250
[    1.061210] console [ttyS0] enabled
[    8.854530] systemd[1]: Created slice system-getty.slice.
`

**Comment by rasod** [comment]
Usually if the serial port 4 is not accessible that means the changes to the /boot/uEnv.txt file weren't picked up. You should see the following in /dev

![screen shot 2018-12-06 at 11 38 30 am](https://user-images.githubusercontent.com/7154349/49598120-fbf80900-f94b-11e8-8f30-24908881db62.png)

Are you booting with the S2 button held down or flashing the SD card to the board?

**Comment by dangerusty** [comment]
My mistake, I did make the changes in uEnv.txt but didn't boot with holding S2 after the first boot. Serial ports now look good, but homebridge is stopping shortly after starting with this error:

```
Dec 06 10:51:23 beaglebone homebridge[2106]: 2018-12-06T16:51:23.913Z serialport:main _read reading
Dec 06 10:51:23 beaglebone homebridge[2106]: 2018-12-06T16:51:23.922Z serialport:bindings read
Dec 06 10:51:23 beaglebone homebridge[2106]: 2018-12-06T16:51:23.934Z serialport:unixRead Starting read
Dec 06 10:51:23 beaglebone homebridge[2106]: events.js:160
Dec 06 10:51:23 beaglebone homebridge[2106]:       throw er; // Unhandled 'error' event
Dec 06 10:51:24 beaglebone systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 10:51:24 beaglebone systemd[1]: homebridge.service: Unit entered failed state.
Dec 06 10:51:24 beaglebone systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by rasod** [comment]
If you are using a different user to run homebridge you need add them to the dialout group so they can access the port.

For user “homebridge”:
sudo usermod -a -G dialout homebridge

**Comment by dangerusty** [comment]
I've already done that as part of my serial port troubleshooting:

```
debian@beaglebone:~$ groups homebridge
homebridge : homebridge tty dialout
```

**Comment by dangerusty** [comment]
I wasn't getting enough debug info from the journalctl output, ran homebridge from command line and got more hints:

```
[12/6/2018, 1:41:04 PM] [Insteon Local Platform] Started Insteon Express server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1271:14)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at EventEmitter.listen (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/application.js:618:24)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:363:10
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:142:32)
    at emitNone (events.js:91:20)
    at SerialPort.emit (events.js:185:7)
```

I tried launching with use_express: false and its up and running!
