### ISSUE TITLE
Insteon Smoke Bridge Support?

### ISSUE THREAD

**Issue by ericboles** [kuestess/homebridge-platform-insteonlocal#48]
This plugin works great--much thanks to @kuestess for all the hard work.  Running on a Pi3, this makes Insteon more reliable than most of my native HomeKit devices...

Looking through the config options and code, it doesn't seem like the plugin currently supports the Insteon Smoke Bridge.  Wondering if anyone else has gotten it to work or if I could help in testing to add support.

Thanks.

**Comment by kuestess** [comment]
@ericboles Looks like homekit offers a smoke and CO detector which the smoke bridge seems to support.  Should be somewhat straightforward to add.  May take a bit for me to get to it, but I'll see if I can add with the next release.  I don't have one, so would appreciate any testing you can do!

**Comment by ericboles** [comment]
Excellent!  I'll be happy to test--just let me know when you're ready to get started with it.

**Comment by kuestess** [comment]
@ericboles Just published a version to npm with initial support for the smoke bridge.  Just specify your device type as 'smoke' and it should create a smoke sensor and CO sensor.  Let me know if you have any issues.

**Comment by ericboles** [comment]
@kuestess Alas...I had ordered a smoke bridge, but then ran into issues with it being poorly supported by First Alert--very difficult to tell which smoke alarms are now compatible.  Seems like something they were actively supporting years ago, but have since focused on native HomeKit smoke alarms (and even repurposed their "Onelink" brand name from the Insteon-compatible versions to their current HomeKit line).  Bottom line, it unfortunately means I don't have the parts to test effectively.   If there's someone out there that does, please shout out.  (And if they have details on compatible wired-in compatible smoke + CO alarms, I'd love to hear it!)

**Comment by kuestess** [comment]
Looking for testers for smoke bridge functionality, closing for now.
