### ISSUE TITLE
Siri sends ON command with 0% as value when using voice commands

### ISSUE THREAD

**Issue by ckellar33** [kuestess/homebridge-platform-insteonlocal#49]
When using Siri to turn on an Insteon dimmer switch the command shows up in Homekit as ON with 0%. If I specifically ask Siri to turn ON to 100% then all works as intended. Is there a possible fix for this? Thanks for all you do.

**Comment by kuestess** [comment]
@ckellar33 See [#47](https://github.com/kuestess/homebridge-platform-insteonlocal/issues/47)
