### ISSUE TITLE
Half-broken support for lowercase IDs in config file

### ISSUE THREAD

**Issue by rcombs** [kuestess/homebridge-platform-insteonlocal#50]
Looks like the primary issue here is this needing a `.toUpperCase()`: https://github.com/kuestess/homebridge-platform-insteonlocal/blob/131495edead5d8953a934234cb8f7ada00f3e079/index.js#L284

**Comment by kuestess** [comment]
@rcombs Can you provide more background on the issue?

**Comment by rcombs** [comment]
With the current code, if you have a lowercase ID in your config file, incoming events from that device won't be handled (e.g. turning off a light manually won't show up in HomeKit).

**Comment by kuestess** [comment]
@rcombs Thanks.  Easy fix - will take a look at it.

**Comment by kuestess** [comment]
Done.  Published a fix to npm that should take care of this.
