### ISSUE TITLE
Adding Insteon Scene to HomeKit  without Keypad?

### ISSUE THREAD

**Issue by ericboles** [kuestess/homebridge-platform-insteonlocal#53]
I might be missing some configuration details, but I’m trying to add an Insteon scene without a keypad...essentially having that scene show up within HomeKit as an on/off switch so it can be triggered within HomeKit manually or via automation. I’ve been able to set up scenes when tied to a keypadlinc, but the config seems to require a device id...which wouldn’t apply to a standalone scene not triggered by a keypad. 

Reason for the request...When controlling multiple Insteon devices, using an Insteon scene directly is preferable to creating a HomeKit scene.  An Insteon scene triggers the devices simultaneously, whereas a HomeKit scene controlling multiple Insteon devices seems to hit each device one-by-one.

I feel like I’m missing something basic because the scenes seem so easy to trigger with the Express server. Appreciate any guidance/insight.

**Comment by kuestess** [comment]
@ericboles You can leave out the `deviceID` field and just populate the `groupID` to trigger a scene using the same underlying method that the express server uses.  let me know if you have problems with that.

**Comment by ericboles** [comment]
Thanks, @kuestess.  Unfortunately, that doesn't seem to work ( running homebridge-platform-insteonlocal v0.3.15).  When I add the scene without a deviceID, I get an error with Homebridge and it fails to load.  Here's what is added to config.json (I've tried with groupID with and without quotes):

`   {
"name": "Downstairs All",
"groupID": "15",
"deviceType": "scene"
}`

And here is the error during loading:

`/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1882
    self.id = device.deviceID.toUpperCase()
                              ^
TypeError: Cannot read property 'toUpperCase' of undefined
    at InsteonLocalAccessory.init (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1882:31)
    at new InsteonLocalAccessory (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1869:15)
    at /homebridge/node_modules/homebridge-platform-insteonlocal/index.js:724:25
    at Array.forEach (<anonymous>)
    at InsteonLocalPlatform.accessories (/homebridge/node_modules/homebridge-platform-insteonlocal/index.js:723:18)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)`

**Comment by kuestess** [comment]
@ericboles Sorry, looks like I introduced a bug with a recent change.  Should be a quick fix - will try to push this evening.

**Comment by ericboles** [comment]
No worries at all. Thanks for the great work on this plugin...  It really is spectacular, as is your support of it.

**Comment by kuestess** [comment]
@ericboles You're too kind :-)  Just pushed an update to npm that should fix this.  Looks like it was introduced a while back so I'm surprised it took this long to catch.

**Comment by ericboles** [comment]
@kuestess Works like a charm!  Thanks for the quick fix.
