### ISSUE TITLE
Seeing messages such as "[2/17/2019, 8:35:53 PM] [InsteonLocal] Setting level of LR Lamp to undefined%"

### ISSUE THREAD

**Issue by ctgreybeard** [kuestess/homebridge-platform-insteonlocal#56]
Since I now have Homebridge working I have gone farther and set up most of my devices. I can control on and off but am having trouble with brightness. I get the above message all or nearly all of the time that I try to adjust brightness.

The config for this particular one is:
```
            {
              "controllers" : [ "13ADEA" ],
              "deviceID" : "265851",
              "deviceType" : "lightbulb",
              "dimmable" : "yes",
              "name" : "LR Lamp"
            },
```

but others are doing the same.

**Comment by ctgreybeard** [comment]
Digging ...

in `InsteonLocalAccessory.prototype.setBrightnessLevel = function(level, callback)`
In:
```
                if(level === true){
                        var theLevel = 100
                } else if(level === false){
                        var theLevel = 0
                }

        self.levelTimeout = setTimeout(function(){
                        setLevel.call(self,theLevel, function(){
                                self.levelOne = ''
                                callback
                        })
        }, debounceTimer + 100)
```

`theLevel` is never set to a value if the requested level is neither `true` nor `false`.

**Comment by kuestess** [comment]
@ctgreybeard Good catch!  Just pushed a fix to github/npm.

**Comment by ctgreybeard** [comment]
As I am new to npm, what's the correct way to pick up the change? I installed originally using npm although I may switch to a github clone later.

**Comment by kuestess** [comment]
`npm -g install homebridge-platform-insteonlocal`  Makes it really easy.

**Comment by ctgreybeard** [comment]
I did an `sudo npm -g update` It took a while but the update was picked up. It's all working for me now.
