### ISSUE TITLE
Hub Pro 2243 Question 

### ISSUE THREAD

**Issue by 64Spaces** [kuestess/homebridge-platform-insteonlocal#63]
When power cycling the Hub 2243, does the S2 Boot button have to be held down each time? Or should the setup survive a power cycle?

**Comment by ctgreybeard** [comment]
I'd like to hear other opinions on this too. In my experience using S2 once seems to allow not using it later. I can rebbot my 2243 remotely now without getting near S2 and it's working fine. I did, I believe, need to use it once to get the uEnv.txt to be effective. It would be nice to heard from a BeagleBone "expert" about this as all of the documentation I can find is very old.

**Comment by kuestess** [comment]
@64Spaces I don't use my 2243 enough to know whether it makes a difference.  I believe the current thought is that you need to hold down S2 on each reboot or you get some wonkiness in the hub.  Paging @rasod who is the expert with the Hub Pro.

**Comment by rasod** [comment]
For me I flashed the SD card to the eMMC which wipes the factory code completely. I have to check my notes to see how I did that. I think there was a line at the bottom of the uEnv.txt that you could uncomment to flash the SD to the eMMC.

**Comment by 64Spaces** [comment]
Thank you. It seems that reboot maintains the network connection. But a power cycle causes it to loose its network connection and need the S2 reboot to recover.

**Comment by 64Spaces** [comment]
Thank you. Once it's flashed to eMMC, can you still SSH into it and configure/update the config.json file? And can additional Homebridge plugins (like PM2 to auto-start Homebridge) be added?

**Comment by rasod** [comment]
I think I followed these instructions https://stackoverflow.com/a/40180517 basically edit the uEnv.txt file reboot and wait fo it to flash the memory. After that  remove the SD card then you have flashed Hub Pro. Caution there is no going back!

Sorry it was a while ago when I did it all, took horrible notes. Since then all my homebridge plugins run off the flashed HubPro.

**Comment by shereefalkady** [comment]
@ctgreybeard @kuestess @rasod
I only used the s2 once to initially boot ... then it works automatically every time therafeter ...

But @kuestess am I doing something wrong ? The 2243 is significantly slower than the 2245...
What is the setup supposed to look like ? For host user and pass?

**Comment by 64Spaces** [comment]
Beautiful, I was able to flash the memory and it boots properly after a power cycle. Thank you. However, I quickly ran into "not enough space" when adding Homebridge and Insteonlocal. I'm not a power user. Is there a way to either free up flash memory or use an inserted microSD card for the space?

@shereefalkady, when you turn power off and then back on, does you network connection and setup appear again without touching it?

Here is a config.json that works for me:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "XX:XX:XX:XX:XX:XX",
		"pin": "123-45-678"
	},

	"platforms": [

				{
				  "platform": "InsteonLocal",
				  "name": "Insteon Local Platform",
				  "host": "10.0.0.101",
				  "model": "2243",
				  "use_express": false,
				  "devices": [
						{	"name" : "Porch",
						  	"deviceID" : "XX.XX.XX",
						  	"dimmable" : "yes",
						  	"deviceType" : "dimmer"
						 },
						{	"name" : "Lamp",
						  	"deviceID" : "XX.XX.XX",
						  	"dimmable" : "yes",
						  	"deviceType" : "dimmer"
						 }
							
            				]
				}
			],
	
	"accessories": [
			

   ]

}`

**Comment by rasod** [comment]
@shereefalkady usually once you pull power the Hub will boot using the default uEnv settings. It will still boot off the SD and homebridge will be available however the serial port will be disabled and the plugin will not work. That is why you need to hold S2 on boot. However once booted you can use the reboot command and the settings will remain but if power is cycled they are reset. This is all in my experience there may be another way to have the booting work.

Technically the host/user/pass are not needed since the plugin is talking directly to the Insteon PLM that is inside box.

When you say “slower” what do you mean? For me I run two dozen Insteon devices from the Hub (inculding all the other homebridge plugins running alongside there are 50) and I wouldn’t call it slow.

Controlling one device is instantaneous. When controlling multiple devices like with a HK scene there is a delay between each device but that just a limitation of how the Insteon protocol works. For example I have one automation that will turn on/off the bedroom nightstand lights when the bedroom ceiling light is turning on. The ceiling light is an Insteon FanLinc the nightstands are Hue bulbs, and it is instant.

**Comment by 64Spaces** [comment]
@rasod , Thank you. My original desire was to find out if homebridge and insteonlocal would automatically be available after a power failure. My thought is that if I am not home and the power to the house goes out for whatever reason, I would like the hub come back on and work without having to hold S2 to reboot. I will do some more experimenting.

**Comment by rasod** [comment]
@64Spaces once flashed it should reboot after a power failure and come back up and work - you will need something to startup homebridge like PM2 or systemd but that's it. That is how mine works. I have had it running for over a year like this.

One gotcha is to make sure whatever user is running homebridge has access to the serial port. For example if you create a "homebridge" user to give it access to the port.

```
For user “homebridge”:
sudo usermod -a -G dialout homebridge
```

Also after flashing make sure to remove the SD card. I had mine boot up off that months after I flashed it. It was so confusing cause my config was months old.

**Comment by 64Spaces** [comment]
@rasod , thank you. That sounds like what I am looking for. Are you loading homebridge and the plug-ins on the eMMC memory? How did you get it to fit? I get the "not enough space" error.

**Comment by rasod** [comment]
I didn't have any problems like that, I used the IoT image.

**Comment by 64Spaces** [comment]
Thank you @rasod.  I must be missing a step. I'm using Debian 9.4 IoT (with flasher enabled) to flash it and reboot with no SD card. I edit the flashed /boot/uEnv.txt file,  reboot, install homebridge. Homebridge will run. Then I add insteonlocal. Then when running homebridge command again, it says "not enough space" and will not run. Any suggestions? Thanks so much for your help.

df shows of eMMC:

`Filesystem     1K-blocks    Used Available Use% Mounted on
udev              220444       0    220444   0% /dev
tmpfs              49504    4780     44724  10% /run
/dev/mmcblk1p1   1809656 1614288     85392  95% /
tmpfs             247500       0    247500   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             247500       0    247500   0% /sys/fs/cgroup
tmpfs              49500       0     49500   0% /run/user/1000`

**Comment by rasod** [comment]
hmm, mine shows

```
debian@beaglebone:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            215M     0  215M   0% /dev
tmpfs            49M  8.9M   40M  19% /run
/dev/mmcblk1p1  3.5G  2.4G  945M  72% /
tmpfs           243M     0  243M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           243M     0  243M   0% /sys/fs/cgroup
tmpfs            49M     0   49M   0% /run/user/1000
```

What size SD card did you use? You might need to expand the filesystem. You can try:

```
cd /opt/scripts/tools
./grow_partition.sh
```

I didn't have to do that so if it works please report back the new size.

**Comment by 64Spaces** [comment]
Very strange. My board only show 2GB
Old situation:

``
Device         Boot Start     End Sectors  Size Id Type
/dev/mmcblk1p1 *     8192 3751935 3743744  1.8G 83 Linux

>>> Created a new DOS disklabel with disk identifier 0xde1177fb.
/dev/mmcblk1p1: Created a new partition 1 of type 'Linux' and of size 1.8 GiB.
Partition #1 contains a ext4 signature.
/dev/mmcblk1p2: Done.

New situation:

Device         Boot Start     End Sectors  Size Id Type
/dev/mmcblk1p1 *     8192 3751935 3743744  1.8G 83 Linux

The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Device or resource busy
The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
Syncing disks.
reboot
``

**Comment by 64Spaces** [comment]
Lightbulb! It turns out the Hub I'm flashing is a Hub Pro V2. I have another one that is a Hub Pro V5. I'm going to try the V5.

**Comment by 64Spaces** [comment]
That was it. Apparently the Hub Pro V2 only has 2GB onboard. I flashed the Hub Pro V5 and edited the uEnv.txt file on the board. Mission accomplished, the plugin and serial port now survive a power cycle. And there is room for more plugins. Many thanks to @rasod. I will close this issue.

**Comment by ctgreybeard** [comment]
@64Spaces Your post prompted me to check my own Hub Pro which I purchased very recently and I find it also has a 2GB eMMC. Did Smarthome sell me an old version? Where did you get the V5 that you have?

**Comment by 64Spaces** [comment]
Thank you @kuestess for this plugin. I got them both on ebay. The version 2 ($25) was being sold by someone who has a bunch to sell (As-Is) and the version 5 ($50) was from an individual. And Smarthome ($149) is still selling them.

**Comment by ctgreybeard** [comment]
Yes, Smarthome IS selling 2243-222's but the one I received is a V2! I have written them to ask why and to request a replacement.

**Comment by bls8486** [comment]
How can you tell a v2 from a v5?

**Comment by Calorion** [comment]
Here's a related question: Is there a way to reboot it without unplugging it and plugging it back in?
