### ISSUE TITLE
Insteon Outlet Module 2635-222 - State/status is incorrect

### ISSUE THREAD

**Issue by NorthernMan54** [kuestess/homebridge-platform-insteonlocal#66]
When I use the Insteon Outlet Module 2635-222 configured as an outlet, the state is incorrect.  During homebridge startup if the module is off, HomeKit reports it as on.  Also when using the local control on the module the state would not update in HomeKit correctly.

Config.json fragment

```
{
      "name": "Test Module",
      "deviceID": "320BD1",
      "dimmable": "no",
      "deviceType": "outlet"
    }
```

I switched the deviceType to be a switch and it was fine afterwards

I'm not sure if this is an issue, or just something for other users to be aware of.

PS Great plugin, really impressed with your real-time updates into HomeKit.

**Comment by kuestess** [comment]
@NorthernMan54 Thanks!  Really digging your node-red plugin - always wanted to build something like that for all of my home automation gear.  Switch is the correct device type for the 2635-222.  The outlet device type is intended for the 2663-22 wired-in outlet.

**Comment by NorthernMan54** [comment]
Tks, will close this

Hope you enjoy the node-red plugin, I'm just starting to play with the power of it, and so far have been amazed with the automations I have been able to create.  My main one so far has been the ability to resume status after an On/Off event.  That scored a lot of WAF points for my, as previously we had been left literally in the dark.
