### ISSUE TITLE
Getting fs.Type Error when clicking on get device info

### ISSUE THREAD

**Issue by thehigherlife** [kuestess/homebridge-platform-insteonlocal#69]
I'm getting this error when i click on the "get hub info"  home bridge crashes as well.

: Getting Hub info
Jun 01 18:23:09 homebridge homebridge[3551]: { raw: '026050B75C0333A4',
Jun 01 18:23:09 homebridge homebridge[3551]: type: '60',
Jun 01 18:23:09 homebridge homebridge[3551]: id: '50B75C',
Jun 01 18:23:09 homebridge homebridge[3551]: deviceCategory: { id: 3, name: 'Network Bridges' },
Jun 01 18:23:09 homebridge homebridge[3551]: deviceSubcategory: { id: 51 },
Jun 01 18:23:09 homebridge homebridge[3551]: firmwareVersion: 'A4' }
Jun 01 18:23:09 homebridge homebridge[3551]: [6/1/2019, 6:23:09 PM] TypeError: fs.copyFile is not a function
Jun 01 18:23:09 homebridge homebridge[3551]: at InsteonUI.saveInsteonConfig (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2015:5)
Jun 01 18:23:09 homebridge homebridge[3551]: at /usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1598:11
Jun 01 18:23:09 homebridge homebridge[3551]: at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
Jun 01 18:23:09 homebridge homebridge[3551]: at runSingle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
Jun 01 18:23:09 homebridge homebridge[3551]: at flush (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
Jun 01 18:23:09 homebridge homebridge[3551]: at _combinedTickCallback (internal/process/next_tick.js:73:7)
Jun 01 18:23:09 homebridge homebridge[3551]: at process._tickCallback (internal/process/next_tick.js:104:9)
Jun 01 18:23:09 homebridge homebridge[3551]: [6/1/2019, 6:23:09 PM] Got SIGTERM, shutting down Homebridge...
Jun 01 18:23:14 homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
Jun 01 18:23:14 homebridge systemd[1]: Unit homebridge.service entered failed state.

**Comment by kuestess** [comment]
@thehigherlife Which version of node are you running?  copyFile was only available starting with 8.50.

**Comment by thehigherlife** [comment]
updating to a later version of node fixed it.  thank you,.
