### ISSUE TITLE
Insteon Scenes

### ISSUE THREAD

**Issue by MajdiElSadek** [kuestess/homebridge-platform-insteonlocal#7]
Hello, 

I just added scenes as described in readme for 0.3.2. But the scenes are appearing as devices in the home app. The scenes work as expected with App but makes it little tricky when activating through Siri since she doesn't recognize them as scans. 

would appreciate your help. Thanks. 
[config.json.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/1998946/config.json.txt)

**Comment by kuestess** [comment]
@MajdiElSadek What you describe above is the intended result - the plugin will import your Insteon scenes as devices.  To my knowledge, it isn't currently possible to create scenes via homebridge.  As a workaround, you could create a scene in the Home app and add the scene device to it.  I don't personally use homekit scenes with Siri, but I think that should work.
