### ISSUE TITLE
Dimming lights crashes Homebridge

### ISSUE THREAD

**Issue by bljarisch** [kuestess/homebridge-platform-insteonlocal#70]
My Insteon Hub pro finally died, so now I am adding all of my Insteon devices to my old hub and setting up in home bridge.  So far I have 2 dimmer switches, on and off works fine, however, when I dim in the home app I get this error in the Homebridge log:

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1011:5
    at /homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1079:5
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2059:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

***This is what I have in config file for this particular dimmer switch:

"name": "Fan Light",
"deviceID": "45a143",
"dimmable": "yes",
"deviceType": "dimmer"

Any help is appreciated.  Thanks!

**Comment by kuestess** [comment]
@bljarisch I think I've got an extra callback in there.  Should be an easy fix - let me take a look.  Hopefully have a fix shortly.

**Comment by bljarisch** [comment]
Sounds good thanks!

**Comment by kuestess** [comment]
@bljarisch Just pushed a fix - see if that works for you.

**Comment by bljarisch** [comment]
I use homebridge-config-ui to install updates.  I am running home bridge in docker on a Synology NAS.  I am not seeing your update.  Let me see if I can try a different way.

**Comment by kuestess** [comment]
@bljarisch If you can get to a terminal prompt within the container, you can upgrade via `npm -g install homebridge-platform-insteonlocal`

**Comment by bljarisch** [comment]
So that method doesn’t work with this container.  Instead I added “*” to the package.json and it is supposed to download the latest version of a platform when the container is restarted.  Currently says version 0.4.1.   Still having same issue.

**Comment by bljarisch** [comment]
Ok never mind I got it by uninstalling and reinstalling via the UI.  I will do some testing.   So far working ok.

**Comment by bljarisch** [comment]
ok after some testing, when I dim lights Homebridge seems to freeze.  No errors in logs.  Also my garage now says not responding.  Should I switch to a newer hub?  Currently using a 2242.  Should I do something with refresh and keep alive?  Here is my config:

{
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "bjar",
            "pass": "Gibson31",
            "host": "10.0.1.53",
            "port": "25105",
            "model": "2242",
            "refresh": "0",
            "keepAlive": "0",
            "use_express": "true",
            "server_port": "3000",
            "devices": [
                {
                    "name": "Garage Door 1",
                    "deviceID": "420566",
                    "dimmable": "yes",
                    "deviceType": "iolinc"
                },
                {
                    "name": "Front Door Motion",
                    "deviceID": "319097",
                    "dimmable": "yes",
                    "deviceType": "motionsensor"
                },
                {
                    "name": "Garage Door 2",
                    "deviceID": "395FB7",
                    "dimmable": "yes",
                    "deviceType": "iolinc"
                },
                {
                    "name": "Master BR Fan High",
                    "deviceID": "3B906B",
                    "dimmable": "yes",
                    "groupID": "22",
                    "keypadbtn": "A",
                    "six_btn": "true",
                    "deviceType": "scene"
                },
                {
                    "name": "Front Light",
                    "deviceID": "3C3CA9",
                    "dimmable": "no",
                    "groupID": "32",
                    "keypadbtn": "F",
                    "six_btn": "false",
                    "deviceType": "scene"
                },
                {
                    "name": "Stairs Light",
                    "deviceID": "41e6ce",
                    "dimmable": "yes",
                    "groupID": "21",
                    "keypadbtn": "A",
                    "six_btn": "true",
                    "deviceType": "scene"
                },
                {
                    "name": "Dining Light",
                    "deviceID": "3c759d",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Front Porch Light",
                    "deviceID": "3bde8d",
                    "dimmable": "no",
                    "deviceType": "switch",
                    "controllers": "319097"
                },
                {
                    "name": "Luke Light",
                    "deviceID": "42cb71",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Luke Fan",
                    "deviceID": "425413",
                    "dimmable": "no",
                    "deviceType": "switch"
                },
                {
                    "name": "Garage Entry Light",
                    "deviceID": "3c3ca9",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Formal Living Lamps",
                    "deviceID": "39a691",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Master BR Light",
                    "deviceID": "3b906b",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Recessed Lights",
                    "deviceID": "388c98",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Fan Light",
                    "deviceID": "45a143",
                    "deviceType": "dimmer",
                    "dimmable": "yes"
                }

**Comment by bljarisch** [comment]
The issue seems to only be with lights.  I have loaded home bridge on a Mac mini I have, set up a new 2245 hub, added 1 light switch dimmer only, and I am still getting this:
[6/29/2019, 3:10:42 PM] [Insteon Local Platform] Setting level of Recessed Lights to 100%
[6/29/2019, 3:10:52 PM] [Insteon Local Platform] Error setting level of Recessed Lights
[6/29/2019, 3:10:52 PM] [Insteon Local Platform] Getting status for Recessed Lights
[6/29/2019, 3:11:02 PM] [Insteon Local Platform] Error getting power state of Recessed Lights

**Comment by kuestess** [comment]
@bljarisch Sorry for the delay - it looks like there may be something in the response from your hub that prevents the status update.  Can you run homebridge in debug mode (`homebridge -D`) and post the output?  Thanks!

**Comment by bljarisch** [comment]
No problem at all!  OK, I went to home app and slid the dimmer for the dining room light down to 27%. This is the output in Homebridge in debug mode:

[7/10/2019, 10:11:38 PM] [Insteon Local Platform] Setting level of Dining Room Light to 78%
[7/10/2019, 10:11:39 PM] [Insteon Local Platform] Dining Room Light is on at 78%

It froze at 78%.  In the home app, then dining light had a spinning thing in the upper right corner for about 1 min then went to "no response".  Even with no response I opened up the dimmer control, it said 100%, so I slid it down again and got another output in home bridge:

[7/10/2019, 10:14:36 PM] [Insteon Local Platform] Setting level of Dining Room Light to 72%
[7/10/2019, 10:14:36 PM] [Insteon Local Platform] Dining Room Light is on at 72%

homebridge says 72%, but now home app says 78%.

3rd time, dimmed light down to 32%, light first got brighter then dimmed all the way to 32% and the "no response" went away in home app.  This is the output immediately after setting to 32%:

[7/10/2019, 10:16:04 PM] [Insteon Local Platform] Setting level of Dining Room Light to 56%
[7/10/2019, 10:16:04 PM] [Insteon Local Platform] Setting level of Dining Room Light to 100%
[7/10/2019, 10:16:04 PM] [Insteon Local Platform] Dining Room Light is on at 56%
[7/10/2019, 10:16:04 PM] [Insteon Local Platform] Dining Room Light is on at 100%
[7/10/2019, 10:16:05 PM] [Insteon Local Platform] Setting level of Dining Room Light to 33%
[7/10/2019, 10:16:05 PM] [Insteon Local Platform] Dining Room Light is on at 33%
[7/10/2019, 10:16:06 PM] [Insteon Local Platform] Setting level of Dining Room Light to 32%
[7/10/2019, 10:16:06 PM] [Insteon Local Platform] Dining Room Light is on at 32%

Seems to just be a dimming issue, If I set dimmable "no" and device type "switch" then it works flawlessly as an on/off switch.  But I would like to have the dimming work.  Note: I went back to the 2242 and running homebridge in docker on a Synology NAS because my 2245 died (my 3rd Insteon Hub to die) and Mac mini would not keep homebridge running for very long.  Thank you for looking into this!

**Comment by kuestess** [comment]
@bljarisch This is probably related to the way that the Home app sends dimming commands and my attempts to 'debounce' them.  When dimming, the Home app continuously sends on and level commands as you move the slider rather than just waiting until you're done and only sending the last level.  I added some code to attempt to figure out when dimming is done and when to send the command, although it has tradeoffs in responsiveness.  I threw that code together fairly quickly, and there's probably a better way to do it, so let me take a look at it.  One thing you can try in the meantime is using a different homekit app.  Most of them wait until dimming stops before sending the command which creates a much better experience.

**Comment by bljarisch** [comment]
I really like the home app, but I’ll check some of the others out. I can keep using it the way I have it set up for now.  Take your time!  You have exceeded my expectations with this plugin, and your customer service!

**Comment by kuestess** [comment]
@bljarisch I just pushed 0.4.2 with rewritten, simpler dimmer debounce code that I think will solve your issues.  Give it a try and see if that works.

**Comment by bljarisch** [comment]
Seems to be working so far!   Thank you!!!

**Comment by kuestess** [comment]
Fixed with 0.4.2 - feel free to reopen if still an issue.
