### ISSUE TITLE
deviceType dimmer should default to dimmable 

### ISSUE THREAD

**Issue by natefanaro** [kuestess/homebridge-platform-insteonlocal#76]
I feel like if a device is defined as a dimmer then dimmable should default to true. 

Should probably be handled around `InsteonLocalAccessory.prototype.init` here

https://github.com/kuestess/homebridge-platform-insteonlocal/blob/a886419c374bd30c5f4e6a13d77279f089267b7a/index.js#L1943

This would help make configuring devices a little easier. Haven't tried fixing it locally yet but I can make a PR a little later for this.

**Comment by kuestess** [comment]
@natefanaro Implemented in 0.4.12.
