### ISSUE TITLE
NPM is not Finding the new 0.4.5-1 Version, You need to Increase the Minor Version

### ISSUE THREAD

**Issue by mkellsy** [kuestess/homebridge-platform-insteonlocal#82]
I have a user that is trying to install the new version 0.4.5-1, the -1 is throwing off NPM. It needs to be released as 0.4.6 or 0.4.6-beta.1. Then when you are out of beta the version needs to be 0.4.7.

NPM reserves the - for betas, and requires a minor version increase.

**Comment by mkellsy** [comment]
The user should be able to use this @0.4.5-1, but the @latest version points to 0.4.5.

**Comment by BlueiPhone** [comment]
[Homekit with Insteon.docx](https://github.com/kuestess/homebridge-platform-insteonlocal/files/3998205/Homekit.with.Insteon.docx)

I have left comments and  help - Thank you for the work on this Plugin...

**Comment by kuestess** [comment]
@BlueiPhone Moving this to a new issue.

@mkellsy This seems to only be an issue for HOOBS installs - any reason for the restrictions?  There were only minor fixes in 0.4.5-1, specifically for valves, so will catch this in the next update.  0.4.5 should work fine for the time being.

**Comment by mkellsy** [comment]
I attempted to instal this on my vanilla Homebridge setup, and I get the same issue.

```
sudo npm install -g --unsafe-perm homebridge-platform-insteonlocal
```
Installs version 0.4.5.

To get 0.4.5-1 installed I have to type in this.
```
sudo npm install -g --unsafe-perm homebridge-platform-insteonlocal@0.4.5-1
```

I have ran across this with many NPM packages for many different projects. When ever I run betas and the version looks like this 0.1.0-beta.1, or 0.1.0-1, NPM won't add the @latest tag to version with a "-". Then to further this I am unable to publish 0.1.1, I have to increase the version to 0.2.1. NPM treats "-" wired. I have opened countless support tasks with them, and the answer is always, reserve ".0" for betas, and release under ".1".

**Comment by kuestess** [comment]
@mkellsy Try without the version tag.  I just installed on a clean test system using `npm -g install homebridge-platform-insteonlocal` and it installs 0.4.5-1.

**Comment by BlueiPhone** [comment]
Mike,

 

I am still working on this problem and I need to put homebridge into debug mode.

I did as kuestess suggested but

@BlueiPhone <https://github.com/BlueiPhone>  I'm not familiar with HOOBS, but maybe you can translate how to do this in that install. First, you need to stop the homebridge service. Next, go into terminal and type homebridge -D. This will run homebridge in your console in debug mode, with output directly in the console. Once you stop it in the terminal (ctrl-c) that will stop homebridge and then you can go back and restart the service. If you can post the output that results in all three fan buttons being on, that will help in debugging.

This was my output.

hoobs@hoobs:~/.hoobs/etc <mailto:hoobs@hoobs:~/.hoobs/etc>  $ homebridge -D

Enviornment: NPM Cache OK

Enviornment: NPM Configuration OK

Enviornment: GYP Build Cache is Root Locked

Enviornment: NPM Configuration Reset

[12/28/2019, 6:55:54 AM] listen EADDRINUSE: address already in use :::8080

Error: listen EADDRINUSE: address already in use :::8080

    at Server.setupListenHandle [as _listen2] (net.js:1280:14)

    at listenInCluster (net.js:1328:12)

    at Server.listen (net.js:1415:7)

    at Function.serverListen [as listen] (/home/hoobs/.hoobs/node_modules/express-ws/lib/index.js:42:40)

    at API.start (/home/hoobs/.hoobs/lib/api.js:158:17)

    at module.exports (/home/hoobs/.hoobs/lib/cli.js:174:21)

    at process._tickCallback (internal/process/next_tick.js:68:7)

[HOOBS] Stopping server.

hoobs@hoobs:~/.hoobs/etc <mailto:hoobs@hoobs:~/.hoobs/etc>  $

How to I put homebridge under HOOBS in debug mode?

Clay

**Comment by mkellsy** [comment]
`hoobs -D`

HOOBS debug output is much more than Homebridge because it includes API requests.

As of 3.1.14, there is a `sudo hoobs service log`, this will chase the log of the service so you don't need to stop the service at all.

**Comment by BlueiPhone** [comment]
Michael,

 

I am running 3.1.14 so at the terminal mode, I can type “hoobs -D” and it will start the debug mode.

…. Now I do what I want to trace..

How do I turn it off?

 

Where is the log stored @?

 

Tks again for the help…

 

Clay

**Comment by mkellsy** [comment]
The log is the stdout, same as Homebridge. To quit is just a ctrl+c, same as Homebridge or any other *nix app. Don't want debug don't use the -D, or simply start the service.

HOOBS uses Homebridge under the hood. So developing with vanilla Homebridge is essentially the same thing. In fact we actually recommend using Homebridge to develop plugins because it is easier.

**Comment by BlueiPhone** [comment]
Mike,

 

Here is what I get whenever I try hoobs -D command:

 

hoobs@hoobs:~/config $ hoobs -D

Enviornment: NPM Cache OK

Enviornment: NPM Configuration OK

Enviornment: GYP Build Cache is Root Locked

Enviornment: NPM Configuration Reset

[12/29/2019, 6:16:27 AM] listen EADDRINUSE: address already in use :::8080

Error: listen EADDRINUSE: address already in use :::8080

    at Server.setupListenHandle [as _listen2] (net.js:1280:14)

    at listenInCluster (net.js:1328:12)

    at Server.listen (net.js:1415:7)

    at Function.serverListen [as listen] (/home/hoobs/.hoobs/node_modules/express-ws/lib/index.js:42:40)

    at API.start (/home/hoobs/.hoobs/lib/api.js:158:17)

    at module.exports (/home/hoobs/.hoobs/lib/cli.js:174:21)

    at process._tickCallback (internal/process/next_tick.js:68:7)

[HOOBS] Stopping server.

hoobs@hoobs:~/config $

 

What am I doing wrong?

 

Clay

**Comment by mkellsy** [comment]
You need to stop the hoobs service first.
```
sudo systemctrl stop hoobs
```
or 
```
sudo systemctrl stop homebridge
```

**Comment by BlueiPhone** [comment]
Mike,

 

Tried both:

 

hoobs@hoobs:~/config $ sudo systemctrl stop hoobs

sudo: systemctrl: command not found

hoobs@hoobs:~/config $ sudo systemctrl stop homebridge

sudo: systemctrl: command not found

hoobs@hoobs:~/config $

 

?????

**Comment by mkellsy** [comment]
Typo, I usually tab the command in, its systemctl not systemctrl.
```
sudo systemctl stop hoobs
```
or
```
sudo systemctl stop homebridge
```

**Comment by BlueiPhone** [comment]
I tried:

 

hoobs@hoobs:~/.hoobs/etc $ sudo systemctl stop hoobs

Failed to stop hoobs.service: Unit hoobs.service not loaded.

hoobs@hoobs:~/.hoobs/etc $ 

 

If I type sudo systemctl stop homebridge the screen clears and I am presented with the boot screen for HOOBS??

**Comment by mkellsy** [comment]
I am confused what you are trying to do. Is the wrong issue? Wrong repo?
This is the homebridge-platform-insteonlocal repo.

These notes are for putting HOOBS into a state to run debug mode.

1. Stop the HOOBS service
```
sudo systemctl stop hoobs
```
or
```
sudo systemctl stop homebridge
```

2. Run HOOBS in debug mode
```
hoobs -D
```

3. After you get what you need from the output, start the hoobs service
```
sudo systemctl start hoobs
```
or
```
sudo systemctl start homebridge
```

If this is not what you need, please open a issue on the HOOBS repo.
https://github.com/hoobs-org/HOOBS/issues

**Comment by BlueiPhone** [comment]
Mike,

 

I know am trying to resolve this problem we opened up .

 

I tried:

 

hoobs@hoobs:~/.hoobs/etc <mailto:hoobs@hoobs:~/.hoobs/etc>  $ sudo systemctl stop hoobs

Failed to stop hoobs.service: Unit hoobs.service not loaded.

hoobs@hoobs:~/.hoobs/etc <mailto:hoobs@hoobs:~/.hoobs/etc>  $ 

 

If I type sudo systemctl stop homebridge the screen clears and I am presented with the boot screen for HOOBS??

 

Mike I am very frustrated about this too and I need the debug output to close this issue up.

This seems so simple… but I am just spinning my wheels and getting nowhere…

 

Please, I need you help…

 

Thank you,

 

Clay

**Comment by mkellsy** [comment]
This all needs to be done from an SSH terminal, the terminal in HOOBS will not work because you are stopping it.

After you run sudo systemctl stop homebridge then run this.
```
hoobs -D
```

Again this needs to be done from SSH.
If you are using a prebuilt image the user is `hoobs` and the password is `hoobsadmin`

SSH command from a Mac or Linux terminal
```
ssh hoobs@hoobs.local
```
hoobs@hoobs.local is [username]@[ip address or host name]

**Comment by BlueiPhone** [comment]
Mike,

 

Now I better understand …

 

I will use putty from my windoze machine…

 

I will try it later and report back to you…

 

Tks…

 

Clay

**Comment by BlueiPhone** [comment]
Mike,

 

Thank you again for your help and understanding.

 

I did get the traces from the debug and passed them on to Kuester to look at.

 

I am hoping to have the plugin working correctly and put this behind me.

 

Clay
