### ISSUE TITLE
2243 Install issue

### ISSUE THREAD

**Issue by bls8486** [kuestess/homebridge-platform-insteonlocal#86]
@rasod 

When installing the plugin, I get the following errors.

```
serialport.target.mk:110: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.14.108-ti-r113
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN notsup Unsupported engine for spark@1.1.1: wanted: {"node":"^0.10.26"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: spark@1.1.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 (node_modules/homebridge-platform-insteonlocal/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

node v12.14.1

running homebridge as a service.  Installed homebridge with these instructions 
[https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux](url)

**Comment by rasod** [comment]
Are you trying to use the serial modem? What device are you running Homebridge on?

**Comment by bls8486** [comment]
> Are you trying to use the serial modem? What device are you running Homebridge on?

I am trying to install on a Hub Pro and use the serial modem to talk to the PLM.

**Comment by rasod** [comment]
What OS image did you Flash the Hub with?

**Comment by bls8486** [comment]
9.9

**Comment by rasod** [comment]
ok it appears that home-controller (which is the main dependancy for this plugin) is dependant on serialport and it is not compiling correctly. 6.2.2 is a rather old version of serial port I'm not sure why it would be installing that one and not the latest version.

**Comment by kuestess** [comment]
@bls8486 I get this error too - not sure why home-controller uses such an old version.  If you go to `/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport` and type `npm install` it should install the latest version just fine.

**Comment by rasod** [comment]
It appears that the version of home-controller published to NPM is 0.8.2 that version has the dependancy for serialport maxed out at 6x. There are newer versions of home-controller but they don't appear to have been published to NPM.

**Comment by bls8486** [comment]
I tried to install the most recent version in the insteon node module directory, but that failed.  Tried to install serialport@6.2.2 but that failed too.

Might be that I am a novice.

Any suggestions?

**Comment by kuestess** [comment]
@bls8486 Try installing `serial port` globally `npm -g install serial port`.  If that doesn't work by itself, copy the resulting global `serialport` directory under the `home-controller` directory.

**Comment by bls8486** [comment]
Same result.  I am in the process of going to an earlier node version.  What are you guys running?

And thank you for your ongoing support.

**Comment by rasod** [comment]
Node 8.11.4
NPM 5.6.0

**Comment by bls8486** [comment]
Rolled back Node.  Installed serial port globally and then installed this module.  So far im up and running.  No devices configured yet.  Thank you again for the help.
