### ISSUE TITLE
New device, can't link

### ISSUE THREAD

**Issue by ctgreybeard** [kuestess/homebridge-platform-insteonlocal#87]
I had to replace an Insteon bulb today and I tried linking using the GUI.

Config here: https://gist.github.com/ctgreybeard/a98e041cfac4a1bd152eb6f47cf6a46c

First, I'm not sure what form the ID of the bulb should be. I seem to get the best results with the "dotted" form. Other forms get `TypeError: self.insteonJSON.devices.forEach is not a function`

But when I do try to link I get:

```
Linking 26.5B.ED to hub
Error linking 26.5B.ED to hub
```

I changed the config to the new ID (the old bulb ended with "BD") and restarted HB. Then I tried the GUI to link and get the above response.

Also, Get Links returns no links at all. insteon.json has empty arrays.  Like this
```
{
    "hub": {
        "info": {},
        "links": []
    },
    "devices": [],
    "scenes": {}
}
```

**Comment by ctgreybeard** [comment]
I've made some progress. After updating node and the modules I now get:

```
Linking 26.5B.ED to hub
{
  raw: '02530100265bed013a42',
  type: '53',
  controller: true,
  wasDeleted: false,
  group: 0,
  id: '265bed',
  deviceCategory: { id: 1, name: 'Dimmable Lighting Control' },
  deviceSubcategory: { id: 1 },
  firmwareVersion: '3a'
}
Linking hub to 26.5B.ED
Error linking 26.5B.ED to hubnull
Found  in Insteon config
Found MBR #1 in homebridge config
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
```

I don't know enough to be able to interpret this but `hubnull` doesn't look right.

And I cannot control the light.

**Comment by kuestess** [comment]
@ctgreybeard You don't need to have the device in the config to link - what do you get if you enter the 'undotted' device ID?  I don't sanitize the inputs on linking (probably should) so it expects undotted.

**Comment by ctgreybeard** [comment]
Thanks for the reply!

```
Linking 265BED to hub
{
  raw: '02530100265bed013a42',
  type: '53',
  controller: true,
  wasDeleted: false,
  group: 0,
  id: '265bed',
  deviceCategory: { id: 1, name: 'Dimmable Lighting Control' },
  deviceSubcategory: { id: 1 },
  firmwareVersion: '3a'
}
Linking hub to 265BED
Error linking 265BED to hubnull
Found  in Insteon config
Found MBR #1 in homebridge config
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
```

**Comment by kuestess** [comment]
@ctgreybeard Yeah, `hubnull` ain't right.  Go to the Hub page and click 'Get Hub Info' then see if you get a better result.  It doesn't know the Hub address until you do that (probably should fix that too).

**Comment by ctgreybeard** [comment]
It did have nothing on the hub page but I did get the hub info a while ago. It says:

```
Hub Information
Hub address: /dev/cu.usbserial-A60089QK
Hub port: undefined
Hub model: 2413
ID: 13ADEA
Firmware Version: 92
```

**Comment by ctgreybeard** [comment]
I'm trying to install a test version and suddenly it won't install because home-controller is asking for a very old version of serialport that won't compile. Your dependency on home-controller calls for >=0.8.0 but the latest is 0.9.0 which calls for a later version of serialport. I'm not sure why it's not picking up the later version of home-controller.

**Comment by rasod** [comment]
0.9.0 has not been published to NPM. We are dealing with the same problem with #86

**Comment by ctgreybeard** [comment]
Ah, thanks. I think I can fudge it. Tomorrow ...

**Comment by kuestess** [comment]
@ctgreybeard @rasod Just pushed a new version that should install the latest `serialport` version despite the latest version specified in the `home-controller` package.json.

**Comment by ctgreybeard** [comment]
@kuestess Thanks! I have moved my homebridge installation to a Raspberry PI4 from the Mac mini that it was on. This meant I had to re-do all my devices because homekit didn't recognize the moved homebridge. But it wasn't too bad to add the devices back into the  scenes and all.

But, with the move, I got yet another version of node (v10.15.2) and npm (5.8.0) which compiles the older version of serialport. I haven't yet picked up your newer release but I  will in the next couple of days. Interestingly, although these are the distribution versions available, this npm complains that the node version isn't supported. It appears to work fine, it just gives me a warning every time I run it.

Can you explain how to use the web pages? I can't seem to make much sense of them and I noticed that I am not seeing updates when I turn on a wall switch (for instance) where I know I used to see them. I have a feeling I lost  some links and maybe the web pages can let me get them back. Here is what I see:

Configuration page: Hub configuration and the devices from config.json. Looks correct

Hub page: Address, model, ID all correct, Links only shows three links for two devices. These are the ones I had been working with (two Insteon bulbs)

Devices page: The same two devices. One has no links listed, showed an error getting Links when I used  Get Dev Info/Links. The other info looks OK though.

Link page: Just the link/unlink form and scenes.

I guess I don't understand why the config page and the devices page aren't showing the same devices. Hopefully you can get me straight?

**Comment by kuestess** [comment]
@ctgreybeard Sorry, I know the UI documentation sucks right now.  Config page is just that - homebridge config, and nothing to do with device management.  The rest of the pages are for device/link management, like the old houselinc.  

Best way to get going is on the Hub page - first click 'Get Hub info'.  This grabs the ID and other info from the hub.  Next, under 'Action', click 'Get Device Info/Links'.  This pulls all of the links, scenes, devices from the hub.  Now if you go to the 'Device' page, you should see all of your devices there.  Any that were defined in your homebridge config should already be named.  Once you select a device, then you can get its info under the action menu.  This pulls the device info/database.  Easiest way starting off is probably to click 'Get all Dev Links' in the top right.  It loops through each device and gets the device database.  Once that is populated, you can creates scenes using device names or IDs on the 'Link' page.  Hope that helps!

**Comment by ctgreybeard** [comment]
Thanks. That’s about how I thought it should work but there are only two devices discovered. And those two are the ones I was “playing” with a couple of days ago. None of the devices that are in the config appear on the devices page.

I’m wondering what happened to all the links and, more to the point, should I do a link for all the “missing” devices?  Will that correct the problem that I am seeing that the hub doesn’t see when I use a wall switch?

And, what use are the Scenes that I create on the hub? They aren’t related to the Scenes in Homekit are they?

**Comment by kuestess** [comment]
@ctgreybeard Hmm, that seems weird....assuming that you had all of your devices linked to the hub before, just moving to an Rpi shouldn't change anything.  The way that I get the devices from the hub is to pull all the links, get all the device IDs, and then filter for uniques.  If you don't have any scenes/links in the hub, it won't find them.  Are you able to control the 'missing' devices?

The scenes that you create on then Link page are no different than those from the Insteon app - just assign the Hub as a controller, pick an unused group number for the hub group, and then link away.  To set that scene up in homebridge, just do the normal config for a scene with the hub group number that you chose in the config.

**Comment by ctgreybeard** [comment]
Yes, strange. They all ***were*** linked at one time but sometime even before I moved the hub I think they disappeared. Perhaps the hub reset at some point? I don’t know.

I never used scenes on the hub that I am aware of. When you say “just do the normal config for a scene” it has no meaning to me. And I have no scenes in the homebridge config either. After I get this straight I might check it out though.

If I use the Link page and link all the missing devices will that fix the problem that the hub doesn’t see physical switch changes?

**Comment by kuestess** [comment]
@ctgreybeard By 'normal config for a scene' I mean in your config.json.  Insteon scenes work a lot better than configuring in the home app.  Linking the individual devices on the Link page should take care of your issue - it will automatically link the Hub as a controller of the device and vice-versa so physical switch changes show in the home app.

**Comment by ctgreybeard** [comment]
I tried using the Link page to link my devices but I get errors.

```
Linking 0B5DC6 to hub
Error linking 0B5DC6 to hub
Found MBR #X in Insteon config
Found MBR #1 in homebridge config
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
```

I have tried four different devices and all get the same response.

The MBR devices were there already from when I was trying to figure things out. I can control all my devices including the four that I am trying to link but the hub doesn't see any changes when I control them locally.

**Comment by ctgreybeard** [comment]
And when I tried to UNLINK it shut down Homebridge

```
Unlinking 0B5DC6 from hub
undefined
[1/22/2020, 10:09:49 AM] TypeError: Cannot read property 'deviceID' of undefined
    at /home/hb/Homebridge/bin/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2442:65
    at /home/hb/Homebridge/bin/node_modules/home-controller/node_modules/q/q.js:2055:17
    at runSingle (/home/hb/Homebridge/bin/node_modules/home-controller/node_modules/q/q.js:137:13)
    at flush (/home/hb/Homebridge/bin/node_modules/home-controller/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[1/22/2020, 10:09:49 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by kuestess** [comment]
@ctgreybeard Do you get any linking beeps from the hub?  Just confirming that you're linking one device at a time, no . delimiters or quotes.

**Comment by ctgreybeard** [comment]
Yes, I see the activity light flash, I hear a very quiet “beep”. I am entering one ID, lower or upper case hex (I tried both), six characters.

Do you know of a way to completely reset the hub? It may have some really old cruft from the years I was running Indigo. Or maybe I need a new one ...

**Comment by ctgreybeard** [comment]
I found out how to reset it.

**Comment by ctgreybeard** [comment]
Do you know if the RF dongle will work with homebridge-controller? https://www.smarthome.com/insteon-2448a7-portable-usb-adapter.html

Maybe as a 2413U?

**Comment by kuestess** [comment]
@ctgreybeard How much Insteon gear do you have!?! :-). I don't have one and haven't tried, but I bet it would work as a 2413U or setup like a Hub Pro.  Spec page show 19200 baud, so it must have a serial interface.

**Comment by ctgreybeard** [comment]
I have around 25 devices.

My 2413U is an antique. The hardware version is 1.0. I think the latest version is 2.5. I’m going to order a new one and also one of the 2448’s. That one will be good to use for testing upgrades, etc.

I’m still going to try resetting the current hub to see if that helps.

**Comment by kuestess** [comment]
@ctgreybeard I want to remember that the older devices have a slightly different command set which may be the source of issues for your 2413.

**Comment by ctgreybeard** [comment]
Ah! I didn’t know that. Mine certainly qualifies as “older” ... I have put in the order, both devices are in stock and should ship today. They are in California IIRC so it will be a few days to get here.

**Comment by ctgreybeard** [comment]
Well, it turns out that the 2448 is a Controller and not a modem so the **`2414U`** is what it will look like. It’s on order but this is a completely different beast that the `2413U`. It’s actually programmable and there is not a lot online about this one or the 2414. I’m still on the fence about whether to return it or try to make it into something.

**Comment by ctgreybeard** [comment]
I tried the reset for the controller this morning. It didn't go exactly as the manual said it would but it did clear the small link table that it had. However it still will not link from the web pages.

At this point it still controls my devices OK so I am going to leave it until Monday when the new 2413U should be here.

**Comment by ctgreybeard** [comment]
No joy!

I installed the new 2314U. It is working OK controlling devices, that's good, but it will not Link, I get the same error as the other, older one.

```
Building Hub scene data...
Getting Hub info
{ raw: '026053c0c403159e',
  type: '60',
  id: '53c0c4',
  deviceCategory: { id: 3, name: 'Network Bridges' },
  deviceSubcategory: { id: 21 },
  firmwareVersion: '9e' }
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
Building Hub scene data...
Getting devices from Hub
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
Building Hub scene data...
Linking 0B5DC6 to hub
Error linking 0B5DC6 to hub
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
Getting devices from Hub
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
```

Notice the `Linking 0B5DC6 to hub` in the middle  there with the error following. I tried a different device also with  the same results.

**Comment by kuestess** [comment]
@ctgreybeard Just unlinked and linked one of my devices successfully.  One thought - try putting the ID in all caps.

**Comment by ctgreybeard** [comment]
I have been using all caps, no dots, just as it shows in the log.

**Comment by ctgreybeard** [comment]
FOUND THE PROBLEM!!

I cannot link devices the begin with a zero ("0") !!

I don't know where the bug is yet.

**Comment by ctgreybeard** [comment]
Well, it was a little deeper than that but I am now convinced that some of my devices are too old to support linking the way it is implemented. There is another way that the Indigo app used but I don't know what that might be and I'm not going to spend much time looking into it.
