### ISSUE TITLE
Remote 4 Button Support

### ISSUE THREAD

**Issue by BlueiPhone** [kuestess/homebridge-platform-insteonlocal#88]
You said:
Remote support: Remotes are supported as on/off switches or stateless switches intended to be used in Homekit automation and/or scenes. Only 8-button mode is supported for now (happy to add 4-button support if someone is willing to test).

I am willing to test... add support for both 4 and 8 button remotes.

Just let me know what you need.

**Comment by THX723** [comment]
I'd also be willing to help test.

**Comment by kuestess** [comment]
@BlueiPhone @THX723 Thank you both.  Download the linked file below and rename from .txt to .js.  Put the config in from your homebridge config.json and put the remote Insteon ID in for foundID.  If you can push each button on the remote and paste the output here indicating which buttion was pushed, I'll see if I can get 4-button support working.

[https://github.com/kuestess/homebridge-platform-insteonlocal/files/4013375/eventlistener.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/4013375/eventlistener.txt)

**Comment by BlueiPhone** [comment]
Scott,

 

Here is the output:

 

When I press the “a” button:

Connected to Insteon Hub.  Server listening....

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000001","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000001CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000001","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000001CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"52F5D8","extended":false,"messageType":2,"hopsLeft":1,"maxHops":1,"command1":"11","command2":"01","raw":"02503F063C52F5D8451101"}}

Device ID: 3F063C

messageType: 2

Command1: 11

Command2: 01

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"110501","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"06","command2":"00","raw":"02503F063C110501CF0600"}}

Device ID: 3F063C

messageType: 6

Command1: 06

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"110501","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"06","command2":"00","raw":"02503F063C110501CF0600"}}

Device ID: 3F063C

messageType: 6

Command1: 06

Command2: 00

 

When I press the “b” button:

Connected to Insteon Hub.  Server listening....

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000002","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000002CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000002","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000002CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"52F5D8","extended":false,"messageType":2,"hopsLeft":1,"maxHops":1,"command1":"11","command2":"02","raw":"02503F063C52F5D8451102"}}

Device ID: 3F063C

messageType: 2

Command1: 11

Command2: 02

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"110302","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"06","command2":"00","raw":"02503F063C110302CF0600"}}

Device ID: 3F063C

messageType: 6

Command1: 06

Command2: 00

 

When I press the “c” button:

Connected to Insteon Hub.  Server listening....

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000003","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000003CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000003","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000003CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"52F5D8","extended":false,"messageType":2,"hopsLeft":1,"maxHops":1,"command1":"11","command2":"03","raw":"02503F063C52F5D8451103"}}

Device ID: 3F063C

messageType: 2

Command1: 11

Command2: 03

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"110303","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"06","command2":"00","raw":"02503F063C110303CF0600"}}

Device ID: 3F063C

messageType: 6

Command1: 06

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"110303","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"06","command2":"00","raw":"02503F063C110303CF0600"}}

Device ID: 3F063C

messageType: 6

Command1: 06

Command2: 00

 

When I press the “d” button:

e eventlistener.js

Connected to Insteon Hub.  Server listening....

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000004","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000004CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

Full data: {"standard":{"type":"50","id":"3F063C","gatewayId":"000004","extended":false,"messageType":6,"hopsLeft":3,"maxHops":3,"command1":"11","command2":"00","raw":"02503F063C000004CF1100"}}

Device ID: 3F063C

messageType: 6

Command1: 11

Command2: 00

**Comment by BlueiPhone** [comment]
Have you had a chance to look at this yet?? Is there anything more you need?
Clay

**Comment by kuestess** [comment]
@BlueiPhone Sorry, work/family taking priority for the time being.  Will hopefully be able to get to it later this week or next.

**Comment by BlueiPhone** [comment]
I do understand, “Thank You” for the reply…

**Comment by kuestess** [comment]
@BlueiPhone Just pushed 0.4.11 with initial support for 4-button remotes.

**Comment by BlueiPhone** [comment]
Scott,

 

When I press any of the remote buttons on my iPhone they light up but nothing happens with the Fan.

I tried running a trace and I saw no output from pressing the buttons.

--------------------------------------------------------------------------------

Here is the config I tried:

{

            "deviceType": "remote",

            "dimmable": "no",

            "Note": "Samantha's Bedroom Remote",

            "groupID": "18",

           "four_btn": true,

            "refresh": "0",

            "deviceID": "3F063C",

            "stateless": false,

            "groupMembers": "Remote c - Low,Remote b - Med,Remote a - High",

            "name": "Remote d - Off",

            "remotebtn": "D"

        },

        {

            "deviceType": "remote",

            "dimmable": "no",

            "Note": "Samantha's Bedroom Remote",

            "groupID": "17",

            "four_btn": true,

            "refresh": "0",

            "deviceID": "3F063C",

            "stateless": false,

            "groupMembers": "Remote d - Off,Remote b - Med,Remote a - High",

            "name": "Remote c - Low",

            "remotebtn": "C"

        },

        {

            "deviceType": "remote",

            "dimmable": "no",

            "Note": "Samantha's Bedroom Remote",

            "groupID": "16",

            "four_btn": true,

            "refresh": "0",

            "deviceID": "3F063C",

            "stateless": false,

            "groupMembers": "Remote d - Off,Remote c - Low,Remote a - High",

            "name": "Remote b - Med",

            "remotebtn": "B"

        },

        {

            "deviceType": "remote",

            "dimmable": "no",

            "Note": "Samantha's Bedroom Remote",

            "groupID": "15",

            "four_btn": true,

            "refresh": "0",

            "deviceID": "3F063C",

            "stateless": false,

            "groupMembers": "Remote d - Off,Remote c - Low,Remote b - Med",

            "name": "Remote a - High",

            "remotebtn": "A"

        }

**Comment by kuestess** [comment]
@BlueiPhone Remotes don't work like keypads do.  Because they are battery powered devices, they aren't listening for commands I can't send them a command from the plugin.  The only way they can be used is as a trigger for automation.  The plugin listens for a button press from the remote and then turns on the corresponding device in HomeKit.  To get it to do something, you'll need to set up an automation in the Home app with the remote button as the trigger.

**Comment by BlueiPhone** [comment]
Scott,

 

“Thank you” for your understanding and help. I re-read the details on the remote setup.

I am trying to set it up as a switch now…

 

If I am correct the remote switch buttons should be set as "stateless": true. Their normal position is “Off” and should only activate when I push the button, either on the physical switch or on the iPhone to activate a automation. 

 

When I set the config with "stateless": true, I am thinking that the button on the iPhone should light up when I push it for “ON” and then go to “Off” when I release it. This would be acting just like the physical switch. 

 

When I set the config with "stateless": true, when I press the button on the iPhone, a new screen pops up and asks me to define actions for the switch:

Single press                        Add

Double press                      Add

Long press                          Add

 

I have tried to Add actions to this screen but it always pops up when I press the button.

 

Is this how "stateless": true is supposed to work?

 

Clay

------------------------------------------

 

Here is the new config:

        {

            "name": "Remote Off SB",

            "deviceType": "remote",

            "four_btn": true,

            "deviceID": "3F063C",

            "stateless": true,

            "remotebtn": "D"

        },

        {

            "name": "Remote Low SB",

            "deviceType": "remote",

            "four_btn": true,

            "deviceID": "3F063C",

            "stateless": true,

            "remotebtn": "C"

        },

        {

            "name": "Remote Med SB",

           "deviceType": "remote",

            "four_btn": true,

            "deviceID": "3F063C",

            "stateless": true,

            "remotebtn": "B"

        },

        {

            "name": "Remote High SB",

            "deviceType": "remote",

            "four_btn": true,

            "deviceID": "3F063C",

            "stateless": true,

            "remotebtn": "A"

        }

**Comment by kuestess** [comment]
@BlueiPhone Just reset my remote config and set up again, and it saves/works just fine for me.  After you set the action, do you get all the way through the screen to test it?  This is a Home app issue rather than a plugin issue.

**Comment by BlueiPhone** [comment]
Thank you

**Comment by smcahee** [comment]
when y'all are talking about 4 button remotes, do you mean the 4-scene remote 2342-232 that has the rocker buttons labeled a-d on the right side only with down arrows on the left side and up arrows on the right?  ive got one and for the life of me can't get it to do anything in the home app.

ive got this code in the config file:

{
            "name": "Remote Button A",
            "deviceID": "XX.XX.XX",
            "deviceType": "remote",
            "remotebtn": "A",
            "four_btn": "true",
            "stateless": "false"
        },
        {
            "name": "Remote Button B",
            "deviceID": "XX.XX.XX",
            "deviceType": "remote",
            "remotebtn": "B",
            "four_btn": "true",
            "stateless": "false"
        },
        {
            "name": "Remote Button C",
            "deviceID": "XX.XX.XX",
            "deviceType": "remote",
            "remotebtn": "C",
            "four_btn": "true",
            "stateless": "false"
        },
        {
            "name": "Remote Button D",
            "deviceID": "XX.XX.XX",
            "deviceType": "remote",
            "remotebtn": "D",
            "four_btn": "true",
            "stateless": "false"
        },

and when i press a button i get this in the log:
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button A
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button B
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button C
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button D
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button A
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button B
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button C
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button D
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button A
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button B
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button C
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button D
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button A
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button B
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button C
[2/3/2021, 11:04:35 AM] [InsteonLocal] Got updated status for Remote Button D
[2/3/2021, 11:04:37 AM] [InsteonLocal] Got updated status for Remote Button A
[2/3/2021, 11:04:37 AM] [InsteonLocal] Got updated status for Remote Button B
[2/3/2021, 11:04:37 AM] [InsteonLocal] Got updated status for Remote Button C
[2/3/2021, 11:04:37 AM] [InsteonLocal] Got updated status for Remote Button D

but nothing else seems to happen.

am i missing something? not sure if i should have posted this as a new issue or here.

**Comment by kuestess** [comment]
@smcahee The plugin reports any button press on the remote (shown in your log above) which can be used to trigger a HomeKit scene or automation.  Outside of that, they don't provide a lot of functionality as you can't send on/off commands to them since they are battery powered.  If you use them to trigger an Insteon scene, you can set that up as a scene in the plugin.

**Comment by shereefalkady** [comment]
@kuestess can i activate a scene/group from a mini remote?
i mean it already does .... i just want it to update status in homekit


tried the below and many variations nothing works.... i only get the event not for correct group message
 {
                    "name": "Test Remote C",
                    "deviceID": "3F06AF",
                    "deviceType": "remote",
                    "remotebtn": "D",
                    "groupID": "4",
                    "dimmable": "no",
                    "groupMembers": "43E77B,44EF63"
                },

**Comment by shereefalkady** [comment]
sorry i meaqnt i tried it as so 

 {
                    "name": "G4",
                    "deviceID": "3F06AF",
                    "deviceType": "scene",
                    "groupID": "4",
                    "keypadbtn": "C",
                    "groupMembers": "43E77B,44EF63"
                },
