### ISSUE TITLE
Support for “stateless” in scenes

### ISSUE THREAD

**Issue by BlueiPhone** [kuestess/homebridge-platform-insteonlocal#90]
Asking for support for “stateless” in scenes. For the “Fan Off” button, it does turn the fan off, but it stays “ON”, but should it say “ON”, when the fan is off? It would be nice to have your “Stateless” option for the scenes. The options could be:

"stateless": “on”,  normal mode would be “on”
"stateless": “off”,  normal mode would be “off”
"stateless": false,  No stateless mode (Default)

For the “Fan Off” I would select, "stateless": “off”, then when I press the “Fan Off” button, the button would light up, the fan would turn off and then the “Fan Off” button would automatically turn off.

**Comment by ctgreybeard** [comment]
I don’t think that Homebridge can control what you are asking for and I think it goes against what a “Scene” means. When a Scene is “ON/Highlighted” that means that the Scene is SET or, you might say, ACTIVE. All the devices are in the state requested by the Scene. However, if you have a Fan On scene it should do exactly as you suggest, when the Fan is On it will be Highlighted, and if you press Fan On to turn it off then it should turn to fan off and go dark. So I then you have named the Scene incorrectly, call it Fan On and have it turn the Fan on then us it to also turn the Fan off.

I know that works for my lights scenes, I think that should work for your Fan scenes.

**Comment by BlueiPhone** [comment]
Bill,

 

The option “stateless” is valid for a remote in this Homebridge plugin, I am asking for this to be valid for a scene too. My example is for the “fan off”, right now the when I press the “Fan off” button in HomeKit it lights up and the fan turns off. The “stateless” option would correct this, when the button is pressed it would light up and then turn off, with the fan turning off also.

 

Clay

**Comment by ctgreybeard** [comment]
I understand what you are asking for but I don’t think this is possible. The scenes are inside Homekit and not under control of Homebridge. Homebridge can only control Accessories.

To get what you want I would try making.a Fan On scene where it controls the Fam Power to On. Then when the Fan is On it will be lit up. When you press it again it will turn the Fan Off and go dark. That way it follows the Fan state correctly.

**Comment by BlueiPhone** [comment]
I think that I found a solution to this problem with the switch not saying in sync with the Fan.

I now turn on the "Off" button whenever I select a speed of the fan. 
If I want "Low", I turn on the "Low" fan speed and the "Off" button.
If I want "Med", I turn on the "Med" fan speed and the "Off" button.
If I want "High", I turn on the "High" fan speed and the "Off" button.

Then whenever I turn off the fan I, select the "Off" button, and the current speed button turns off too.

I works great and the "Off" button is ready to use and is "Off" when the fan is  "Off"

**Comment by kuestess** [comment]
@BlueiPhone I think you would probably have a better experience if you added the 'ON' button as a device rather than the 'OFF' button.  The ON button should always match state of the fan without the need to manually turn it on, saving you a step and keeping things in sync.
