### ISSUE TITLE
Compilation failures with latest version

### ISSUE THREAD

**Issue by bfkeinberg** [kuestess/homebridge-platform-insteonlocal#92]
This no longer seems to install on Mac (older one, running High Sierra, but latest node)

> serialport@6.2.2 install /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.8.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/serialport/src/serialport.o
../src/serialport.cpp:41:48: error: too few arguments to function call, single argument 'context' was not specified
  v8::String::Utf8Value path(info[0]->ToString());
                             ~~~~~~~~~~~~~~~~~ ^
/Users/brian/Library/Caches/node-gyp/13.8.0/include/node/v8.h:2750:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/brian/Library/Caches/node-gyp/13.8.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/serialport.cpp:48:53: error: too few arguments to function call, single argument 'context' was not specified
  v8::Local<v8::Object> options = info[1]->ToObject();
                                  ~~~~~~~~~~~~~~~~~ ^
/Users/brian/Library/Caches/node-gyp/13.8.0/include/node/v8.h:2754:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(

**Comment by kuestess** [comment]
@bfkeinberg Unfortunately `home-controller` has a very old version of serialport as a dependency.  See here for the fix.  #91 I thought that I took care of this with npm-shrinkwrap.json, but will take another look at it.  Above should fix for you in the meantime.

**Comment by bfkeinberg** [comment]
Thanks, it builds now.
