### ISSUE TITLE
Issues setting up Insteonlocal or InsteonUI on my HubPro

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#94]
Hey Kuestess hope your doing well I have been looking for a great way to repurpose my HubPro while using it for the same use and i have found your work! firstly i want to thank you for all the hard work and effort you have put into this! This truly is a much better alternative to Insteon’s way! 

Anyway on to the issue. So i have got homebridge working on my hubpro but for some reason i cannot get InsteonUI or Insteonlocal (i’m not sure which one is which i’m a bit of a newb lol) to work and i’m not quite sure why. Any chance u or someone else can give me a hand?

**Comment by kuestess** [comment]
@yonigold1 Happy to help.  Sounds like you're able to boot up the Hub Pro and get homebridge running.  What messages are you getting when you install / try to install insteonlocal?

**Comment by yonigold1** [comment]
So i 100% have homebridge running as i can ssh into it as well as i can also get to the homebridge UI by going to the IP:Port and i get the nice friendly interface.
So after i get there i installed “Homebridge Platform Insteonlocal” and here is exactly where i’m stuck i’m really not sure where to go from here as i’ve tried following the steps given in the README under InsteonUI 🤔 

The image bellow is the homebridge logs from the status view on homebridge
<img width="1063" alt="A210C08E-A76F-45C1-B37A-CF1C1699DE92" src="https://user-images.githubusercontent.com/34217684/79301239-0d91df00-7eb7-11ea-90da-1c339aac106c.png">

Let me know if i’ve done something wrong :) thanks 🙏

**Comment by kuestess** [comment]
@yonigold1 It looks like your problem is with the serial port not being enabled.  Just confirming that you followed step 7 here: [https://github.com/kuestess/homebridge-platform-insteonlocal#using-the-hubpro-model-2243-beta](https://github.com/kuestess/homebridge-platform-insteonlocal#using-the-hubpro-model-2243-beta) and rebooted holding down the S2 button.  You'll need to hold down S2 every time you reboot, even from the terminal.  It will appear to work fine if you reboot in the terminal, but lots of people have had issues connecting to the serial port until they reboot with S2 held down.

**Comment by jackgold58** [comment]
I believe I did step 7 but i will check again and if somethings missing ill add it. But as for the S2 button i have been holding it every time i boot the hub.

**Comment by kuestess** [comment]
@yonigold1 @jackgold58 May be a linux permissions problem.  When you are logged in as the user that you use to run homebridge, type `groups`.  You should see `dialout` in the output.   If not, add your user to the `dialout` group with the command `sudo usermod -a -G dialout [your username]`, substituting in your username.  I think that should take care of your permission issue.  If that doesn't work, try `ls -al /dev/ttyS*` to confirm that the serial ports are present.

**Comment by jackgold58** [comment]
Thanks so much for the help I got the permission sorted out by adding the homebridge user instead of the Debian user, I can now connect to the insteonUI.  :D

I am now trying to add devices (mostly dimmers and on off switches) to the in the InsteonUI, they appear in `config.json`in homebridge but they don't show up in the devices tab in InsteonUI and when I check the `insteon.json` file all the info is blank.
<img width="571" alt="SS 2020-04-17 at 5 28 47 PM" src="https://user-images.githubusercontent.com/58569018/79616899-2a572e00-80d4-11ea-9f21-be3f8aa9f4e5.png">

I also see this error when I startup homebridge:
<img width="1050" alt="SS 2020-04-17 at 5 32 45 PM" src="https://user-images.githubusercontent.com/58569018/79616658-92594480-80d3-11ea-84f9-98b677f72f60.png">

I also have an issue with the Get Hub Info button. When I press it the webpage just goes blank.
<img width="1048" alt="SS 2020-04-17 at 5 47 13 PM" src="https://user-images.githubusercontent.com/58569018/79616990-68545200-80d4-11ea-8e1e-84b5c82be565.png">


Overall progress is being made!! Thanks so much for your time and help and sorry about the double accounts lol.

**Comment by kuestess** [comment]
@yonigold1 @jackgold58 Glad you got it working!  What you're seeing is an inherent byproduct of how Insteon works.  I'm assuming that you have everything set up with another hub - those devices are linked to that hub.  In order to see devices in the ui,  you'll need to link them to your hub pro as well.  TO do this easily, you can go to the 'Link' tab and enter the devices that you want to link to the hub.  Give it a shot with a device or two, then go back to the 'Hub' tab and click 'Get Hub Info'.  You should see the devices that you link now start to populate.

**Comment by jackgold58** [comment]
So I tried to add a switch to through the link Link tab and I enter the InsteonID of the switch (i tried 2 different ones) and I can't manage to get them added. Any ideas?

**Comment by jackgold58** [comment]
So i managed to get a switch to show up in my home app but it doesn't work I've tried flipping it on and off but no go it also shows in homebridge but the InsteonUI still does not list it down in the devices/links list

**Comment by kuestess** [comment]
@jackgold58 I think the root cause is still that the devices aren't linked to the HubPro.  Try the link page again, but enter device IDs without any ':' between the sections.  I need to add code to sanitize the input and remove, but for now the link page only works without adding the ':' separators.  If you did enter without separators, let me know and we can troubleshoot more.

**Comment by jackgold58** [comment]
Just tried readding the switch without "." (so it looked like this "495AB2" rather than this 49.5A.B2) and i still have no luck :(. After it says successfully added (on the link page) i go try to flick the toggle on my home app but no go

**Comment by kuestess** [comment]
@jackgold58 Looking back at your previous screenshots, I noticed that the Hub ID (on the Hub page) shows as undefined. If you click ‘Get Hub Info’ again, does the Insteon ID populate?  You can always manually link through the set button on the hub - should work just the same.

**Comment by jackgold58** [comment]
When I press Get Hub Info the following appears in the homebridge logs and the InsteonUI tab goes to a Safari cant connect to the server page.
<img width="1051" alt="SS 2020-04-18 at 11 01 11 PM" src="https://user-images.githubusercontent.com/58569018/79678347-813e2f80-81c8-11ea-8758-a58a7f645708.png">

**Comment by jackgold58** [comment]
i also just tried through the set button and also no go. im getting the feeling it has to do with the Hub info

**Comment by kuestess** [comment]
@jackgold58 Try shutting down homebridge and manually deleting your insteon.json.  Restart homebridge and then try ‘Get Hub Info’again.

**Comment by jackgold58** [comment]
Ok i deleted insteon.json and insteon.json.bak and i went on and pressed get hub info and same thing happens with the same error.

<img width="1034" alt="SS 2020-04-18 at 11 36 20 PM" src="https://user-images.githubusercontent.com/58569018/79678834-69b57580-81cd-11ea-824b-b06fc67bf686.png">

**Comment by kuestess** [comment]
@jackgold58 Seems like its still not connecting to the hub.  Can you run the attached script and post the output.  Just download, rename to `info.js` and then run `node info.js`.  Make sure you stop homebridge before running.
[info.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/4500121/info.txt)

**Comment by jackgold58** [comment]
I installed the home-controller module and then ran the script and this was the output.

<img width="1056" alt="SS 2020-04-19 at 6 08 42 PM" src="https://user-images.githubusercontent.com/58569018/79701155-d16cce80-8268-11ea-928c-03a1dfcf404d.png">

**Comment by jackgold58** [comment]
I managed to install the serialport module using the following command:

`sudo npm install serialport --unsafe-perm --build-from-source`

Now that home-controller and serialport are both installed in the local folder of info.js, I get the following output when running your script:

<img width="494" alt="SS 2020-04-19 at 6 40 54 PM" src="https://user-images.githubusercontent.com/58569018/79701713-4e9a4280-826d-11ea-8906-86d8325f5f8b.png">

**Comment by jackgold58** [comment]
I ran the following command:

`npm list -g --depth=2`

Under homebridge-platform-insteonlocal@0.4.12 it reports that serialport is invalid.

<img width="340" alt="SS 2020-04-19 at 6 50 37 PM" src="https://user-images.githubusercontent.com/58569018/79701888-aab19680-826e-11ea-8116-e76fe4ed5fdd.png">

And then reports the following at the end:

`npm ERR! invalid: serialport@8.0.7 /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/node_modules/serialport`

Could this have something to do with it not working?

**Comment by kuestess** [comment]
@jackgold58 Yep, I think that's part of the problem.  Try `npm -g install serialport` and then re-run the script.

**Comment by jackgold58** [comment]
I installed it globally and it won't run. The script only runs when the modules are installed locally, or with the modules linked locally. This [stackoverflow](https://stackoverflow.com/questions/42445679/node-not-finding-global-module) link implies that you cannot import modules that are installed globally.

**Comment by kuestess** [comment]
@jackgold58 Hmmm, that should work....  Did the global install work without error?  Try copying the contents of the global `serialport` directory into the local at `/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/node_modules/serialport` (per your above post).  `serialport` has been a pain in the rear - the dependency version in home-controller is old and the arm binary has to be compiled.  Thought that I'd taken care of that, but allot of people still have issues.

**Comment by jackgold58** [comment]
I copied over the newly compiled serialport module to the directory you specified. When I ran your script from the` /usr/lib/node_modules/homebridge-platform-insteonlocal` directory it ran without error. I then put back the old serialport module and tried again, and it also ran without error, so I don't think that was it.

I did, however, notice that after it reported that it connected to the Insteon Hub, it displayed "undefined" for the info parameter:

<img width="740" alt="SS 2020-04-19 at 10 26 09 PM" src="https://user-images.githubusercontent.com/58569018/79708203-c62b9a00-828c-11ea-8abf-7656b3a570e0.png">

Shouldn't it be displaying the Hub's info?

**Comment by kuestess** [comment]
@jackgold58 Thanks for bearing with me on this - something still doesn't seem right.  You should see the hub info after running that script.  Change into the `/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/node_modules` directory and delete the serialport and @serialport directories.  Go up one level to `/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/` and run `npm install serialport`.  Try the script and/or plugin then and see if you get info back.

**Comment by jackgold58** [comment]
No problem I wanna figure this out ahahah! :) So I'm still not getting any response. I connected directly to the serialport using the `screen` tool and tried sending the command `0260` that I found in the index.js file of home-controller. There was no response from the modem. Are there other commands I can try?

**Comment by kuestess** [comment]
@jackgold58 Wow, you're going super nerdy now!  Doing some experimentation....which version of Debian did you install on the Hub?

**Comment by jackgold58** [comment]
🤓 ahahahah this is the version AM3358 Debian 10.3 2020-04-06 4GB SD IoT

**Comment by kuestess** [comment]
@jackgold58 Awesome emoji!  ATDT!  So in trying to do a bit of troubleshooting last night, I managed to screw up my install on may Hub Pro and happened to end up getting the same permission denied error that you did initially.  I recreated everything from scratch and couldn't get the serial port to work using the image that you used above.  When I switched to the Debian 9.9 image, everything worked as before.  Here are the steps I followed: Flash the image, login and `sudo ant-get update` followed by `sudo apt-get upgrade` and then `sudo apt-get dist-upgrade`.  From there, I added a user using `adduser` - this made sure that the new user got added to all of the correct groups, including dialout.  I then followed the instructions to enable the serial port and rebooted.  From there, I installed node using [nvm](https://github.com/nvm-sh/nvm) (highly recommended) and uninstalled the node version that came with Debian.  Both homebridge and the plugin installed easily from there!  Give that a try and see if it works.  starting from scratch, but may be faster in the long run.

**Comment by yonigold1** [comment]
Hey sorrry for the late response ive just got a few things on my plate at the moment and i will attempt this as soon as i get the chance! :)

**Comment by yonigold1** [comment]
Ok so after doing everything you recommended here

> @jackgold58 Awesome emoji! ATDT! So in trying to do a bit of troubleshooting last night, I managed to screw up my install on may Hub Pro and happened to end up getting the same permission denied error that you did initially. I recreated everything from scratch and couldn't get the serial port to work using the image that you used above. When I switched to the Debian 9.9 image, everything worked as before. Here are the steps I followed: Flash the image, login and `sudo ant-get update` followed by `sudo apt-get upgrade` and then `sudo apt-get dist-upgrade`. From there, I added a user using `adduser` - this made sure that the new user got added to all of the correct groups, including dialout. I then followed the instructions to enable the serial port and rebooted. From there, I installed node using [nvm](https://github.com/nvm-sh/nvm) (highly recommended) and uninstalled the node version that came with Debian. Both homebridge and the plugin installed easily from there! Give that a try and see if it works. starting from scratch, but may be faster in the long run.

i finally got it to connect to the hub pro and it all works so smoothly now with no issues thanks so much for helping me out u this method of using my insteon devices is truly better than insteon!

**Comment by kuestess** [comment]
@jackgold58 @yonigold1 Good stuff - glad you got it working!
