### ISSUE TITLE
Error installing under Windows 10 and Node.js 12.16.2 (x64)

### ISSUE THREAD

**Issue by KWDeering** [kuestess/homebridge-platform-insteonlocal#95]
As of today, the Particle API can only be accessed through the api.particle.io domain. Access through the legacy domain api.spark.io has been disabled.

I notified Particle users with web applications that made requests to the api.spark.io domain of this planned end of life by email one month ago.
Installing on Windows 10, I get an error that spark has been deprecated...
C:\Windows\System32>npm -g install homebridge-platform-insteonlocal
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated spark@1.1.1: Use particle-api-js instead
npm WARN notsup Unsupported engine for spark@1.1.1: wanted: {"node":"^0.10.26"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: spark@1.1.1

+ homebridge-platform-insteonlocal@0.4.12
updated 1 package in 9.497s

Google says...
If you have a web application that stopped working because of the domain change, you must update it to make Particle API requests to the api.particle.io domain. No other change should be necessary in your application as the functionality of the Particle API offered by api.spark.io and api.particle.io is identical. In particular, no changes to the firmware running on devices is necessary.

If you use the deprecated sparkjs library, consider upgrading to particle-api-js 3 or at least updating to the latest version of sparkjs which is configured to use api.particle.io

**Comment by kuestess** [comment]
@KWDeering Does this prevent you from installing the plugin?  spark is an upstream dependency of home-controller and isn’t needed for this plugin.  It’s displayed this warning for a while, but hasn’t ever created a problem.

**Comment by KWDeering** [comment]
I reinstalled Node.js on Win10 and the install seems to have completed successfully.
Thanks.
