### ISSUE TITLE
Express Server not starting under Win 10

### ISSUE THREAD

**Issue by KWDeering** [kuestess/homebridge-platform-insteonlocal#96]
The Express server is not getting started.
Log...
[37m[4/19/2020, 12:43:52 PM][39m Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.4
[37m[4/19/2020, 12:43:52 PM][39m Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[37m[4/19/2020, 12:43:52 PM][39m ---
[37m[4/19/2020, 12:43:52 PM][39m Loading 3 platforms...
[37m[4/19/2020, 12:43:52 PM][39m [36m[Config][39m Initializing config platform...
[37m[4/19/2020, 12:43:52 PM][39m [36m[Config][39m Running in Service Mode
[37m[4/19/2020, 12:43:52 PM][39m [36m[HarmonyHub][39m Initializing HarmonyHubWebSocket platform...
[37m[4/19/2020, 12:43:52 PM][39m [36m[HarmonyHub][39m HarmonyPlatform Init
[37m[4/19/2020, 12:43:52 PM][39m [36m[Insteon Local Platform][39m Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from C:\Users\KDeering\.homebridge\config.json
Found 3 platform(s) in config
Creating new insteon.json
No devices in config
[37m[4/19/2020, 12:43:52 PM][39m [36m[Insteon Local Platform][39m Started connection watcher...
[37m[4/19/2020, 12:43:52 PM][39m [36m[Insteon Local Platform][39m Found 1 devices in config
[37m[4/19/2020, 12:43:52 PM][39m [36m[Insteon Local Platform][39m Initializing platform accessory 'Lamps'...

config.json
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "uuuuuu",
            "pass": "pppppp",
            "host": "192.168.1.11",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "use_express": true,
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Lamps",
                    "deviceID": "35.21.10",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                }
            ]
        }

I did a test install of Express as described on their web and was able to start a server and open the web on 3000

**Comment by kuestess** [comment]
@KWDeering Try removing `"use_express": true` from your config.

**Comment by KWDeering** [comment]
No difference.
[37m[4/19/2020, 6:21:30 PM][39m Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.4
[37m[4/19/2020, 6:21:30 PM][39m Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[37m[4/19/2020, 6:21:30 PM][39m ---
[37m[4/19/2020, 6:21:30 PM][39m Loading 3 platforms...
[37m[4/19/2020, 6:21:30 PM][39m [36m[Config][39m Initializing config platform...
[37m[4/19/2020, 6:21:30 PM][39m [36m[Config][39m Running in Service Mode
[37m[4/19/2020, 6:21:30 PM][39m [36m[HarmonyHub][39m Initializing HarmonyHubWebSocket platform...
[37m[4/19/2020, 6:21:30 PM][39m [36m[HarmonyHub][39m HarmonyPlatform Init
[37m[4/19/2020, 6:21:30 PM][39m [36m[Insteon Local Platform][39m Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from C:\Users\KDeering\.homebridge\config.json
Found 3 platform(s) in config
Creating new insteon.json
No devices in config
[37m[4/19/2020, 6:21:30 PM][39m [36m[Insteon Local Platform][39m Started connection watcher...
[37m[4/19/2020, 6:21:30 PM][39m [36m[Insteon Local Platform][39m Found 1 devices in config
[37m[4/19/2020, 6:21:30 PM][39m [36m[Insteon Local Platform][39m Initializing platform accessory 'Lamps'...
[37m[4/19/2020, 6:21:30 PM][39m Loading 0 accessories...

**Comment by kuestess** [comment]
@KWDeering Do you ever get a 'Connected to Insteon Model 2245 Hub...' in the log?  Not seeing some messages I would expect.

**Comment by KWDeering** [comment]
No I don't get such a message. Here's my Hub Info matching the config.json.
![File 2020-04-20, 08 27 31](https://user-images.githubusercontent.com/62318545/79751636-eb49f800-82e0-11ea-93d6-5dc6d92e1317.jpeg)
![File 2020-04-20, 08 32 39](https://user-images.githubusercontent.com/62318545/79752500-665fde00-82e2-11ea-974d-33e9026a2313.jpeg)
I can ping 192.168.1.11 OK.

**Comment by kuestess** [comment]
@KWDeering Thanks for the info.  Just confirming that you're using the 'Hub Username' and 'Hub Password' from the screenshot above in your config.  Are you able to control Insteon devices from the Home app?

**Comment by KWDeering** [comment]
After you asked me, I double checked and I had a uppercase I where I needed a lowercase L in my password. Updating the pw got it all working.
Sorry for bothering you about it

**Comment by kuestess** [comment]
@KWDeering No problem!  Sometimes just takes another set of eyes :-)
