### ISSUE TITLE
Garage Door shows "No Response" when opening

### ISSUE THREAD

**Issue by travisandkelly** [kuestess/homebridge-platform-insteonlocal#97]
When closing, IOlinc is reporting the proper status, but when opening, I get "No Response" after only about 7 seconds.
`        {
            "name": "Garage Door",
            "gdo_delay": "30",
            "deviceID": "1F.C6.48",
            "deviceType": "iolinc"
        }`

**Comment by kuestess** [comment]
@travisandkelly Does this happen when closing from the app, normal garage door button, or both?  Can you run homebridge in debug mode `homebridge -D` and post the log from when you have the issue?

**Comment by THX723** [comment]
@travisandkelly @kuestess I've been experiencing the same exact issue as well. I should also note my configuration is `inverted_sensor = false` or the sensor is `On` when the door is fully `Closed`.

I did finally get around to analyze this section of the code and believe I have identified the issues and came up with a working solution. Many thoughts of burning out my garage door opener from over 100 door open/close cycles of debugging. 😆 

 @kuestess I'll post the fix to a new pull request. If you concur with the change after initial review, maybe you can do a beta release so @travisandkelly can also help validate it.

As a side note, iolinc activity seems to trigger a crap ton of peripheral Insteon traffic. The debug log is virtually unreadable as the result. :yikes:

**Comment by kuestess** [comment]
Closing as this should be fixed with the latest release.
