### ISSUE TITLE
error installing - not able to access local:3000

### ISSUE THREAD

**Issue by elegua** [kuestess/homebridge-platform-insteonlocal#98]
Note that <me> is my actual system user name. I am running this on a Mac 10.11.6 (it's an old mini and this is as far as I can go).

npm WARN saveError ENOENT: **no such file or directory, open '/Users/<me>/package.json**'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for spark@1.1.1: wanted: {"node":"^0.10.26"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: spark@1.1.1
npm WARN enoent ENOENT: no such file or directory, open '/Users/<me>/package.json'
npm WARN elegua No description
npm WARN elegua No repository field.
npm WARN elegua No README data
npm WARN elegua No license field.

**Comment by elegua** [comment]
okay so it hid the carrots and left the folder tree black, but my user name is between /Users and /package.json.

**Comment by kuestess** [comment]
@elegua Can you clarify the error that you're seeing?  The title indicates issues with accessing local:3000, but I don't see that error anywhere in the above.  If you can provide more information on the line with 'ENOENT' - fine to leave out username, but troubleshooting will require knowing which package.json it can't find.

**Comment by elegua** [comment]
Sorry, haven't had time to look more into it. I run the plugin from home bridge, and everything says it's fine. If I run it by npm, I get the following:

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated spark@1.1.1: Use particle-api-js instead
npm WARN notsup Unsupported engine for spark@1.1.1: wanted: {"node":"^0.10.26"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: spark@1.1.1

+ homebridge-platform-insteonlocal@0.4.12
updated 1 package in 15.333s

**Comment by kuestess** [comment]
@elegua Those errors are fine to ignore.  The first just states that the `request` library is no longer being updated, the latter two are for two libraries that aren't used by the plugin.

**Comment by elegua** [comment]
Let me run the install again. I don’t understand it. If I install the plugin through homebridge, I don’t see any problems. However, if I go to local host, port 3k, I get nothing. Where can I go to troubleshoot this? Is there a web log?

**Comment by THX723** [comment]
Are you trying to access the InsteonUI? If so you need to insure “use_express” is set to true in your config.json. If not specified, the express server is disabled by default.

**Comment by elegua** [comment]
I assume that is how it should work. I don't know if it was supposed to install express, but I did try it manually. I get the below. I'll add the above to the config and see what happens.

2 warnings and 9 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/elegua/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/node_modules/serialport
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN elegua No description
npm WARN elegua No repository field.
npm WARN elegua No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 (node_modules/home-controller/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 (node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ express@4.17.1
updated 1 package and audited 1675 packages in 30.159s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by elegua** [comment]
Any guidance/documentation on how to add that to that option to the config?

**Comment by THX723** [comment]
The directions are on the main page of the repo:
https://github.com/kuestess/homebridge-platform-insteonlocal#configuration

Specifically this line: use_express: true or false to enable/disable Express server

**Comment by elegua** [comment]
So, I added the line, but it's not correct. The plugin says it's installed, but still no 127.0.0.1:3000. There's no way to load images.

I added to the top of the json.config the line use_express: true, but I get an error.

**Comment by THX723** [comment]
It would help if you show the log and the config.json entries.

Also, 127.0.0.1:3000 is assuming you are browsing locally (your Mac Mini). If you're browsing from another computer then you'll need to post to the Mac Mini's IP address.

**Comment by kuestess** [comment]
@elegua Based upon some of the errors from above, I would recommend uninstalling and reinstalling the plugin via `npm -g install homebridge-platform-insteonlocal`.  Posting your config will be helpful as well.

**Comment by elegua** [comment]
I think it's a problem with node.js. Below is the current config. I have smart things running. I tried reinstalling everything from scratch. I removed node. I used brew to install.

removing some of the samsung info...

{
    "bridge": {
        "name": "Homebridge 810C",
        "username": "",
        "port": 51241,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "SmartThings-v2",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "",
            "access_token": "",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "disableErrorReporting": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        }
    ]
}

**Comment by kuestess** [comment]
@elegua Big fan of brew, but for node I would highly recommend `nvm` - solves a lot of problems.  See here: [https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm)

**Comment by elegua** [comment]
Did NVM and installed node: edia-server:~ elegua$ nvm install node
Downloading and installing node v14.2.0...
Downloading https://nodejs.org/dist/v14.2.0/node-v14.2.0-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v14.2.0 (npm v6.14.4)
Creating default alias: default -> node (-> v14.2.0)

**Comment by elegua** [comment]
Okay, I am able to create a little JS file and start up a server. I got the 'Hello World' thing working. How do I include the server = true thing in the json.config file?

**Comment by kuestess** [comment]
@elegua You will need to reinstall homebridge and the plugin for your new install of node - follow the steps on the homebridge site and then install the plugin via `npm-g install homebridge-platform-insteonlocal`.  You should be able to exclude anything regarding express in your config to have the GUI start.

**Comment by elegua** [comment]
nothing on port 3000, I don't know if I am supposed to. I don't know if I need to manually add anything to the json.config or how to enter it. Just doesn't seem to want to work for me. Sucks, cause I had a bunch of Insteon stuff, but since I can't get anything to work with it, I am just getting rid of all of the devices. The smart things seems to work alright.

**Comment by kuestess** [comment]
@elegua Can you run homebridge in debug mode `homebridge -D` and post the output?  It seems like its not connecting to your hub which can be a straightforward fix.

**Comment by elegua** [comment]
I have been trying to get the node web server up and running to follow the directions. The localhost:3000 doesn't work. However, I was manually able to spin up a server. Someone mentioned making sure the server = true was in the json.config, but I honestly have no idea how to enter it into the config file.

I went ahead and captured all of the information from the hub, as per config, it's a 2245. I had the hub pro as well but Insteon isn't making it anymore, which eliminated HomeKit, so their devices are no longer an option for me, other than needing to create HomeBridge.

The only reason I had the 2245 is because Insteon dropped the ball on the Fanlinc, so I had to have some sort of hub to control just the two fans. Since this was turning into a problem, I bought enough GE Z-wave devices to replace all of the switches. If I could still get some use out of Insteon devices it would be great, but I fear with the direction Insteon is taking will mean the company won't be around long. I certainly will not buy any more devices until I know they are going to support HomeKit again. I prefer the wired over the wireless. Some devices cannot connect to the Samsung hub. So, enough devices need to be daisy chained to get them to work. Plus, they both now require HomeBridge to be of any use.

I have not tried to connect the Hub to Homebridge manually, because I don't know how. If there's an example json config I can give it a shot.

**Comment by kuestess** [comment]
@elegua If you can post the output requested above, I think we can get it working for you.  Homebridge and the plugin will actually run directly on the Hub Pro itself, which offers a very responsive experience.  I have a similar setup with ST as well - DTHs for Insteon devices are in another one of my repos, so I think you can get all of your Insteon gear running on all platforms.

**Comment by elegua** [comment]
Well, my Hub Pro died, and couldn’t be replaced. I can turn that on, but what do you want me to do, restart the server and get that? I’ve not configured anything, I’ve only installed the plugin.

**Comment by kuestess** [comment]
@elegua Lets set aside the Hub Pro for now and get your Mac working.  If you’ve got homebridge and the plugin reinstalled, run homebridge in debug mode `homebridge -D` and post the output.  I’m looking in particular for a message that says that it connected to the hub.  Your previous config should still be intact from the prior homebridge install, so start with that and we can troubleshoot from there.

**Comment by elegua** [comment]
This is the log on a restart......

[5/8/2020, 8:34:36 PM] [Config] Homebridge restart request received
[5/8/2020, 8:34:36 PM] [Config] No restart command defined, killing process...
[5/8/2020, 8:34:36 PM] [HB Supervisor] Stopping services...
[5/8/2020, 8:34:36 PM] Got SIGTERM, shutting down Homebridge...
[5/8/2020, 8:34:41 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/8/2020, 8:34:45 PM] [HB Supervisor] Homebridge Storage Path: /Users/elegua/.homebridge
[5/8/2020, 8:34:45 PM] [HB Supervisor] Homebridge Config Path: /Users/elegua/.homebridge/config.json
[5/8/2020, 8:34:45 PM] [HB Supervisor] Logging to /Users/elegua/.homebridge/homebridge.log
[5/8/2020, 8:34:45 PM] [HB Supervisor] OS: Darwin 15.6.0 x64
[5/8/2020, 8:34:45 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[5/8/2020, 8:34:45 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[5/8/2020, 8:34:45 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[5/8/2020, 8:34:45 PM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 55167
[5/8/2020, 8:34:54 PM] Loaded config.json with 0 accessories and 2 platforms.
[5/8/2020, 8:34:54 PM] ---
[5/8/2020, 8:35:00 PM] Loaded plugin: homebridge-config-ui-x
[5/8/2020, 8:35:00 PM] Registering platform 'homebridge-config-ui-x.config'
[5/8/2020, 8:35:00 PM] ---
[5/8/2020, 8:35:10 PM] Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.5
[5/8/2020, 8:35:10 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[5/8/2020, 8:35:10 PM] ---
[5/8/2020, 8:35:13 PM] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8581
[5/8/2020, 8:35:18 PM] Loaded plugin: homebridge-smartthings-v2
[5/8/2020, 8:35:18 PM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[5/8/2020, 8:35:18 PM] ---
[5/8/2020, 8:35:18 PM] Loading 2 platforms...
[5/8/2020, 8:35:18 PM] [Config] Initializing config platform...
[5/8/2020, 8:35:18 PM] [Config] Running in Service Mode
[5/8/2020, 8:35:18 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...
INFO: Homebridge Version: 2.5
INFO: SmartThings-v2 Plugin Version: 2.3.3
INFO: Checking Package Version for Updates...
INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
GOOD: Refreshing All Device Data | Source: (First Launch)
Setup Payload:
X-HM://0024GA4JJ5M01
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    └────────────┘     
                       
[5/8/2020, 8:35:19 PM] Homebridge is running on port 51241.
NOTICE: Temperature Unit is Now: (F)
NOTICE: Updating Global Values | HubIP: 192.168.1.18 | UseLocal: false
WARN: Devices to Remove: (0) []
INFO: Devices to Update: (13)
GOOD: Devices to Create: (0) []
ALERT: Total Initialization Time: (1 seconds)
NOTICE: Unknown Capabilities: ["Zw Multichannel","Ocf","Tv Channel","Execute","Media Input Source","Media Playback","custom.error","custom.picturemode","custom.soundmode","custom.accessibility","custom.launchapp","custom.recording","custom.tvsearch"]
INFO: SmartThings DeviceCache Size: (13)
INFO: WebServer Initiated...
INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
INFO: Direct Connect Active | Listening at 192.168.1.22:8000
INFO: SmartThings-v2 Hub Communication Established
INFO: INFO: Your plugin version is up-to-date
NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.3

**Comment by kuestess** [comment]
@elegua Can you post your config - I see the platform registered, but no attempt to connect to the hub or poll device status.

**Comment by elegua** [comment]
Right, I haven’t put anything in the config. I don’t know how. I copied the Samsung and trying to see if I can figure out how to enter it.

**Comment by elegua** [comment]
I tried my hand at a config. I saw that there was a sample config in the repo. I had not noticed it was there before. I was only reading the text instructions. Below is the log with my attempt at updating the config. Below the log is the current config file.

[5/9/2020, 6:23:43 AM] [HB Supervisor] Restarting Homebridge...
[5/9/2020, 6:23:43 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/9/2020, 6:23:43 AM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 79062
[5/9/2020, 6:23:47 AM] Loaded config.json with 0 accessories and 3 platforms.
[5/9/2020, 6:23:47 AM] ---
[5/9/2020, 6:23:49 AM] Loaded plugin: homebridge-config-ui-x
[5/9/2020, 6:23:49 AM] Registering platform 'homebridge-config-ui-x.config'
[5/9/2020, 6:23:49 AM] ---
[5/9/2020, 6:23:54 AM] Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.5
[5/9/2020, 6:23:54 AM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[5/9/2020, 6:23:54 AM] ---
[5/9/2020, 6:23:59 AM] Loaded plugin: homebridge-smartthings-v2
[5/9/2020, 6:23:59 AM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[5/9/2020, 6:23:59 AM] ---
[5/9/2020, 6:23:59 AM] Loading 3 platforms...
[5/9/2020, 6:23:59 AM] [Config] Initializing config platform...
[5/9/2020, 6:23:59 AM] [Config] Running in Service Mode
[5/9/2020, 6:23:59 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
INFO: Homebridge Version: 2.5
INFO: SmartThings-v2 Plugin Version: 2.3.3
INFO: Checking Package Version for Updates...
[5/9/2020, 6:23:59 AM] [Insteon Local Platform] Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from /Users/elegua/.homebridge/config.json
Found 3 platform(s) in config
Creating new insteon.json
No devices in config
[5/9/2020, 6:24:00 AM] TypeError: Cannot read property 'length' of undefined
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:292:35)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:396:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
[5/9/2020, 6:24:00 AM] Got SIGTERM, shutting down Homebridge...
[5/9/2020, 6:24:05 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null




{
    "bridge": {
        "name": "Homebridge 810C",
        "username": "0E:46:49:82:81:0C",
        "port": 51241,
        "pin": "593-72-927"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "SmartThings-v2",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "",
            "access_token": "",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "disableErrorReporting": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        },
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "MyUser",
            "pass": "1234566",
            "host": "192.168.1.17",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600"
        }
        
    ]
}

**Comment by elegua** [comment]
Um... I think I got it running. I can load the server at 3000. I didn't realize there was a sample config. I only read the page with instructions and I thought 3000 was supposed to show up once the plugin was installed. Anyway... I am going to see if I can set up a device now.

**Comment by elegua** [comment]
So, I am about to give it a try, but I don't seem to be able to get anything from InsteonUI to copy into Homebridge. Do I need to manually add each device to the config?

**Comment by kuestess** [comment]
@elegua You can add devices to the config at the bottom of the config (main) page.  Just add a row for each device and after you save it should add to your config.

**Comment by elegua** [comment]
I started adding them and testing them. I have three lights set up. I wish I had known I could have done this a few months ago when my hub died. I am glad I had the old hub. I want to try out the fans next.

**Comment by kuestess** [comment]
@elegua Glad you got it working.  If your hub pro still powers up, that’s a real ideal setup.  It’s very responsive.

**Comment by elegua** [comment]
No, the hub pro died-died. This mini is 10 years old, I need to get a new one. I use it to do all sorts of things. I just fear it will die and then I have to go through this all over again. Getting ready to backup the .homebridge folder.

**Comment by kuestess** [comment]
@elegua Try calling Insteon - they replaced my hub pro for free out of warranty.  I’ve got an old mini (maybe slightly newer than yours) with esxi running on it - still powerful enough to run pfSense and some other virtual machines side by side.

**Comment by elegua** [comment]
Yeah, they may be refurbishing them. I have enough devices for now. Now that I bought a bunch to replace my Insteon. I am just going to see what happens with future devices. I prefer Insteon a lot... the wireless signal is not that great. Anyway, I just hope the mini keeps running until I can replace it and get it all setup again. Hopefully something commercial comes along already prepared to go.

**Comment by elegua** [comment]
On the fans, is it possible to set the fan speeds through Siri?

**Comment by kuestess** [comment]
@elegua I don't have a fanlinc to test with, but yes - you should be able to at least ask Siri to set it to a percent, which the plugin will then translate to low/med/high.

**Comment by elegua** [comment]
I figured out the problem, it was two fold. It would seem the lights I put in the fan are not dimmable. The other thing I ran into was determine if something was a switch or a lightbulb, etc.. Anyway, it seems everything is correct now.

**Comment by kjohnston84** [comment]
I am actually having a very similar issue right now. I have gone through all the same trouble shooting steps above and still cannot access 127.0.0.1:3000.

Here is the Insteon portion of my debug data:
[5/21/2020, 9:00:48 AM] [Insteon Home] Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from /Users/username/.homebridge/config.json
Found 6 platform(s) in config
Creating new insteon.json
No devices in config
[5/21/2020, 9:00:48 AM] [Insteon Home] Connecting to Insteon Model 2245 Hub...
[5/21/2020, 9:00:48 AM] [Insteon Home] Started connection watcher...
[5/21/2020, 9:00:48 AM] [Insteon Home] Found 1 devices in config
[5/21/2020, 9:00:48 AM] [Insteon Home] [20200521090048.512]: found Insteon Device, deviceid=51D1A7

And here is my config file (removed other platforms that are not relevant):
{
    "bridge": {
        "name": "Homebridge 54A7",
        "username": "username",
        "port": 51380,
        "pin": "123-45-678",
    },
    "accessories": [
        
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "InsteonLocal",
            "name": "Insteon Home",
            "user": "USER",
            "pass": "12345678",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Fan Light",
                    "deviceID": "51.D1.A7",
                    "dimmable": "yes",
                    "deviceType": "lightbulb"
                }
            ]
        }
    ]
}

Any help would be greatly appreciated!

**Comment by kuestess** [comment]
@kjohnston84 From your log above, it doesn't look like its connecting to the hub.  Is the user/pass from inside the Insteon app (Settings->House in the Insteon app), not the initial login?

**Comment by kjohnston84** [comment]
wow, cant believe I didn't try that. That fixed it right away. Thank you!

**Comment by kuestess** [comment]
np - glad it worked!
